function [result,report,scenario] = run_v5_all_channel_sequence()
%RUN_V5_ALL_CHANNEL_SEQUENCE Run and audit the 48 h all-channel V5 case.

here=fileparts(mfilename('fullpath'));
v5Root=fileparts(here);
addpath(v5Root,fullfile(v5Root,'config'),fullfile(v5Root,'model'), ...
    fullfile(v5Root,'source'),fullfile(v5Root,'scenarios'));

scenario=v5_build_all_channel_weather_task_scenario();
result=run_v5_model(scenario.input,scenario.config);
d=result.dispatch;
h=scenario.hourly;
cfg=result.config;
tol=1e-5;

sourceType=string(result.source.sourceType(:));
sourceBy=result.source.availableBySourceMW;
pWind=sum(sourceBy(:,sourceType=="wind"),2);
pPV=sum(sourceBy(:,sourceType=="pv"),2);
pTidal=sum(sourceBy(:,sourceType=="tidal"),2);

detail=[h,table(pWind,pPV,pTidal),d(:,2:end)];

p1=h.phase=="P1_SHORTAGE_DISCHARGE";
p2=h.phase=="P2_PV_RISE_CHARGE";
p3=h.phase=="P3_COMPUTE_START";
p4=h.phase=="P4_CABLE_SATURATION";
p5=h.phase=="P5_ELECTROLYSIS_START";
p6=h.phase=="P6_ALL_CHANNELS_CURTAIL";
p7=h.phase=="P7_RENEWABLE_DROP";
p8=h.phase=="P8_RECOVERY_TERMINAL";

effectiveCableLimit=min(result.input.cableSendLimitMW, ...
    result.input.gridAcceptLimitMW/(1-cfg.output.cableLossFraction));
satMask=p6 & ...
    d.pBessChargeMW>=cfg.bess.chargeMaxMW-1e-5 & ...
    d.pComputeFacilityMW>=cfg.compute.facilityMaxMW-1e-5 & ...
    d.pCableSendMW>=effectiveCableLimit-1e-5 & ...
    d.pElectrolyzerMW>=cfg.hydrogen.electrolyzerRatedMW-1e-5 & ...
    d.pCurtailmentMW>tol;

eventName=[ ...
    "低出力阶段触发电池放电"; ...
    "光伏爬升阶段触发电池充电"; ...
    "柔性算力在任务到达后启动"; ...
    "海缆在P4达到有效发送上限"; ...
    "制氢在海缆满载之后启动"; ...
    "管输和船运两个氢出口均被激活"; ...
    "P6同小时满足电池充电功率、算氢缆满载和弃电"; ...
    "P6内BESS达到SOC上限"; ...
    "首次关键事件顺序符合场景设计"; ...
    "突降幅度超过300 MW"; ...
    "突降阶段触发电池放电"; ...
    "突降阶段柔性算力低于饱和阶段"; ...
    "突降阶段电解槽和海缆均回落"; ...
    "突降阶段不出现弃电"; ...
    "弃电与刚性缺供不同时出现"; ...
    "恢复阶段存在电池回充"; ...
    "BESS循环期末状态回到真实初态"; ...
    "V5独立代数审计通过"; ...
    "Foundation 4.4母线交叉复核通过"; ...
    "三级择优保持经济主目标和最小总弃电"];
passed=false(size(eventName));
evidence=strings(size(eventName));

passed(1)=any(d.pBessDischargeMW(p1)>tol);
evidence(1)=sprintf('P1 max discharge %.3f MW', ...
    max(d.pBessDischargeMW(p1)));
passed(2)=pPV(find(p2,1,'last'))>pPV(find(p2,1,'first'))+tol && ...
    any(d.pBessChargeMW(p2)>tol);
evidence(2)=sprintf('PV %.3f -> %.3f MW; max charge %.3f MW', ...
    pPV(find(p2,1,'first')),pPV(find(p2,1,'last')), ...
    max(d.pBessChargeMW(p2)));
passed(3)=any(d.pComputeFlexibleMW(p3)>tol) && ...
    all(d.pComputeFlexibleMW(p1|p2)<=tol);
evidence(3)=sprintf('P3 max flexible compute %.3f MW', ...
    max(d.pComputeFlexibleMW(p3)));
passed(4)=any(d.pCableSendMW(p4)>=effectiveCableLimit(p4)-tol);
evidence(4)=sprintf('P4 cable send min/max %.3f / %.3f MW', ...
    min(d.pCableSendMW(p4)),max(d.pCableSendMW(p4)));
firstCableCap=first_time(h.timeH,d.pCableSendMW>=effectiveCableLimit-tol);
firstEly=first_time(h.timeH,d.pElectrolyzerMW>tol);
passed(5)=isfinite(firstCableCap) && isfinite(firstEly) && ...
    firstEly>firstCableCap && any(d.pElectrolyzerMW(p5)>tol);
evidence(5)=sprintf('first cable cap h%.0f; first electrolysis h%.0f', ...
    firstCableCap,firstEly);
passed(6)=sum(d.h2PipeWithdrawnKg)>tol && ...
    sum(d.h2ShipWithdrawnKg)>tol;
evidence(6)=sprintf('pipe/ship withdrawn %.3f / %.3f kg', ...
    sum(d.h2PipeWithdrawnKg),sum(d.h2ShipWithdrawnKg));
passed(7)=any(satMask);
evidence(7)=sprintf('simultaneous saturation count %d; P6 spill %.3f MWh', ...
    nnz(satMask),sum(d.pCurtailmentMW(p6))*cfg.time.dispatchStepH);
passed(8)=any(d.bessSOC(p6)>=cfg.bess.socMax-tol);
evidence(8)=sprintf('P6 max SOC %.6f; upper bound %.6f', ...
    max(d.bessSOC(p6)),cfg.bess.socMax);

eventTime=[ ...
    first_time(h.timeH,d.pBessDischargeMW>tol); ...
    first_time(h.timeH,p2 & d.pBessChargeMW>tol); ...
    first_time(h.timeH,d.pComputeFlexibleMW>tol); ...
    firstCableCap; ...
    firstEly; ...
    first_time(h.timeH,d.pCurtailmentMW>tol); ...
    first_time(h.timeH,p7 & d.pBessDischargeMW>tol)];
passed(9)=all(isfinite(eventTime)) && all(diff(eventTime)>=0) && ...
    eventTime(6)>=30 && eventTime(7)>=36;
evidence(9)=sprintf('event hours [%s]',strjoin(compose('%.0f',eventTime),', '));
preDrop=max(d.pSourceAvailableMW(p6));
dropMin=min(d.pSourceAvailableMW(p7));
passed(10)=preDrop-dropMin>300;
evidence(10)=sprintf('pre-drop max/drop min %.3f / %.3f MW', ...
    preDrop,dropMin);
passed(11)=any(d.pBessDischargeMW(p7)>tol);
evidence(11)=sprintf('P7 max discharge %.3f MW', ...
    max(d.pBessDischargeMW(p7)));
passed(12)=max(d.pComputeFacilityMW(p7))< ...
    max(d.pComputeFacilityMW(p6))-tol;
evidence(12)=sprintf('compute P6/P7 max %.3f / %.3f MW', ...
    max(d.pComputeFacilityMW(p6)),max(d.pComputeFacilityMW(p7)));
passed(13)=max(d.pElectrolyzerMW(p7))< ...
    max(d.pElectrolyzerMW(p6))-tol && ...
    max(d.pCableSendMW(p7))<max(d.pCableSendMW(p6))-tol;
evidence(13)=sprintf('P7 electrolyzer/cable max %.3f / %.3f MW', ...
    max(d.pElectrolyzerMW(p7)),max(d.pCableSendMW(p7)));
passed(14)=all(d.pCurtailmentMW(p7)<=tol);
evidence(14)=sprintf('P7 max curtailment %.3e MW', ...
    max(d.pCurtailmentMW(p7)));
rigidUnserved=d.pInternalUnservedMW+d.pMarineUnservedMW+ ...
    d.pComputeBaseUnservedMW;
passed(15)=~any(d.pCurtailmentMW>tol & rigidUnserved>tol);
evidence(15)=sprintf('coexistence count %d', ...
    nnz(d.pCurtailmentMW>tol & rigidUnserved>tol));
passed(16)=any(d.pBessChargeMW(p8)>tol);
evidence(16)=sprintf('P8 max charge %.3f MW', ...
    max(d.pBessChargeMW(p8)));
passed(17)=abs(d.bessEnergyMWh(end)- ...
    result.input.initial.bessEnergyMWh)<=tol;
evidence(17)=sprintf('initial/final %.6f / %.6f MWh', ...
    result.input.initial.bessEnergyMWh,d.bessEnergyMWh(end));
passed(18)=result.audit.pass;
evidence(18)=sprintf('bus residual %.3e MW; max capacity violation %.3e', ...
    result.audit.maxAbsBusBalanceResidualMW, ...
    result.audit.maxCapacityViolation);
passed(19)=result.foundationBusCrosscheck.pass;
evidence(19)=sprintf('foundation bus residual %.3e MW', ...
    result.foundationBusCrosscheck.maxAbsResidualMW);
secondaryTol=cfg.objective.primaryRelativeTolerance* ...
    (1+abs(result.meta.secondaryCurtailmentMWh));
passed(20)=result.meta.temporalTieBreakApplied && ...
    result.kpi.economicNetCostCNY<= ...
        result.meta.primaryObjectiveFirstPass+ ...
        result.meta.primaryBoundTolerance+tol && ...
    result.kpi.eCurtailmentMWh<= ...
        result.meta.secondaryCurtailmentMWh+secondaryTol+tol;
evidence(20)=sprintf( ...
    'economic %.3f <= %.3f; curtailment %.6f <= %.6f MWh', ...
    result.kpi.economicNetCostCNY, ...
    result.meta.primaryObjectiveFirstPass+result.meta.primaryBoundTolerance, ...
    result.kpi.eCurtailmentMWh, ...
    result.meta.secondaryCurtailmentMWh+secondaryTol);

report=table(eventName,passed,evidence);
eventType=[ ...
    "BESS_DISCHARGE";"BESS_CHARGE";"COMPUTE_START";"CABLE_CAP"; ...
    "ELECTROLYSIS_START";"CURTAILMENT_START";"DROP_BESS_DISCHARGE"];
eventTable=table(eventType,eventTime);

summary=table( ...
    result.kpi.eAvailableMWh,result.kpi.eSourceUsedMWh, ...
    result.kpi.eCurtailmentMWh,result.kpi.curtailmentRate, ...
    sum(d.pBessChargeMW)*cfg.time.dispatchStepH, ...
    sum(d.pBessDischargeMW)*cfg.time.dispatchStepH, ...
    result.kpi.eComputeServiceMWhCS,result.kpi.eCableReceivedMWh, ...
    sum(d.h2ProducedKg),result.kpi.h2PipeDeliveredKg, ...
    result.kpi.h2ShipDeliveredKg,result.kpi.ensMWh, ...
    result.audit.maxAbsBusBalanceResidualMW, ...
    'VariableNames',{'AvailableMWh','SourceUsedMWh','CurtailmentMWh', ...
    'CurtailmentRate','BessChargeMWh','BessDischargeMWh', ...
    'ComputeServiceMWhCS','CableReceivedMWh','H2ProducedKg', ...
    'H2PipeDeliveredKg','H2ShipDeliveredKg','ENSMWh', ...
    'MaxBusResidualMW'});

phaseCodes=scenario.phaseTable.phaseCode;
phaseStartH=scenario.phaseTable.startH;
phaseEndH=scenario.phaseTable.endH;
nPhase=numel(phaseCodes);
sourceMWh=zeros(nPhase,1);
windMWh=zeros(nPhase,1);
pvMWh=zeros(nPhase,1);
tidalMWh=zeros(nPhase,1);
bessChargeMWh=zeros(nPhase,1);
bessDischargeMWh=zeros(nPhase,1);
computeFacilityMWh=zeros(nPhase,1);
cableSendMWh=zeros(nPhase,1);
electrolyzerMWh=zeros(nPhase,1);
curtailmentMWh=zeros(nPhase,1);
rigidENSMWh=zeros(nPhase,1);
minimumSOC=zeros(nPhase,1);
maximumSOC=zeros(nPhase,1);
for k=1:nPhase
    mask=h.phase==phaseCodes(k);
    sourceMWh(k)=sum(d.pSourceAvailableMW(mask))*cfg.time.dispatchStepH;
    windMWh(k)=sum(pWind(mask))*cfg.time.dispatchStepH;
    pvMWh(k)=sum(pPV(mask))*cfg.time.dispatchStepH;
    tidalMWh(k)=sum(pTidal(mask))*cfg.time.dispatchStepH;
    bessChargeMWh(k)=sum(d.pBessChargeMW(mask))*cfg.time.dispatchStepH;
    bessDischargeMWh(k)=sum(d.pBessDischargeMW(mask))* ...
        cfg.time.dispatchStepH;
    computeFacilityMWh(k)=sum(d.pComputeFacilityMW(mask))* ...
        cfg.time.dispatchStepH;
    cableSendMWh(k)=sum(d.pCableSendMW(mask))*cfg.time.dispatchStepH;
    electrolyzerMWh(k)=sum(d.pElectrolyzerMW(mask))* ...
        cfg.time.dispatchStepH;
    curtailmentMWh(k)=sum(d.pCurtailmentMW(mask))* ...
        cfg.time.dispatchStepH;
    rigidENSMWh(k)=sum(rigidUnserved(mask))*cfg.time.dispatchStepH;
    minimumSOC(k)=min(d.bessSOC(mask));
    maximumSOC(k)=max(d.bessSOC(mask));
end
phaseSummary=table(phaseCodes,phaseStartH,phaseEndH,sourceMWh, ...
    windMWh,pvMWh,tidalMWh,bessChargeMWh,bessDischargeMWh, ...
    computeFacilityMWh,cableSendMWh,electrolyzerMWh, ...
    curtailmentMWh,rigidENSMWh,minimumSOC,maximumSOC);

outputDir=fullfile(v5Root,'outputs','v5_all_channel_weather_task_48h');
if ~isfolder(outputDir), mkdir(outputDir); end
writetable(scenario.phaseTable,fullfile(outputDir,'phase_definition.csv'));
writetable(detail,fullfile(outputDir,'hourly_weather_task_dispatch.csv'));
writetable(report,fullfile(outputDir,'validation_report.csv'));
writetable(eventTable,fullfile(outputDir,'event_timeline.csv'));
writetable(summary,fullfile(outputDir,'summary.csv'));
writetable(phaseSummary,fullfile(outputDir,'phase_summary.csv'));
save(fullfile(outputDir,'v5_all_channel_weather_task_48h.mat'), ...
    'result','report','scenario','eventTable','summary','phaseSummary');

disp(report);
disp(summary);
assert(all(passed),'V5 48 h all-channel sequence validation failed.');
fprintf('V5 48 H ALL-CHANNEL WEATHER/TASK SEQUENCE: PASSED\n');
end

function t=first_time(timeH,condition)
idx=find(condition,1,'first');
if isempty(idx), t=NaN; else, t=timeH(idx); end
end
