function report=test_v4_post_compute_redispatch_4_9()
%TEST_V4_POST_COMPUTE_REDISPATCH_4_9 Released-compute power regression.
% Numerical values are synthetic mechanism tests
% [assumption values, pending enterprise calibration].

modelDir=fileparts(mfilename('fullpath'));
v4Root=fileparts(fileparts(fileparts(modelDir)));
interfaceFolders=dir(fullfile(v4Root,'library','4.2*'));
assert(~isempty(interfaceFolders), ...
    'Cannot locate the frozen 4.2 interface folder.');
addpath(fullfile(interfaceFolders(1).folder,interfaceFolders(1).name), ...
    fullfile(v4Root,'modules','4.5_storage_hydrogen','integration'));
cfg=common_config_4_2('interface_smoke');
cfg=v4_apply_4_5_parameter_overlay(cfg);
N=4;
exportCap=min(cfg.output.cableSendCapacityMW, ...
    cfg.output.gridAcceptMaxMW);

d=struct;
d.computeRequestedMW=[20;20;20;20];
d.marineRequestedMW=[5;0;0;0];
d.marineAllocatedMW=[3;0;0;0];
d.exportRequestedMW=[exportCap-4;exportCap;exportCap;exportCap];
d.req45=struct( ...
    'bessChargeMW',zeros(N,1), ...
    'bessDischargeMW',zeros(N,1), ...
    'electrolyzerMW',[10;0;10;10]);
d.h2DeliveryTargetKg=[1000;1000;1000;1000];
d.h2DeliveryPlanKg=[0;0;0;1000];
d.h2InventoryPlanKg=zeros(N,1);
d.electrolyzerOperatingMinimumMW= ...
    cfg.hydrogen.electrolyzerModuleMinMW;
d.spillPlannedMW=zeros(N,1);

actual=[8;17;18;15];
a=v4_redispatch_after_compute_4_9(cfg,d,actual);

checkName=[ ...
    "12 MW release splits 2/4/6 to marine/export/H2"; ...
    "offline electrolyzer rejects a sub-minimum 3 MW start"; ...
    "online electrolyzer accepts a 2 MW increment"; ...
    "saturated H2 delivery leaves released power as spill"; ...
    "same-hour production and withdrawal preserve H2 inventory"; ...
    "released-power allocation identity closes"];
passed=false(size(checkName)); evidence=strings(size(checkName));
passed(1)=abs(a.marineTopUpMW(1)-2)<=1e-12 && ...
    abs(a.exportTopUpMW(1)-4)<=1e-12 && ...
    abs(a.electrolyzerTopUpMW(1)-6)<=1e-12 && ...
    abs(a.remainingReleasedMW(1))<=1e-12;
evidence(1)=sprintf('%.3f/%.3f/%.3f/%.3f MW', ...
    a.marineTopUpMW(1),a.exportTopUpMW(1), ...
    a.electrolyzerTopUpMW(1),a.remainingReleasedMW(1));
passed(2)=a.electrolyzerTopUpMW(2)==0 && ...
    abs(a.remainingReleasedMW(2)-3)<=1e-12;
evidence(2)=sprintf('top-up/spill %.3f/%.3f MW', ...
    a.electrolyzerTopUpMW(2),a.remainingReleasedMW(2));
passed(3)=abs(a.electrolyzerTopUpMW(3)-2)<=1e-12 && ...
    abs(a.remainingReleasedMW(3))<=1e-12;
evidence(3)=sprintf('top-up %.3f MW',a.electrolyzerTopUpMW(3));
passed(4)=a.electrolyzerTopUpMW(4)==0 && ...
    abs(a.remainingReleasedMW(4)-5)<=1e-12;
evidence(4)=sprintf('top-up/spill %.3f/%.3f MW', ...
    a.electrolyzerTopUpMW(4),a.remainingReleasedMW(4));
productionTopUpKg=1000*a.electrolyzerTopUpMW* ...
    cfg.time.dispatchStepH/cfg.hydrogen.secKWhPerKg;
passed(5)=max(abs(a.h2FlowThroughTopUpKg-productionTopUpKg))<=1e-12 && ...
    max(abs(a.h2InventoryPlanKg-d.h2InventoryPlanKg))<=1e-12;
evidence(5)=sprintf('max flow-through identity %.3e kg', ...
    max(abs(a.h2FlowThroughTopUpKg-productionTopUpKg)));
passed(6)=max(abs(a.powerClosureResidualMW))<=1e-12;
evidence(6)=sprintf('max residual %.3e MW', ...
    max(abs(a.powerClosureResidualMW)));

report=table(checkName,passed,evidence);
disp(report);
assert(all(passed),'Post-compute redispatch regression failed.');
end
