function result = v5_solve_dispatch(cfg,in)
%V5_SOLVE_DISPATCH Solve V5 MILP and return an auditable interval ledger.

mdl=v5_build_problem(cfg,in);
options=optimoptions('intlinprog', ...
    'Display',cfg.solver.display, ...
    'RelativeGapTolerance',cfg.solver.relativeGapTolerance, ...
    'MaxTime',cfg.solver.maxTimeS);

[sol,primaryValue,exitflag,solverOutput]=solve(mdl.problem, ...
    'Options',options);
assert(~isempty(fieldnames(sol)), ...
    'V5 solver returned no incumbent. Exitflag=%g. %s', ...
    exitflag,solver_message(solverOutput));

tieBreakApplied=false;
primaryBoundTolerance=NaN;
secondaryCurtailmentMWh=NaN;
temporalTieBreakApplied=false;
temporalTieBreak=string(field_or(cfg.objective,'temporalTieBreak','none'));
if strcmpi(cfg.objective.tieBreak,'minCurtailment') && ...
        ~strcmp(cfg.objective.primary,'curtailmentMWh')
    tieProblem=mdl.problem;
    primaryBoundTolerance=cfg.objective.primaryRelativeTolerance* ...
        (1+abs(primaryValue));
    tieProblem.Constraints.primaryObjectiveRetention = ...
        mdl.problem.Objective<=primaryValue+primaryBoundTolerance;
    tieProblem.Objective=mdl.expressions.eCurtailmentMWh;
    [tieSol,tieValue,tieExitflag,tieOutput]=solve(tieProblem, ...
        'Options',options);
    if ~isempty(fieldnames(tieSol)) && tieExitflag>0
        sol=tieSol;
        exitflag=tieExitflag;
        solverOutput=tieOutput;
        tieBreakApplied=true;
        secondaryCurtailmentMWh=tieValue;
    end
end

% Optional deterministic tertiary selection for mechanism-test narratives.
% It may only choose among solutions that retain both the primary optimum
% and the minimum total curtailment. The default is 'none'.
if tieBreakApplied && strcmpi(temporalTieBreak,'deferCurtailment')
    temporalProblem=tieProblem;
    secondaryTolerance=cfg.objective.primaryRelativeTolerance* ...
        (1+abs(secondaryCurtailmentMWh));
    temporalProblem.Constraints.secondaryCurtailmentRetention = ...
        mdl.expressions.eCurtailmentMWh<= ...
        secondaryCurtailmentMWh+secondaryTolerance;
    temporalWeight=(numel(in.timeH):-1:1)';
    temporalProblem.Objective=sum(temporalWeight.* ...
        mdl.expressions.pCurtailmentMW)*cfg.time.dispatchStepH;
    [temporalSol,~,temporalExitflag,temporalOutput]=solve( ...
        temporalProblem,'Options',options);
    if ~isempty(fieldnames(temporalSol)) && temporalExitflag>0
        sol=temporalSol;
        exitflag=temporalExitflag;
        solverOutput=temporalOutput;
        temporalTieBreakApplied=true;
    end
end

timeH=in.timeH;
pComputeFacilityMW=sol.pComputeBaseServedMW+sol.pComputeFlexibleMW;
dispatch=table( ...
    timeH, ...
    in.pSourceAvailableMW, ...
    sol.pSourceUsedMW, ...
    in.pSourceAvailableMW-sol.pSourceUsedMW, ...
    sol.pBessChargeMW, ...
    sol.pBessDischargeMW, ...
    sol.bessEnergyMWh, ...
    sol.bessEnergyMWh/cfg.bess.energyMWh, ...
    sol.pComputeBaseServedMW, ...
    sol.pComputeBaseUnservedMW, ...
    sol.pComputeFlexibleMW, ...
    pComputeFacilityMW, ...
    sol.nComputeOnline, ...
    sol.pElectrolyzerMW, ...
    sol.nElectrolyzerOnline, ...
    sol.nElectrolyzerStart, ...
    sol.h2ProducedKg, ...
    sol.h2InventoryKg, ...
    sol.h2PipeWithdrawnKg, ...
    sol.h2ShipWithdrawnKg, ...
    sol.pH2PowerMW, ...
    sol.h2ToPowerConsumedKg, ...
    sol.pCableSendMW, ...
    sol.pCableReceivedMW, ...
    sol.pMarineServedMW, ...
    sol.pMarineUnservedMW, ...
    sol.pInternalUnservedMW, ...
    'VariableNames',{ ...
    'timeH', ...
    'pSourceAvailableMW', ...
    'pSourceUsedMW', ...
    'pCurtailmentMW', ...
    'pBessChargeMW', ...
    'pBessDischargeMW', ...
    'bessEnergyMWh', ...
    'bessSOC', ...
    'pComputeBaseServedMW', ...
    'pComputeBaseUnservedMW', ...
    'pComputeFlexibleMW', ...
    'pComputeFacilityMW', ...
    'nComputeOnline', ...
    'pElectrolyzerMW', ...
    'nElectrolyzerOnline', ...
    'nElectrolyzerStart', ...
    'h2ProducedKg', ...
    'h2InventoryKg', ...
    'h2PipeWithdrawnKg', ...
    'h2ShipWithdrawnKg', ...
    'pH2PowerMW', ...
    'h2ToPowerConsumedKg', ...
    'pCableSendMW', ...
    'pCableReceivedMW', ...
    'pMarineServedMW', ...
    'pMarineUnservedMW', ...
    'pInternalUnservedMW'});

kpi=calculate_kpi(cfg,in,dispatch);
if kpi.eAvailableMWh>0
    kpi.renewableUtilization=kpi.eSourceUsedMWh/kpi.eAvailableMWh;
    kpi.curtailmentRate=kpi.eCurtailmentMWh/kpi.eAvailableMWh;
else
    kpi.renewableUtilization=NaN;
    kpi.curtailmentRate=NaN;
end
kpi.deterministicENSNotice = ...
    'ENS for this deterministic horizon; EENS requires scenario probabilities.';

result=struct;
result.meta=struct( ...
    'modelId',cfg.meta.modelId, ...
    'schemaId',cfg.meta.schemaId, ...
    'schemaVersion',cfg.meta.schemaVersion, ...
    'caseMode',cfg.meta.caseMode, ...
    'objectiveMethod',cfg.objective.method, ...
    'primaryObjective',cfg.objective.primary, ...
    'primaryObjectiveFirstPass',primaryValue, ...
    'tieBreakApplied',tieBreakApplied, ...
    'secondaryCurtailmentMWh',secondaryCurtailmentMWh, ...
    'temporalTieBreak',temporalTieBreak, ...
    'temporalTieBreakApplied',temporalTieBreakApplied, ...
    'primaryBoundTolerance',primaryBoundTolerance, ...
    'solver',cfg.solver.name, ...
    'exitflag',exitflag, ...
    'solverMessage',solver_message(solverOutput));
result.dispatch=dispatch;
result.kpi=kpi;
result.solution=sol;
result.audit=v5_validate_solution(cfg,in,result);
end

function kpi=calculate_kpi(cfg,in,d)
dt=cfg.time.dispatchStepH;
kpi=struct;
kpi.eAvailableMWh=sum(in.pSourceAvailableMW)*dt;
kpi.eSourceUsedMWh=sum(d.pSourceUsedMW)*dt;
kpi.eCurtailmentMWh=kpi.eAvailableMWh-kpi.eSourceUsedMWh;
kpi.eCableReceivedMWh=sum(d.pCableReceivedMW)*dt;
kpi.eComputeServiceMWhCS=sum(d.pComputeFacilityMW./in.pue)*dt;
kpi.h2PipeDeliveredKg=(1-cfg.hydrogen.pipeLossFraction)* ...
    sum(d.h2PipeWithdrawnKg);
kpi.h2ShipDeliveredKg=(1-cfg.hydrogen.shipLossFraction)* ...
    sum(d.h2ShipWithdrawnKg);
kpi.h2DeliveredKg=kpi.h2PipeDeliveredKg+kpi.h2ShipDeliveredKg;
kpi.ensInternalMWh=sum(d.pInternalUnservedMW)*dt;
kpi.ensMarineMWh=sum(d.pMarineUnservedMW)*dt;
kpi.ensComputeBaseMWh=sum(d.pComputeBaseUnservedMW)*dt;
kpi.ensMWh=kpi.ensInternalMWh+kpi.ensMarineMWh+ ...
    kpi.ensComputeBaseMWh;

kpi.operatingCostCNY = ...
    cfg.economic.sourceVariableOMCNYPerMWh*kpi.eSourceUsedMWh+ ...
    cfg.economic.bessDegradationCNYPerMWhDischarge* ...
        sum(d.pBessDischargeMW)*dt+ ...
    cfg.economic.hydrogenVariableCNYPerKgProduced*sum(d.h2ProducedKg)+ ...
    cfg.economic.electrolyzerStartCNYPerModule* ...
        sum(d.nElectrolyzerStart)+ ...
    cfg.economic.h2PipeTransportCNYPerKgWithdrawn* ...
        sum(d.h2PipeWithdrawnKg)+ ...
    cfg.economic.h2ShipTransportCNYPerKgWithdrawn* ...
        sum(d.h2ShipWithdrawnKg)+ ...
    cfg.economic.h2PowerVariableCNYPerMWh*sum(d.pH2PowerMW)*dt+ ...
    cfg.economic.cableVariableOMCNYPerMWhReceived* ...
        kpi.eCableReceivedMWh+ ...
    cfg.economic.computeVariableOMCNYPerMWhCS* ...
        kpi.eComputeServiceMWhCS+ ...
    cfg.economic.internalUnservedPenaltyCNYPerMWh* ...
        kpi.ensInternalMWh+ ...
    cfg.economic.marineUnservedPenaltyCNYPerMWh* ...
        kpi.ensMarineMWh+ ...
    cfg.economic.computeBaseUnservedPenaltyCNYPerMWh* ...
        kpi.ensComputeBaseMWh;
kpi.outputRevenueCNY = ...
    sum(in.electricityPriceCNYPerMWh.*d.pCableReceivedMW)*dt+ ...
    sum(in.hydrogenPriceCNYPerKg.* ...
        ((1-cfg.hydrogen.pipeLossFraction)*d.h2PipeWithdrawnKg+ ...
         (1-cfg.hydrogen.shipLossFraction)*d.h2ShipWithdrawnKg))+ ...
    sum(in.computePriceCNYPerMWhCS.* ...
        (d.pComputeFacilityMW./in.pue))*dt+ ...
    sum(in.marineServiceValueCNYPerMWh.*d.pMarineServedMW)*dt;
kpi.terminalAdjustmentCNY = ...
    cfg.economic.bessTerminalValueCNYPerMWh* ...
        (in.initial.bessEnergyMWh-d.bessEnergyMWh(end))+ ...
    cfg.economic.h2InventoryTerminalValueCNYPerKg* ...
        (in.initial.h2InventoryKg-d.h2InventoryKg(end));
kpi.economicNetCostCNY=kpi.operatingCostCNY- ...
    kpi.outputRevenueCNY+kpi.terminalAdjustmentCNY;

kpi.projectGHGKgCO2e = ...
    cfg.environment.sourceLifecycleKgCO2ePerMWhUsed* ...
        kpi.eSourceUsedMWh+ ...
    cfg.environment.bessThroughputKgCO2ePerMWh* ...
        sum(d.pBessChargeMW+d.pBessDischargeMW)*dt+ ...
    cfg.environment.hydrogenNonElectricKgCO2ePerKgProduced* ...
        sum(d.h2ProducedKg)+ ...
    cfg.environment.h2ShipKgCO2ePerKgWithdrawn* ...
        sum(d.h2ShipWithdrawnKg)+ ...
    cfg.environment.h2PipeKgCO2ePerKgWithdrawn* ...
        sum(d.h2PipeWithdrawnKg)+ ...
    cfg.environment.h2PowerNonFuelKgCO2ePerMWh* ...
        sum(d.pH2PowerMW)*dt;
kpi.avoidedBaselineGHGKgCO2e = ...
    cfg.environment.electricityBaselineKgCO2ePerMWhReceived* ...
        kpi.eCableReceivedMWh+ ...
    cfg.environment.hydrogenBaselineKgCO2ePerKgDelivered* ...
        kpi.h2DeliveredKg+ ...
    cfg.environment.computeBaselineKgCO2ePerMWhCS* ...
        kpi.eComputeServiceMWhCS+ ...
    cfg.environment.marineBaselineKgCO2ePerMWh* ...
        sum(d.pMarineServedMW)*dt;
kpi.netGHGKgCO2e=kpi.projectGHGKgCO2e- ...
    kpi.avoidedBaselineGHGKgCO2e;
end

function message=solver_message(output)
if isstruct(output) && isfield(output,'message')
    message=string(output.message);
else
    message="No solver message.";
end
end

function value=field_or(s,name,defaultValue)
if isfield(s,name), value=s.(name); else, value=defaultValue; end
end
