function audit = v5_validate_solution(cfg,in,result)
%V5_VALIDATE_SOLUTION Independent numerical checks of the returned ledger.

d=result.dispatch;
dt=cfg.time.dispatchStepH;
tolMW=1e-6;
tolState=1e-5;

busResidual=d.pSourceUsedMW+d.pBessDischargeMW+d.pH2PowerMW- ...
    (d.pBessChargeMW+d.pElectrolyzerMW+d.pComputeFacilityMW+ ...
     d.pCableSendMW+d.pMarineServedMW+ ...
     in.pInternalDemandMW-d.pInternalUnservedMW);

expectedBess=zeros(height(d),1);
expectedBess(1)=cfg.bess.standingRetentionPerStep* ...
    in.initial.bessEnergyMWh+ ...
    cfg.bess.etaCharge*d.pBessChargeMW(1)*dt- ...
    d.pBessDischargeMW(1)*dt/cfg.bess.etaDischarge;
for t=2:height(d)
    expectedBess(t)=cfg.bess.standingRetentionPerStep* ...
        d.bessEnergyMWh(t-1)+ ...
        cfg.bess.etaCharge*d.pBessChargeMW(t)*dt- ...
        d.pBessDischargeMW(t)*dt/cfg.bess.etaDischarge;
end
bessStateResidual=d.bessEnergyMWh-expectedBess;

expectedH2=zeros(height(d),1);
expectedH2(1)=cfg.hydrogen.storageRetentionPerStep* ...
    in.initial.h2InventoryKg+d.h2ProducedKg(1)- ...
    d.h2PipeWithdrawnKg(1)-d.h2ShipWithdrawnKg(1)- ...
    d.h2ToPowerConsumedKg(1);
for t=2:height(d)
    expectedH2(t)=cfg.hydrogen.storageRetentionPerStep* ...
        d.h2InventoryKg(t-1)+d.h2ProducedKg(t)- ...
        d.h2PipeWithdrawnKg(t)-d.h2ShipWithdrawnKg(t)- ...
        d.h2ToPowerConsumedKg(t);
end
h2StateResidual=d.h2InventoryKg-expectedH2;

cableResidual=d.pCableReceivedMW- ...
    (1-cfg.output.cableLossFraction)*d.pCableSendMW;
marineResidual=d.pMarineServedMW+d.pMarineUnservedMW- ...
    in.pMarineDemandMW;
computeBaseResidual=d.pComputeBaseServedMW+ ...
    d.pComputeBaseUnservedMW-in.pComputeBaseDemandMW;
sourceSplitResidual=in.pSourceAvailableMW-d.pSourceUsedMW- ...
    d.pCurtailmentMW;
expectedH2Production=(1000/cfg.hydrogen.secKWhPerKg)* ...
    (d.pElectrolyzerMW*dt- ...
     cfg.hydrogen.startEnergyMWhPerModule*d.nElectrolyzerStart);
h2ProductionResidual=d.h2ProducedKg-expectedH2Production;
expectedH2PowerConsumption=1000*d.pH2PowerMW*dt/ ...
    (cfg.h2Power.efficiencyLHV*cfg.h2Power.h2LHVKWhPerKg);
h2PowerResidual=d.h2ToPowerConsumedKg-expectedH2PowerConsumption;
elyDelta=[d.pElectrolyzerMW(1)-in.initial.electrolyzerPowerMW; ...
    diff(d.pElectrolyzerMW)];
computeDelta=[d.pComputeFacilityMW(1)-in.initial.computePowerMW; ...
    diff(d.pComputeFacilityMW)];
h2PowerDelta=[d.pH2PowerMW(1)-in.initial.h2PowerMW; ...
    diff(d.pH2PowerMW)];
elyOnlineDelta=[d.nElectrolyzerOnline(1)- ...
    in.initial.electrolyzerOnlineModules; ...
    diff(d.nElectrolyzerOnline)];

capacityViolation=[ ...
    d.pSourceUsedMW-in.pSourceAvailableMW; ...
    d.pBessChargeMW-cfg.bess.chargeMaxMW*in.availability.bess; ...
    (d.pBessDischargeMW-d.pBessChargeMW)+ ...
        cfg.bess.gfmReservePowerMW*in.gfmRequired- ...
        cfg.bess.dischargeMaxMW*in.availability.bess; ...
    -(d.pBessDischargeMW-d.pBessChargeMW)+ ...
        cfg.bess.gfmAbsorptionReservePowerMW*in.gfmRequired- ...
        cfg.bess.chargeMaxMW*in.availability.bess; ...
    cfg.bess.socMin*cfg.bess.energyMWh+ ...
        cfg.bess.gfmReserveEnergyMWh*in.gfmRequired- ...
        d.bessEnergyMWh; ...
    d.bessEnergyMWh-cfg.bess.socMax*cfg.bess.energyMWh+ ...
        cfg.bess.gfmAbsorptionReserveEnergyMWh*in.gfmRequired; ...
    cfg.hydrogen.moduleMinMW*d.nElectrolyzerOnline- ...
        d.pElectrolyzerMW; ...
    d.pElectrolyzerMW- ...
        cfg.hydrogen.moduleRatedMW*d.nElectrolyzerOnline; ...
    d.pElectrolyzerMW- ...
        cfg.hydrogen.electrolyzerRatedMW* ...
        in.availability.electrolyzer; ...
    d.h2InventoryKg- ...
        cfg.hydrogen.storageMaxKg*in.availability.h2Storage; ...
    d.h2PipeWithdrawnKg- ...
        in.h2PipeLimitKgPerH.*in.availability.h2Pipe*dt; ...
    d.h2ShipWithdrawnKg- ...
        in.h2ShipLimitKgPerH.*in.availability.h2Ship*dt; ...
    d.pH2PowerMW-cfg.h2Power.ratedMW*in.availability.h2Power; ...
    d.pComputeFlexibleMW-in.pComputeFlexibleMaxMW; ...
    cfg.compute.moduleFacilityMinMW*d.nComputeOnline- ...
        d.pComputeFacilityMW; ...
    d.pComputeFacilityMW- ...
        cfg.compute.moduleFacilityMaxMW*d.nComputeOnline; ...
    d.pComputeFacilityMW- ...
        cfg.compute.facilityMaxMW*in.availability.compute; ...
    d.pMarineServedMW-in.pMarineDemandMW; ...
    d.pInternalUnservedMW-in.pInternalDemandMW; ...
    d.pCableSendMW-in.cableSendLimitMW.*in.availability.cable; ...
    d.pCableReceivedMW-in.gridAcceptLimitMW.*in.availability.cable];

bessTerminalViolation=terminal_violation(cfg.bess.terminalRule, ...
    d.bessEnergyMWh(end),in.initial.bessEnergyMWh, ...
    cfg.bess.terminalTargetSOC*cfg.bess.energyMWh);
h2TerminalViolation=terminal_violation(cfg.hydrogen.terminalRule, ...
    d.h2InventoryKg(end),in.initial.h2InventoryKg, ...
    cfg.hydrogen.terminalTargetKg);

audit=struct;
audit.maxAbsBusBalanceResidualMW=max(abs(busResidual));
audit.maxAbsBessStateResidualMWh=max(abs(bessStateResidual));
audit.maxAbsH2StateResidualKg=max(abs(h2StateResidual));
audit.maxAbsCableLossResidualMW=max(abs(cableResidual));
audit.maxAbsMarineLedgerResidualMW=max(abs(marineResidual));
audit.maxAbsComputeBaseLedgerResidualMW=max(abs(computeBaseResidual));
audit.maxAbsSourceSplitResidualMW=max(abs(sourceSplitResidual));
audit.maxAbsH2ProductionResidualKg=max(abs(h2ProductionResidual));
audit.maxAbsH2PowerConversionResidualKg=max(abs(h2PowerResidual));
audit.maxCapacityViolation=max([0;capacityViolation]);
audit.bessTerminalViolationMWh=bessTerminalViolation;
audit.h2TerminalViolationKg=h2TerminalViolation;
audit.maxRampViolationMW=max([0; ...
    elyDelta-cfg.hydrogen.rampUpMWPerH*dt; ...
    -elyDelta-cfg.hydrogen.rampDownMWPerH*dt; ...
    computeDelta-cfg.compute.rampUpMWPerH*dt; ...
    -computeDelta-cfg.compute.rampDownMWPerH*dt; ...
    h2PowerDelta-cfg.h2Power.rampUpMWPerH*dt; ...
    -h2PowerDelta-cfg.h2Power.rampDownMWPerH*dt]);
audit.maxElectrolyzerStartLogicViolation=max(abs( ...
    d.nElectrolyzerStart-max(0,elyOnlineDelta)));
audit.maxH2MinimumDeliveryViolationKg=max([0; ...
    in.h2PipeMinimumKgPerH*dt-d.h2PipeWithdrawnKg; ...
    in.h2ShipMinimumKgPerH*dt-d.h2ShipWithdrawnKg]);
audit.minimumGfmUpwardPowerHeadroomMW=min( ...
    cfg.bess.dischargeMaxMW*in.availability.bess- ...
    (d.pBessDischargeMW-d.pBessChargeMW)- ...
    cfg.bess.gfmReservePowerMW*in.gfmRequired);
audit.minimumGfmDownwardPowerHeadroomMW=min( ...
    cfg.bess.chargeMaxMW*in.availability.bess+ ...
    (d.pBessDischargeMW-d.pBessChargeMW)- ...
    cfg.bess.gfmAbsorptionReservePowerMW*in.gfmRequired);
audit.minimumGfmUpwardEnergyHeadroomMWh=min(d.bessEnergyMWh- ...
    cfg.bess.socMin*cfg.bess.energyMWh- ...
    cfg.bess.gfmReserveEnergyMWh*in.gfmRequired);
audit.minimumGfmDownwardEnergyHeadroomMWh=min( ...
    cfg.bess.socMax*cfg.bess.energyMWh-d.bessEnergyMWh- ...
    cfg.bess.gfmAbsorptionReserveEnergyMWh*in.gfmRequired);
% Backward-compatible names retain the upward reserve meaning.
audit.minimumGfmPowerHeadroomMW= ...
    audit.minimumGfmUpwardPowerHeadroomMW;
audit.minimumGfmEnergyHeadroomMWh= ...
    audit.minimumGfmUpwardEnergyHeadroomMWh;
audit.minimumVariableValue=min(table2array(d(:, ...
    setdiff(d.Properties.VariableNames,{'timeH'}))),[],'all');
audit.simultaneousBessChargeDischargeCount=nnz( ...
    d.pBessChargeMW>tolMW & d.pBessDischargeMW>tolMW);
audit.simultaneousElectrolysisH2PowerCount=nnz( ...
    d.pElectrolyzerMW>tolMW & d.pH2PowerMW>tolMW);
criticalUnservedMW=d.pInternalUnservedMW+d.pMarineUnservedMW+ ...
    d.pComputeBaseUnservedMW;
audit.simultaneousCurtailmentCriticalENSCount=nnz( ...
    d.pCurtailmentMW>tolMW & criticalUnservedMW>tolMW);
audit.maximumCurtailmentCriticalENSProductMW2=max( ...
    d.pCurtailmentMW.*criticalUnservedMW);
[audit.productMixMaxShareViolation, ...
    audit.productMixMinimumEnergyViolationMWh]= ...
    product_mix_violation(in,result.kpi);
if isfinite(cfg.objective.maxENSMWh)
    audit.ensEpsilonViolationMWh=max( ...
        0,result.kpi.ensMWh-cfg.objective.maxENSMWh);
else
    audit.ensEpsilonViolationMWh=0;
end
if result.kpi.eAvailableMWh<=tolState
    if cfg.objective.minRenewableUtilization<=0
        audit.renewableUtilizationEpsilonViolation=0;
        audit.renewableUtilizationConstraintStatus= ...
            'NOT_APPLICABLE_NO_AVAILABLE_RENEWABLE';
    else
        audit.renewableUtilizationEpsilonViolation=Inf;
        audit.renewableUtilizationConstraintStatus= ...
            'INFEASIBLE_POSITIVE_MINIMUM_WITHOUT_AVAILABLE_RENEWABLE';
    end
else
    audit.renewableUtilizationEpsilonViolation=max(0, ...
        cfg.objective.minRenewableUtilization- ...
        result.kpi.renewableUtilization);
    audit.renewableUtilizationConstraintStatus='EVALUATED';
end
if isfinite(cfg.objective.maxNetGHGKgCO2e)
    audit.netGHGEpsilonViolationKgCO2e=max(0, ...
        result.kpi.netGHGKgCO2e-cfg.objective.maxNetGHGKgCO2e);
else
    audit.netGHGEpsilonViolationKgCO2e=0;
end
audit.pass = ...
    audit.maxAbsBusBalanceResidualMW<=tolMW && ...
    audit.maxAbsBessStateResidualMWh<=tolState && ...
    audit.maxAbsH2StateResidualKg<=tolState && ...
    audit.maxAbsCableLossResidualMW<=tolMW && ...
    audit.maxAbsMarineLedgerResidualMW<=tolMW && ...
    audit.maxAbsComputeBaseLedgerResidualMW<=tolMW && ...
    audit.maxAbsSourceSplitResidualMW<=tolMW && ...
    audit.maxAbsH2ProductionResidualKg<=tolState && ...
    audit.maxAbsH2PowerConversionResidualKg<=tolState && ...
    audit.maxCapacityViolation<=tolState && ...
    audit.bessTerminalViolationMWh<=tolState && ...
    audit.h2TerminalViolationKg<=tolState && ...
    audit.maxRampViolationMW<=tolState && ...
    audit.maxElectrolyzerStartLogicViolation<=tolState && ...
    audit.maxH2MinimumDeliveryViolationKg<=tolState && ...
    audit.minimumGfmUpwardPowerHeadroomMW>=-tolState && ...
    audit.minimumGfmDownwardPowerHeadroomMW>=-tolState && ...
    audit.minimumGfmUpwardEnergyHeadroomMWh>=-tolState && ...
    audit.minimumGfmDownwardEnergyHeadroomMWh>=-tolState && ...
    audit.minimumVariableValue>=-tolState && ...
    audit.simultaneousBessChargeDischargeCount==0 && ...
    audit.simultaneousElectrolysisH2PowerCount==0 && ...
    audit.simultaneousCurtailmentCriticalENSCount==0 && ...
    audit.productMixMaxShareViolation<=tolState && ...
    audit.productMixMinimumEnergyViolationMWh<=tolState && ...
    audit.ensEpsilonViolationMWh<=tolState && ...
    audit.renewableUtilizationEpsilonViolation<=1e-8 && ...
    audit.netGHGEpsilonViolationKgCO2e<=1e-3;
audit.scopeNotice = ...
    ['PASS means algebraic hourly feasibility only; it is not proof of ', ...
     'voltage, frequency, current-limit, fault ride-through, black-start, ', ...
     'weather survivability or corrosion-life compliance.'];
audit.dynamicGfmValidationStatus='NOT_RUN_REQUIRES_DYNAMIC_GATE';
end

function [shareViolation,minimumViolation]=product_mix_violation(in,kpi)
if ~in.productMix.enabled
    shareViolation=0;
    minimumViolation=0;
    return
end
minimumViolation=max(0,in.productMix.minimumAllocatedInputMWh- ...
    kpi.eAllocatedProductInputMWh);
if kpi.eAllocatedProductInputMWh<=1e-9
    shareViolation=1;
    return
end
target=[ ...
    in.productMix.targetElectricityShare, ...
    in.productMix.targetHydrogenShare, ...
    in.productMix.targetComputeShare];
actual=[ ...
    kpi.realizedElectricityInputShare, ...
    kpi.realizedHydrogenInputShare, ...
    kpi.realizedComputeInputShare];
lower=max(0,target-in.productMix.shareTolerance);
upper=min(1,target+in.productMix.shareTolerance);
zeroTarget=target<=1e-12;
lower(zeroTarget)=0;
upper(zeroTarget)=0;
shareViolation=max([0,lower-actual,actual-upper],[],'all');
end

function violation=terminal_violation(rule,xFinal,xInitial,xTarget)
switch lower(rule)
    case 'cyclic'
        violation=abs(xFinal-xInitial);
    case 'target'
        violation=max(0,xTarget-xFinal);
    case 'none'
        violation=0;
    otherwise
        violation=Inf;
end
end
