function paths = c5_add_v5_model_paths()
%C5_ADD_V5_MODEL_PATHS Resolve the sibling C4/V5 model by relative path.
%
% C5 owns scenarios, test runners, test data and result management. V5
% owns only the joint-model implementation. No absolute machine path and
% no current-working-directory assumption is used here.

thisDir=fileparts(mfilename('fullpath'));
c5Root=canonical_path(fullfile(thisDir,'..','..'));
hubRoot=canonical_path(fullfile(c5Root,'..'));
v5Candidates={ ...
    fullfile(hubRoot,'C4调度模型与分析','V5模型'), ...
    fullfile(hubRoot,'V5模型')};
v5Root="";
for k=1:numel(v5Candidates)
    candidate=canonical_path(v5Candidates{k});
    if isfile(fullfile(candidate,'run_v5_model.m'))
        v5Root=string(candidate);
        break
    end
end
v5Root=char(v5Root);

required={ ...
    fullfile(v5Root,'run_v5_model.m'), ...
    fullfile(v5Root,'config','v5_default_config.m'), ...
    fullfile(v5Root,'model','v5_build_problem.m'), ...
    fullfile(v5Root,'source','v5_source_adapter.m')};
assert(strlength(string(v5Root))>0 && all(cellfun(@isfile,required)), ...
    ['C5 cannot find the sibling C4/V5 joint-model implementation. ', ...
    'Expected relative path: ../C4调度模型与分析/V5模型']);

addpath(v5Root,fullfile(v5Root,'config'), ...
    fullfile(v5Root,'model'),fullfile(v5Root,'source'));

paths=struct( ...
    'c5Root',c5Root, ...
    'hubRoot',hubRoot, ...
    'v5Root',v5Root, ...
    'scenarioCodeDir',thisDir, ...
    'annualDataDir',fullfile( ...
        c5Root,'5.1场景设计','data','annual_2025'), ...
    'computeInputDir',fullfile( ...
        c5Root,'5.1场景设计','data','compute_inputs'), ...
    'baselineCodeDir',fullfile( ...
        c5Root,'5.2三大基准方案','code'), ...
    'comparisonCodeDir',fullfile( ...
        c5Root,'5.3对比方案与模型最优策略','code'), ...
    'annualRollingCodeDir',fullfile( ...
        c5Root,'5.7混合最优策略短测试与年度运营分析','code'));
end

function pathOut=canonical_path(pathIn)
pathOut=char(java.io.File(pathIn).getCanonicalPath());
end
