function scenario = c5_build_annual_2025_multisource_scenario()
%C5_BUILD_ANNUAL_2025_MULTISOURCE_SCENARIO Annual E/PV/tidal event case.
%
% The legacy annual builder is reused only for the workload, sea-
% temperature and price records. Source availability is rebuilt with all
% three project source types and is calculated by the V5 4.3 device models.
%
% Evidence boundary:
%   NASA POWER WS50M, ALLSKY_SFC_SW_DWN and T2M are public hourly data.
%   NASA 50 m wind is used directly because no supported site-specific
%   50-to-155 m shear model is supplied. GHI is used as a diffuse proxy
%   because no supported DNI/DHI decomposition is supplied.
%   [需查证文献支撑]
%   Tidal speed, wave height, event dates and event derates are
%   [假设值，待企业调研校准].

paths=c5_add_v5_model_paths();
legacy=c5_build_annual_2025_scenario();
scenario=legacy;
cfg=legacy.config;
cfg.meta.parameterVersion='v5_annual_2025_multisource_extreme_proxy_v2';
% Restore the project multi-cluster compute boundary. The legacy annual
% workload represents one 8.20 MW facility. Its flexible-task power shape
% is capacity-scaled to the 120 MW fleet while the original base demand is
% retained as the essential committed cluster. [假设值，待企业调研校准]
legacyComputeCapacityMW=legacy.config.compute.facilityMaxMW;
cfg.compute.facilityMaxMW=120;
cfg.compute.moduleCount=16;
cfg.compute.rampUpMWPerH=120;
cfg.compute.rampDownMWPerH=120;

nasaFile=fullfile(paths.annualDataDir, ...
    'nasa_power_hourly_2025_multisource.csv');
assert(isfile(nasaFile),'Missing NASA POWER annual multi-source file.');
nasa=readtable(nasaFile,'Delimiter',',','NumHeaderLines',11, ...
    'VariableNamingRule','preserve');
assert(height(nasa)==8760,'NASA POWER file must contain 8760 rows.');
wind50=double(nasa.('WS50M'));
ghiHourly=double(nasa.('ALLSKY_SFC_SW_DWN'));
airTemperature=double(nasa.('T2M'));
assert(all(isfinite([wind50,ghiHourly,airTemperature]),'all') && ...
    all(wind50>=0) && all(ghiHourly>=0), ...
    'NASA POWER file contains invalid or missing values.');

timeUTC=legacy.hourly.timeUTC;
assert(numel(timeUTC)==8760,'Legacy annual time axis must have 8760 rows.');
eventCode=repmat("NORMAL",8760,1);
warning=timeUTC>=datetime(2025,9,15,0,0,0,'TimeZone','UTC') & ...
    timeUTC<datetime(2025,9,15,12,0,0,'TimeZone','UTC');
passage=timeUTC>=datetime(2025,9,15,12,0,0,'TimeZone','UTC') & ...
    timeUTC<datetime(2025,9,16,12,0,0,'TimeZone','UTC');
recovery=timeUTC>=datetime(2025,9,16,12,0,0,'TimeZone','UTC') & ...
    timeUTC<datetime(2025,9,17,12,0,0,'TimeZone','UTC');
eventCode(warning)="TYPHOON_WARNING";
eventCode(passage)="TYPHOON_PASSAGE";
eventCode(recovery)="TYPHOON_RECOVERY";

waveHourly=1.5*ones(8760,1);
waveHourly(warning)=3.5;
waveHourly(passage)=7.0;
waveHourly(recovery)=3.0;
sourceOnline=~passage;

hours=8760;
t=(0:hours)'*3600;
N=numel(t);
wave=[waveHourly;waveHourly(end)];
online=[sourceOnline;sourceOnline(end)];

% One equivalent wind sub-farm; generation is calculated from hourly wind,
% not fixed ex ante. The power curve is inherited from the existing 4.3
% mechanism model and scaled to the configured 680 MW wind nameplate.
windScale=cfg.source.windInstalledMW/17;
windIn=struct('t',t,'windSpeed',[wind50;wind50(end)], ...
    'surgeVelocity',zeros(N,1),'pitchRate',zeros(N,1), ...
    'platformPitch',zeros(N,1),'waveHeight',wave, ...
    'availabilityState',online,'derate',ones(N,1), ...
    'powerReference',inf(N,1), ...
    'farmPowerReference',cfg.source.windInstalledMW*1e6*ones(N,1));
windP=struct('ratedPower',cfg.source.windInstalledMW*1e6, ...
    'ratedApparentPower',18.5e6*windScale,'hubHeight',155, ...
    'powerCurveWind',[0 3 5 7 9 11 13 24.99 25 60]', ...
    'powerCurveP',[0 0 0.8 3.8 9.5 15.0 17 17 0 0]'*1e6*windScale, ...
    'cutOutWind',25,'restartWind',20,'maxOperatingWave',6, ...
    'restartWave',4,'maxOperatingPitch',deg2rad(8), ...
    'restartPitch',deg2rad(4),'restartDelay',30*60, ...
    'rampUp',(0.5e6/60)*windScale, ...
    'auxiliaryPower',0.06e6*windScale, ...
    'auxiliaryPowerStandby',0.015e6*windScale, ...
    'arrayLossFraction',0.02);

% Horizontal FPV proxy. Wh/m2 in an hourly NASA record equals its hourly
% average W/m2 numerically. DNI=0 and DHI=GHI is an explicit proxy.
localHour=mod((0:hours)'+8,24);
daylight=localHour>=6 & localHour<=18;
elevation=-0.08*ones(N,1);
elevation(daylight)=(pi/2)*sin(pi*(localHour(daylight)-6)/12);
azimuth=pi/2+pi*(localHour-6)/12;
sunVector=[cos(elevation).*sin(azimuth), ...
    cos(elevation).*cos(azimuth),sin(elevation)];
ghi=[ghiHourly;ghiHourly(end)];
pvIn=struct('t',t,'dni',zeros(N,1),'dhi',ghi,'ghi',ghi, ...
    'sunVector',sunVector, ...
    'ambientTemp',[airTemperature;airTemperature(end)], ...
    'windSpeed',[wind50;wind50(end)],'waveHeight',wave, ...
    'availabilityState',online, ...
    'powerReference',cfg.source.pvInstalledMW*1e6*ones(N,1));
pvP=struct('baseNormal',[0 0 1],'pdcRated',96e6, ...
    'pacRated',cfg.source.pvInstalledMW*1e6, ...
    'apparentPowerRated',88e6,'gstc',1000,'tstc',25, ...
    'gammaP',-0.0035,'U0',25,'U1',6.84,'albedo',0.06, ...
    'bifaciality',0,'iamB0',0.05, ...
    'invLoadFraction',[0 0.05 0.10 0.20 0.50 1.00 1.30]', ...
    'invEfficiency',[0 0.90 0.95 0.97 0.985 0.985 0.98]', ...
    'auxiliaryPower',0.16e6,'auxiliaryPowerStandby',0.04e6, ...
    'cableLossFraction',0.015,'maxOperatingWind',30, ...
    'maxOperatingWave',4,'restartWind',20,'restartWave',2.5, ...
    'restartDelay',30*60,'rampUp',6e6/60);

% Repeated internal current-speed proxy pending public/site u-v current.
validation48=c5_build_all_channel_48h_scenario();
tidalBase=validation48.hourly.tidalSpeedMS;
tidalHourly=tidalBase(mod((0:hours-1)',numel(tidalBase))+1);
tidalVelocity=[tidalHourly;tidalHourly(end)];
nTidal=40;
tidalIn=struct('time',t, ...
    'axialVelocity',tidalVelocity+linspace(-0.04,0.04,nTidal), ...
    'platformAxialVelocity',0, ...
    'wakeVelocityFactor',linspace(1.00,0.94,nTidal), ...
    'availabilityState',repmat(online,1,nTidal), ...
    'derateFactor',ones(N,nTidal),'biofoulingFactor',ones(N,nTidal), ...
    'significantWaveHeight',wave, ...
    'farmPowerReference',cfg.source.tidalInstalledMW*1e6*ones(N,1));
tidalP=struct('ratedPower',1e6*ones(1,nTidal), ...
    'ratedApparentPower',1.1e6*ones(1,nTidal), ...
    'floodCurveSpeed',[0 0.7 1.0 1.3 1.6 1.9 2.2 2.5 3.0 3.5]', ...
    'floodCurvePowerPu',[0 0 0.04 0.14 0.31 0.55 0.80 1 1 0]', ...
    'ebbCurveSpeed',[0 0.7 1.0 1.3 1.6 1.9 2.2 2.5 3.0 3.5]', ...
    'ebbCurvePowerPu',[0 0 0.035 0.13 0.29 0.52 0.78 0.98 1 0]', ...
    'cutInSpeed',0.7,'directionDeadband',0.15, ...
    'reorientationDelay',10*60,'maxOperatingSpeed',3.5, ...
    'restartSpeed',3.1,'maxOperatingWave',4.5,'restartWave',3.8, ...
    'restartDelay',20*60,'rampUpRate',1e6/(10*60), ...
    'auxiliaryPowerRun',12e3,'auxiliaryPowerStandby',3e3, ...
    'collectionLossFraction',0.025);

sourceCase=struct('mode','device_inputs','hours',hours, ...
    'startTimeH',0, ...
    'parameterSetId','ANNUAL_2025_MULTISOURCE_EXTREME_PROXY_V2');
sourceCase.wind=struct('sourceId','NASA_WS50M_WIND_680MW_PROXY', ...
    'input',windIn,'parameters',windP);
sourceCase.pv=struct('sourceId','NASA_GHI_FPV_80MW_PROXY', ...
    'input',pvIn,'parameters',pvP);
sourceCase.tidal=struct('sourceId','TIDAL_40MW_INTERNAL_PROXY', ...
    'input',tidalIn,'parameters',tidalP);

in=legacy.input;
in.sourceCase=sourceCase;
computeScale=cfg.compute.facilityMaxMW/legacyComputeCapacityMW;
in.pComputeFlexibleMaxMW=min( ...
    cfg.compute.facilityMaxMW-in.pComputeBaseDemandMW, ...
    legacy.input.pComputeFlexibleMaxMW*computeScale);
in.pComputeFlexibleMaxMW(warning|passage|recovery)=0;
in.pComputeBaseDemandMW(passage)=0;
channelAvailability=ones(hours,1);
channelAvailability(passage)=0;
channelAvailability(recovery)=0.5;
shipAvailability=ones(hours,1);
shipAvailability(warning|passage)=0;
shipAvailability(recovery)=0.5;
in.availability=struct('bess',ones(hours,1), ...
    'electrolyzer',channelAvailability,'h2Storage',ones(hours,1), ...
    'compute',double(~passage),'cable',channelAvailability, ...
    'h2Pipe',channelAvailability,'h2Ship',shipAvailability, ...
    'h2Power',zeros(hours,1));
in.gfmRequired=ones(hours,1);

scenario.input=in;
scenario.config=cfg;
scenario.meta.scenarioId='V5_ANNUAL_2025_MULTISOURCE_EXTREME_PROXY_V2';
scenario.meta.operatingState='NORMAL_PLUS_ASSUMED_TYPHOON_DRILL';
scenario.meta.parameterStatus='[假设值，待企业调研校准]';
scenario.hourly.eventCode=eventCode;
scenario.hourly.nasaWind50mMS=wind50;
scenario.hourly.nasaGhiWhPerM2=ghiHourly;
scenario.hourly.nasaAirTemperatureC=airTemperature;
scenario.hourly.tidalSpeedProxyMS=tidalHourly;
scenario.hourly.waveHeightAssumptionM=waveHourly;
scenario.evidence.nasaFile=nasaFile;
scenario.evidence.nasaSourceType= ...
    'NASA_POWER_PUBLIC_DATA; NOT_PROJECT_MEASUREMENT';
scenario.evidence.windHeightBoundary= ...
    'NASA_50M_DIRECT_TO_155M_CURVE; [需查证文献支撑]';
scenario.evidence.pvBoundary= ...
    'NASA_GHI_AS_DHI_PROXY; [需查证文献支撑]';
scenario.evidence.tidalBoundary= ...
    'REPEATED_INTERNAL_48H_SPEED; [假设值，待企业调研校准]';
scenario.evidence.extremeEventBoundary= ...
    ['ASSUMED_TYPHOON_DATES_WAVE_AND_DERATES; ', ...
     'NOT_A_HISTORICAL_EVENT_CLAIM'];
scenario.evidence.computeScalingBoundary= ...
    ['ONE_8P2MW_CLUSTER_FLEX_SHAPE_SCALED_TO_120MW_FLEET; ', ...
     'BASE_CLUSTER_RETAINED; [假设值，待企业调研校准]'];
end
