function paths = v5_add_foundation_paths(v5Root)
%V5_ADD_FOUNDATION_PATHS Add authoritative copied V4 support paths.
%
% The unique 4.3 physical implementation is under foundation. Its paths
% are added by v5_source_adapter only when a sourceCase is executed,
% preventing global path pollution and duplicate function resolution.

if nargin<1 || isempty(v5Root)
    v5Root=fileparts(fileparts(mfilename('fullpath')));
end
foundation=fullfile(v5Root,'foundation');
assert(isfolder(foundation), ...
    'Missing V5 foundation. Run tools/sync_v4_foundation.ps1 first.');

interfaceCandidates=dir(fullfile(foundation,'library','4.2*'));
interfaceCandidates=interfaceCandidates([interfaceCandidates.isdir]);
assert(isscalar(interfaceCandidates), ...
    'Expected one copied 4.2 interface directory in V5 foundation.');
interfacePath=fullfile(interfaceCandidates(1).folder, ...
    interfaceCandidates(1).name);

matlabPaths={ ...
    interfacePath, ...
    fullfile(foundation,'integration','common'), ...
    fullfile(foundation,'modules','4.4_bus','integration'), ...
    fullfile(foundation,'modules','4.5_storage_hydrogen','model'), ...
    fullfile(foundation,'modules','4.5_storage_hydrogen','integration'), ...
    fullfile(foundation,'modules','4.8_objectives','model')};
for k=1:numel(matlabPaths)
    assert(isfolder(matlabPaths{k}), ...
        'Missing V5 foundation path: %s',matlabPaths{k});
    addpath(matlabPaths{k});
end

paths=struct( ...
    'root',foundation, ...
    'interface',interfacePath, ...
    'sourceModule',fullfile(foundation,'modules','4.3_source'), ...
    'busModule',fullfile(foundation,'modules','4.4_bus'), ...
    'storageHydrogenModule', ...
        fullfile(foundation,'modules','4.5_storage_hydrogen'), ...
    'computeModule',fullfile(foundation,'modules','4.6_compute'), ...
    'outputModule',fullfile(foundation,'modules','4.7_outputs'), ...
    'objectiveModule',fullfile(foundation,'modules','4.8_objectives'), ...
    'executableSourceModule', ...
        fullfile(foundation,'modules','4.3_source'));
end
