function check = v5_crosscheck_with_foundation_bus(cfg,in,result)
%V5_CROSSCHECK_WITH_FOUNDATION_BUS Recompute V5 balance with copied V4 4.4.
%
% V4 Schema V2 has no hydrogen-to-power injection and its fixed internal
% load ledger assumes zero internal ENS. Those cases are reported as not
% applicable rather than silently changing the frozen equation.

d=result.dispatch;
tol=1e-7;
check=struct( ...
    'status','NOT_RUN', ...
    'applicable',false, ...
    'pass',false, ...
    'maxAbsResidualMW',NaN, ...
    'sourceFunction','foundation/modules/4.4_bus/integration/v4_bus_ledger.m');
if any(d.pH2PowerMW>tol)
    check.status='NOT_APPLICABLE_V2_HAS_NO_H2_POWER_INJECTION';
    return
end
if any(d.pInternalUnservedMW>tol)
    check.status='NOT_APPLICABLE_V2_FIXED_INTERNAL_LOAD_ASSUMES_ZERO_ENS';
    return
end

v2cfg=common_config_4_2('interface_smoke');
v2cfg.source.windCapacityMW=cfg.source.windInstalledMW;
v2cfg.source.pvCapacityMW=cfg.source.pvInstalledMW;
v2cfg.source.tidalCapacityMW=cfg.source.tidalInstalledMW;
v2cfg.source.totalCapacityMW=cfg.source.installedMW;
v2cfg.commonBus.commonAuxMW=0;
v2cfg.commonBus.postPOILossMW=0;
validate_common_schema_4_2(v2cfg,true);

timeH=in.timeH;
N=numel(timeH);
z=zeros(N,1);
pSource=nonnegative_for_crosscheck(in.pSourceAvailableMW,tol, ...
    'pSourceAvailableMW');
pInternalDemand=nonnegative_for_crosscheck(in.pInternalDemandMW,tol, ...
    'pInternalDemandMW');
pBessCharge=nonnegative_for_crosscheck(d.pBessChargeMW,tol, ...
    'pBessChargeMW');
pBessDischarge=nonnegative_for_crosscheck(d.pBessDischargeMW,tol, ...
    'pBessDischargeMW');
pElectrolyzer=nonnegative_for_crosscheck(d.pElectrolyzerMW,tol, ...
    'pElectrolyzerMW');
pCompute=nonnegative_for_crosscheck(d.pComputeFacilityMW,tol, ...
    'pComputeFacilityMW');
pCableSend=nonnegative_for_crosscheck(d.pCableSendMW,tol, ...
    'pCableSendMW');
pMarineServed=nonnegative_for_crosscheck(d.pMarineServedMW,tol, ...
    'pMarineServedMW');
pCurtailment=nonnegative_for_crosscheck(d.pCurtailmentMW,tol, ...
    'pCurtailmentMW');
pInternalUnserved=nonnegative_for_crosscheck( ...
    d.pInternalUnservedMW,tol,'pInternalUnservedMW');
p43=common_packet_4_2('4.3',timeH,v2cfg,'RESPONSE');
p43.ports.source=v4_fill_port(timeH,v2cfg.meter.sourcePOI, ...
    pSource,pSource,pSource,z,pSource, ...
    "V5_CROSSCHECK","AVAILABLE");
p43.loss=struct( ...
    'pCollectionLossMW',z, ...
    'pSourceAuxLoadMW',pInternalDemand, ...
    'collectionLossAlreadyDeducted',true);

p45=common_packet_4_2('4.5',timeH,v2cfg,'RESPONSE');
p45.ports.bessCharge=v4_fill_port(timeH,v2cfg.meter.commonBus, ...
    pBessCharge,pBessCharge,pBessCharge,z, ...
    cfg.bess.chargeMaxMW*ones(N,1),"V5_CROSSCHECK","AVAILABLE");
p45.ports.bessDischarge=v4_fill_port(timeH,v2cfg.meter.commonBus, ...
    pBessDischarge,pBessDischarge,pBessDischarge,z, ...
    cfg.bess.dischargeMaxMW*ones(N,1),"V5_CROSSCHECK","AVAILABLE");
p45.ports.electrolyzer=v4_fill_port(timeH,v2cfg.meter.electrolyzer, ...
    pElectrolyzer,pElectrolyzer,pElectrolyzer,z, ...
    cfg.hydrogen.electrolyzerRatedMW*ones(N,1), ...
    "V5_CROSSCHECK","AVAILABLE");

p46=common_packet_4_2('4.6',timeH,v2cfg,'RESPONSE');
p46.ports.dcFacility=v4_fill_port(timeH,v2cfg.meter.dcFacility, ...
    pCompute,pCompute,pCompute,z, ...
    cfg.compute.facilityMaxMW*ones(N,1),"V5_CROSSCHECK","AVAILABLE");

p47=common_packet_4_2('4.7',timeH,v2cfg,'RESPONSE');
p47.ports.exportSend=v4_fill_port(timeH,v2cfg.meter.cableSend, ...
    pCableSend,pCableSend,pCableSend,z, ...
    in.cableSendLimitMW,"V5_CROSSCHECK","AVAILABLE");
p47.ports.marine=v4_fill_port(timeH,v2cfg.meter.commonBus, ...
    pMarineServed,pMarineServed,pMarineServed,z, ...
    in.pMarineDemandMW,"V5_CROSSCHECK","AVAILABLE");
p47.ports.gridImport=v4_fill_port(timeH,v2cfg.meter.cableSend, ...
    z,z,z,z,z,"V5_CROSSCHECK","STOPPED");

packet=v4_bus_ledger(v2cfg,timeH,p43,p45,p46,p47, ...
    pCurtailment,pInternalUnserved);
check.status='COMPLETED';
check.applicable=true;
check.maxAbsResidualMW=max(abs(packet.state.pBusResidualMW));
check.pass=check.maxAbsResidualMW<= ...
    v2cfg.commonBus.balanceToleranceMW;
check.balanceStatus=packet.state.balanceStatus;
end

function x=nonnegative_for_crosscheck(x,tol,name)
x=double(x(:));
assert(all(isfinite(x)) && all(x>=-tol), ...
    '%s exceeds the V5-to-foundation crosscheck tolerance.',name);
x=max(x,0);
end
