function report=run_c5_sequential_hourly_tests()
%RUN_C5_SEQUENTIAL_HOURLY_TESTS Regression tests for causal reserve policy.

testRoot=fileparts(mfilename('fullpath'));
codeRoot=fileparts(testRoot);
c5Root=fileparts(fileparts(codeRoot));
addpath(codeRoot,fullfile(c5Root,'5.1场景设计','code'));
c5_add_v5_model_paths();

tests={@test_typhoon_warning_enforces_bess_reserve, ...
    @test_unachievable_reserve_target_is_flagged, ...
    @test_normal_state_floor_preserves_initial_bess, ...
    @test_surplus_redispatch_can_start_pem, ...
    @test_rolling_window_overcomes_pem_start_cost};
names=["typhoon warning reserve target", ...
    "unachievable reserve target fallback", ...
    "normal state floor", ...
    "surplus redispatch starts PEM", ...
    "rolling window starts PEM"];
passed=false(size(tests));
messages=strings(size(tests));
for k=1:numel(tests)
    try
        tests{k}();
        passed(k)=true;
        messages(k)="PASS";
    catch ME
        messages(k)=string(ME.identifier)+": "+string(ME.message);
    end
end
report=table(names',passed',messages', ...
    'VariableNames',{'Test','Passed','Message'});
disp(report);
assert(all(passed),'C5 sequential-hourly regression tests failed.');
end

function test_typhoon_warning_enforces_bess_reserve()
cfg=v5_default_config('mechanism_test');
base=base_case(cfg,1,200);
strategy=struct( ...
    'id','test_typhoon_reserve', ...
    'strategyClass','TEST', ...
    'eventReserveRule',true, ...
    'warningBessReserveTargetSOC',0.80, ...
    'warningH2ReserveTargetKg',0, ...
    'maxENSMWh',Inf);
[summary,ledger]=c5_run_sequential_hourly( ...
    base,cfg,strategy,"TYPHOON_WARNING",false);
assert(summary.allHoursOptimal, ...
    'Reserve-policy test must finish with a proven-optimal solution.');
assert(summary.runStatus=="PASS_STRICT" && summary.strictPass && ...
    ~summary.relaxedPass, ...
    'A reserve-policy solve without fallback must be marked PASS_STRICT.');
assert(summary.mainConclusionEligible && ...
    summary.mainConclusionStatus=="MAIN_CONCLUSION_ELIGIBLE", ...
    'Strict results must be eligible for the main conclusion.');
assert(ledger.reserveTargetEnforced && ...
    ~ledger.reserveTargetFallbackUsed, ...
    'Warning reserve target must be enforced without fallback.');
assert(ledger.runStatus=="PASS_STRICT" && ledger.strictPass && ...
    ~ledger.relaxedPass, ...
    'The hourly ledger must retain the strict-pass status.');
assert(ledger.bessSOC>=0.80-1e-8, ...
    'Warning dispatch must meet the configured BESS reserve target.');
end

function test_unachievable_reserve_target_is_flagged()
cfg=v5_default_config('mechanism_test');
base=base_case(cfg);
strategy=struct( ...
    'id','test_unachievable_typhoon_reserve', ...
    'strategyClass','TEST', ...
    'eventReserveRule',true, ...
    'warningBessReserveTargetSOC',0.50, ...
    'warningH2ReserveTargetKg',cfg.hydrogen.storageMaxKg, ...
    'maxENSMWh',Inf);
[summary,ledger]=c5_run_sequential_hourly( ...
    base,cfg,strategy,"TYPHOON_WARNING",false);
assert(summary.reserveTargetFallbackHours==1, ...
    'An unachievable reserve target must be reported as a fallback.');
assert(summary.runStatus=="PASS_RELAXED" && ~summary.strictPass && ...
    summary.relaxedPass, ...
    'A reserve fallback must be marked PASS_RELAXED, not PASS_STRICT.');
assert(~summary.mainConclusionEligible && ...
    summary.mainConclusionStatus=="EXCLUDED_RELAXED_FALLBACK", ...
    'Relaxed fallback results must be excluded from the main conclusion.');
assert(ledger.reserveTargetFallbackUsed && ...
    ledger.h2ReserveShortfallKg>0, ...
    'The ledger must retain the unmet hydrogen reserve.');
assert(ledger.runStatus=="PASS_RELAXED" && ~ledger.strictPass && ...
    ledger.relaxedPass, ...
    'The hourly ledger must retain the relaxed-pass status.');
assert(~ledger.mainConclusionEligible && ...
    ledger.mainConclusionStatus=="EXCLUDED_RELAXED_FALLBACK", ...
    'The hourly ledger must exclude relaxed fallback results.');
end

function test_normal_state_floor_preserves_initial_bess()
cfg=v5_default_config('mechanism_test');
base=base_case(cfg,(1:2)',[100;100]);
strategy=struct( ...
    'id','test_normal_state_floor', ...
    'strategyClass','TEST', ...
    'eventReserveRule',true, ...
    'normalStateFloorRule',true, ...
    'maxENSMWh',Inf);
[summary,ledger]=c5_run_sequential_hourly( ...
    base,cfg,strategy,["NORMAL";"NORMAL"],false);
assert(summary.runStatus=="PASS_STRICT", ...
    'Normal state-floor test must remain strict when no fallback occurs.');
assert(summary.normalStateFloorEnforcedHours==2, ...
    'Normal state floor must be enforced in every normal hour.');
assert(all(ledger.normalStateFloorEnforced), ...
    'Hourly ledger must report normal floor enforcement.');
assert(min(ledger.bessSOC)>=0.50-1e-8, ...
    'Normal state floor must preserve the initial BESS SOC reserve.');
assert(max(ledger.normalBessFloorShortfallMWh)<=1e-8, ...
    'Normal BESS floor shortfall must be zero.');
end

function test_surplus_redispatch_can_start_pem()
cfg=v5_default_config('mechanism_test');
base=base_case(cfg,1,500);
base.cableSendLimitMW=0;
base.gridAcceptLimitMW=0;
base.pMarineDemandMW=0;
base.pComputeFlexibleMaxMW=0;
base.availability.h2Pipe=0;
base.availability.h2Ship=0;
strategy=struct( ...
    'id','test_surplus_redispatch', ...
    'strategyClass','TEST', ...
    'productMixEnabled',true, ...
    'eShare',1,'hShare',0,'cShare',0, ...
    'shareTolerance',0, ...
    'eventReserveRule',false, ...
    'normalStateFloorRule',false, ...
    'surplusRedispatchEnabled',true, ...
    'objectivePrimary','economicNetCostCNY', ...
    'maxENSMWh',Inf);
[summary,ledger]=c5_run_sequential_hourly( ...
    base,cfg,strategy,"NORMAL",false);
assert(summary.auditPass && summary.allHoursOptimal, ...
    'Surplus redispatch test must remain auditable and optimal.');
assert(summary.surplusRedispatchHours==1 && ...
    summary.surplusRedispatchHydrogenMWh>0, ...
    'A realized surplus must trigger PEM redispatch.');
assert(ledger.surplusRedispatchUsed && ...
    ledger.eHydrogenInputMWh>0 && ...
    ledger.surplusRedispatchCurtailmentReductionMWh>0, ...
    'PEM redispatch must absorb surplus and reduce curtailment.');
assert(ledger.ensMWh<=1e-9, ...
    'Surplus redispatch must not create critical ENS.');
end

function test_rolling_window_overcomes_pem_start_cost()
cfg=v5_default_config('mechanism_test');
base=base_case(cfg,(1:6)',20*ones(6,1));
base.initial.bessEnergyMWh=cfg.bess.socMax*cfg.bess.energyMWh- ...
    cfg.bess.gfmAbsorptionReserveEnergyMWh;
base.cableSendLimitMW=0;
base.gridAcceptLimitMW=0;
base.pMarineDemandMW=0;
base.pComputeFlexibleMaxMW=0;
common=struct( ...
    'id','test_rolling_pem', ...
    'strategyClass','TEST', ...
    'productMixEnabled',false, ...
    'forecastMode','PREVIOUS_HOUR_PERSISTENCE', ...
    'initialPlanningCapacityFactor',20/cfg.source.installedMW, ...
    'plannedMinimumAllocationFactor',1, ...
    'plannedShareTolerance',0.05, ...
    'eventReserveRule',false, ...
    'normalStateFloorRule',false, ...
    'surplusRedispatchEnabled',false, ...
    'objectivePrimary','economicNetCostCNY', ...
    'maxENSMWh',Inf);
myopic=common;
myopic.id='test_myopic_pem';
myopic.planningWindowH=1;
[myopicSummary,~]=c5_run_sequential_hourly( ...
    base,cfg,myopic,repmat("NORMAL",6,1),false);

rolling=common;
rolling.planningWindowH=6;
[rollingSummary,rollingLedger]=c5_run_sequential_hourly( ...
    base,cfg,rolling,repmat("NORMAL",6,1),false);

assert(myopicSummary.eHydrogenInputMWh<=1e-8, ...
    'The one-hour economic plan should still avoid the PEM start cost.');
assert(rollingSummary.eHydrogenInputMWh>0 && ...
    rollingSummary.h2ProducedKg>0, ...
    'The 6 h rolling plan must start PEM and produce hydrogen.');
assert(rollingLedger.plannedWindowHydrogenMWh(1)>0 && ...
    rollingLedger.plannedMinimumAllocatedInputMW(1)>0 && ...
    rollingLedger.pElectrolyzerMW(1)>0, ...
    'The first rolling plan must commit and execute first-hour PEM power.');
end

function base=base_case(cfg,timeH,pSourceAvailableMW)
if nargin<2 || isempty(timeH), timeH=1; end
if nargin<3 || isempty(pSourceAvailableMW), pSourceAvailableMW=100; end
timeH=double(timeH(:));
pSourceAvailableMW=double(pSourceAvailableMW(:));
assert(numel(timeH)==numel(pSourceAvailableMW), ...
    'Test time and source vectors must align.');
base=struct( ...
    'timeH',timeH, ...
    'pSourceAvailableMW',pSourceAvailableMW, ...
    'availability',struct( ...
    'bess',1, ...
    'electrolyzer',1, ...
    'h2Storage',1, ...
    'compute',1, ...
    'cable',1, ...
    'h2Pipe',1, ...
    'h2Ship',1, ...
    'h2Power',0), ...
    'initial',struct( ...
    'bessEnergyMWh',0.50*cfg.bess.energyMWh, ...
    'h2InventoryKg',0, ...
    'electrolyzerOnlineModules',0, ...
    'electrolyzerPowerMW',0, ...
    'computePowerMW',0, ...
    'h2PowerMW',0));
end
