function p=v4_objective_parameters_4_8()
%V4_OBJECTIVE_PARAMETERS_4_8 Public-reference and uncalibrated coefficients.
p=struct;
p.economic=struct( ...
    'annualizedCapitalCNY',0, ...
    'sourceVariableOMCNYPerMWh',20, ...
    'bessDischargeDegradationCNYPerMWh',30, ...
    'hydrogenVariableCostCNYPerKg',3.5, ...
    'electrolyzerStartCostCNYPerStart',20000, ...
    'spillPenaltyCNYPerMWh',50, ...
    'unservedPenaltyCNYPerMWh',10000, ...
    'electricityRevenueCNYPerMWh',347, ...
    'hydrogenRevenueCNYPerKg',28.36, ...
    'computeRevenueCNYPerMWhCS',500, ... % uncalibrated fallback; integrated run uses 4.6 task-level revenue
    'marineServiceRevenueCNYPerMWh',300);
p.economic.sourceType={'wind','pv','tidal'};
p.economic.sourceVariableOMCNYPerMWhByType=[NaN NaN NaN];
p.environment=struct( ...
    'annualizedEmbodiedKgCO2e',0, ...
    'sourceKgCO2ePerMWh',15, ...
    'bessThroughputKgCO2ePerMWh',5, ...
    'gridImportKgCO2ePerMWh',500, ...
    'hydrogenDeliveryKgCO2ePerKg',1);
p.reliability=struct('criticalUnservedWeight',1,'marineUnservedWeight',1);
p.meta=struct('calibrationStatus','MIXED_PUBLIC_REFERENCE_AND_UNCALIBRATED', ...
    'notice','Public market references are scenario anchors, not project contract prices; remaining coefficients are [假设值，待企业调研校准].', ...
    'formulaStatus','[需查证文献支撑]', ...
    'electricityPriceSourceType','政府官网（国家能源局《2024年度中国电力市场发展报告》，广东日前均价）', ...
    'hydrogenPriceSourceType','数据网站（上海环境能源交易所绿色氢能价格指数）', ...
    'hydrogenPhysicalParameterSourceType','企业官方网站（Nel MC Series产品规格）', ...
    'sourceCostStatus','AGGREGATE_FALLBACK_UNTIL_COMPARABLE_SOURCE_COST_CASE');
end
