function out=run_v4_integration(options)
%RUN_V4_INTEGRATION Non-invasive Chapter 4.3--4.9 integration smoke test.
if nargin<1 || isempty(options), options=struct; end
here=fileparts(mfilename('fullpath'));
if isfield(options,'scenarioId'), scenarioId=string(options.scenarioId);
else, scenarioId="unified_24h_mixed"; end
addpath(fullfile(here,'library','4.2变量与接口'), ...
    fullfile(here,'integration','common'), ...
    fullfile(here,'modules','4.3_source','integration'), ...
    fullfile(here,'modules','4.4_bus','integration'), ...
    fullfile(here,'modules','4.5_storage_hydrogen','integration'), ...
    fullfile(here,'modules','4.5_storage_hydrogen','model'), ...
    fullfile(here,'modules','4.6_compute','integration'), ...
    fullfile(here,'modules','4.8_objectives','model'), ...
    fullfile(here,'modules','4.9_dispatch','model'));
if isfield(options,'cfg'), cfg=options.cfg; else, cfg=common_config_4_2('interface_smoke'); end
if isfield(options,'useUnifiedCapacity'), useUnifiedCapacity=logical(options.useUnifiedCapacity);
else, useUnifiedCapacity=true; end
if isfield(options,'outputMode'), outputMode=char(options.outputMode);
elseif isfield(cfg,'scenario') && isfield(cfg.scenario,'outputMode')
    outputMode=char(cfg.scenario.outputMode);
else, outputMode='M'; end
if useUnifiedCapacity
    cfg=v4_apply_unified_capacity_case_4_2(cfg,outputMode);
end
cfg=v4_apply_4_5_parameter_overlay(cfg);
validate_common_schema_4_2(cfg,true);
if isfield(options,'outputDir')
    outDir=char(options.outputDir);
    if ~isfolder(fileparts(outDir)) && isempty(fileparts(outDir))
        outDir=fullfile(here,outDir);
    elseif ~isfolder(outDir) && ~is_absolute_path(outDir)
        outDir=fullfile(here,outDir);
    end
else
    outDir=fullfile(here,'outputs');
end
if ~isfolder(outDir), mkdir(outDir); end

%% BOUNDARY: 4.3 source availability and 4.6 compute feasible range
if isfield(options,'sourcePacket')
    p43Boundary=options.sourcePacket;
    sourceRaw=[];
    validate_module_packet_4_2(p43Boundary,'4.3',cfg,true);
else
    [p43Boundary,sourceRaw]=v4_source_adapter(cfg,'BOUNDARY'); %#ok<NASGU>
end
timeH=p43Boundary.axis.timeH; N=numel(timeH);
p46Boundary=v4_compute_boundary_4_6(cfg,timeH);
if isfield(options,'state0')
    state0=options.state0;
else
    state0=struct( ...
        'bessEnergyMWh',cfg.bess.socInitial*cfg.bess.energyMWh, ...
        'h2InventoryKg',cfg.hydrogen.storageInitialKg, ...
        'electrolyzerOn',false, ...
        'electrolyzerPowerMW',0, ...
        'electrolyzerFLEH',0);
end
if isfield(options,'storageBoundaryOptions')
    storageBoundaryOptions=options.storageBoundaryOptions;
else
    storageBoundaryOptions=struct( ...
        'gfmReservePowerMW',cfg.bess.gfmReservePowerMW, ...
        'gfmReserveEnergyMWh',cfg.bess.gfmReserveEnergyMWh, ...
        'blackStartSOCMin',cfg.bess.blackStartSOCMin);
end
[p45Boundary,b45]=v4_storage_hydrogen_boundary_4_5( ...
    cfg,timeH,state0,storageBoundaryOptions); %#ok<NASGU>

%% 4.9 REQUEST: cross-module allocation before professional responses
if isfield(options,'dispatchOptions'), dispatchOptions=options.dispatchOptions;
else, dispatchOptions=struct; end
[p49,dispatch]=v4_dispatch_4_9( ...
    cfg,p43Boundary,p46Boundary,dispatchOptions,p45Boundary);

%% RESPONSE: 4.3 must-take source realization for the smoke case
p43=p43Boundary; p43.meta.phase='RESPONSE';
validate_module_packet_4_2(p43,'4.3',cfg,true);

%% RESPONSE: 4.6 existing DC-only model receives the hourly 4.9 request
computeCsv=fullfile(outDir,'v4_compute_response.csv');
computeRequestCsv=fullfile(outDir,'v4_compute_request.csv');
Tc=table(dispatch.computeRequestedMW,'VariableNames',{'compute_requested_mw'});
writetable(Tc,computeRequestCsv);
pyScript=fullfile(here,'modules','4.6_compute','integration','v4_compute_bridge.py');
dcRoot=fullfile(here,'modules','4.6_compute','DC_model_v2_1');
if isfield(options,'computeMode'), computeMode=char(options.computeMode); else, computeMode='sla'; end
assert(any(strcmp(computeMode,{'sla','power_following'})), ...
    'computeMode must be sla or power_following.');
computeUnitCount=1; computeUnitCapMW=cfg.compute.facilityMaxMW;
if isfield(cfg,'capacity') && isfield(cfg.capacity,'installed')
    computeUnitCount=cfg.capacity.installed.computeUnitCount;
    computeUnitCapMW=cfg.capacity.installed.computeUnitFacilityMaxMW;
end
cmd=sprintf(['python "%s" --module-root "%s" --output "%s" --request "%s" ' ...
    '--hours %d --mode %s --unit-count %d --unit-cap-mw %.12g'], ...
    pyScript,dcRoot,computeCsv,computeRequestCsv,N,computeMode, ...
    computeUnitCount,computeUnitCapMW);
computeEnabled=true;
if isfield(cfg,'assetEnabled') && isfield(cfg.assetEnabled,'subseaCompute')
    computeEnabled=logical(cfg.assetEnabled.subseaCompute);
end
if computeEnabled
    [status,msg]=system(cmd); assert(status==0,'4.6 bridge failed: %s',msg);
    C=readtable(computeCsv,'VariableNamingRule','preserve'); assert(height(C)==N);
else
    z=zeros(N,1);
    C=table(z,z,z,z,z,z,z,z,z,false(N,1), ...
        repmat(string(computeMode),N,1),ones(N,1),z,z,z,z, ...
        'VariableNames',{'dc_power_mw','it_power_mw','dc_aux_power_mw', ...
        'compute_served_mwh_cs','compute_queue_mwh_cs', ...
        'rigid_unserved_mwh_cs','flex_overdue_mwh_cs', ...
        'spot_dropped_mwh_cs','dc_online_min_mw','dc_online', ...
        'compute_model_mode','pue','compute_gross_revenue_yuan', ...
        'compute_sla_penalty_yuan','compute_variable_om_yuan', ...
        'compute_electricity_transfer_yuan'});
    writetable(C,computeCsv);
end
p46=common_packet_4_2('4.6',timeH,cfg,'RESPONSE');
p46.ports.dcFacility=v4_fill_port(timeH,cfg.meter.dcFacility,dispatch.computeRequestedMW, ...
    C.dc_power_mw,C.dc_power_mw,0,p46Boundary.ports.dcFacility.maxMW, ...
    "4.6_DC_ONLY","AVAILABLE");
p46.state.computeQueueMWhCS=C.compute_queue_mwh_cs;
p46.service.computeServedMWhCS=C.compute_served_mwh_cs;
p46.service.pITActualMW=C.it_power_mw;
p46.service.pDCAuxActualMW=C.dc_aux_power_mw;
p46.service.computeRigidUnservedMWhCS=C.rigid_unserved_mwh_cs;
p46.service.computeFlexOverdueMWhCS=C.flex_overdue_mwh_cs;
p46.service.computeSpotDroppedMWhCS=C.spot_dropped_mwh_cs;
p46.service.pDCOnlineMinMW=C.dc_online_min_mw;
p46.service.computeModelMode=string(C.compute_model_mode);
p46.service.computeGrossRevenueCNY=C.compute_gross_revenue_yuan;
p46.service.computeSLAPenaltyCNY=C.compute_sla_penalty_yuan;
p46.service.computeVariableOMCNY=C.compute_variable_om_yuan;
p46.service.computeElectricityTransferCNY=C.compute_electricity_transfer_yuan;
p46.audit.modelOrigin=dcRoot;
p46.audit.computeUnitCount=computeUnitCount;
p46.audit.computeUnitFacilityMaxMW=computeUnitCapMW;
p46.audit.aggregatePhysicalFacilityMaxMW=computeUnitCount*computeUnitCapMW;
p46.audit.assetEnabled=computeEnabled;
p46.audit.serviceNormalization='MWh-CS = GPUh * equivalent_gpu_it_power_kw / 1000; boundary identity, business calibration pending';
p46.audit.economicBoundary='4.6 electricity charge is an internal transfer/opportunity-cost reference; 4.8 does not add it to project cost';
validate_module_packet_4_2(p46,'4.6',cfg,true);

marineReq=dispatch.marineRequestedMW;
redispatch46=v4_redispatch_after_compute_4_9(cfg,dispatch,C.dc_power_mw);
req45=redispatch46.req45;
marineAvailable=redispatch46.marineAllocatedMW;
exportReq=redispatch46.exportRequestedMW;
responseOptions=struct('tolerance',1e-6,'enforceTerminal',true);
prov45=v4_storage_hydrogen_response( ...
    cfg,timeH,req45,state0,redispatch46.h2DeliveryPlanKg,responseOptions);

%% 4.7 existing channel functions; duplicated PUE/production/balance are bypassed
inputCsv=fullfile(outDir,'v4_output_request.csv'); outputCsv=fullfile(outDir,'v4_output_response.csv');
h2Req=redispatch46.h2DeliveryPlanKg;
T=table(exportReq,marineReq,marineAvailable,prov45.h2AvailableForDeliveryKg,h2Req, ...
    p46.service.computeServedMWhCS,repmat(cfg.compute.fiberServiceCapacityMWhCSPerH,N,1), ...
    'VariableNames',{'export_requested_mw','marine_requested_mw','marine_available_mw','h2_available_kg', ...
    'h2_requested_kg','compute_served_mwh_cs','compute_delivery_cap_mwh_cs'});
writetable(T,inputCsv);
pyScript=fullfile(here,'modules','4.7_outputs','integration','v4_output_bridge.py');
mod47=fullfile(here,'modules','4.7_outputs','delivery_model');
cmd=sprintf(['python "%s" --module-root "%s" --input "%s" --output "%s" ' ...
    '--cable-cap %.12g --grid-cap %.12g --cable-loss %.12g --pipe-cap %.12g ' ...
    '--ship-cap %.12g --pipe-loss %.12g --ship-loss %.12g --marine-base %.12g ' ...
    '--marine-desal %.12g --marine-equipment %.12g --marine-flex %.12g'],pyScript,mod47,inputCsv,outputCsv, ...
    cfg.output.cableSendCapacityMW,cfg.output.gridAcceptMaxMW,cfg.output.cableLossFraction, ...
    cfg.hydrogen.pipeCapacityKgPerH,cfg.hydrogen.shipCapacityKgPerH, ...
    cfg.hydrogen.pipeLossFraction,cfg.hydrogen.shipLossFraction, ...
    cfg.output.marineBaseLoadMW,cfg.output.marineDesalLoadMW, ...
    cfg.output.marineEquipmentLoadMW,cfg.output.marineFlexibleFraction);
[status,msg]=system(cmd); assert(status==0,'4.7 bridge failed: %s',msg);
O=readtable(outputCsv,'VariableNamingRule','preserve');
p47=common_packet_4_2('4.7',timeH,cfg,'RESPONSE');
p47.ports.exportSend=v4_fill_port(timeH,cfg.meter.cableSend,exportReq,O.export_actual_mw,O.export_actual_mw,0, ...
    min(cfg.output.cableSendCapacityMW,cfg.output.gridAcceptMaxMW),"4.7_CABLE","AVAILABLE");
p47.ports.gridImport=v4_fill_port(timeH,cfg.meter.cableSend,0,0,0,0,0,"IMPORT_DISABLED","DISABLED");
p47.ports.marine=v4_fill_port(timeH,cfg.meter.commonBus,marineReq,O.marine_actual_mw,O.marine_actual_mw,0, ...
    cfg.output.marineBaseLoadMW+cfg.output.marineDesalLoadMW+cfg.output.marineEquipmentLoadMW,"4.7_MARINE","AVAILABLE");
p47.product.h2DeliveredKg=O.h2_delivered_kg;
p47.product.h2PipeDeliveredKg=O.h2_pipe_delivered_kg;
p47.product.h2ShipDeliveredKg=O.h2_ship_delivered_kg;
p47.service.pCableReceiveMW=O.cable_receive_mw;
p47.service.cableLossMW=O.cable_loss_mw;
p47.service.computeDeliveredMWhCS=O.compute_delivered_mwh_cs;
p47.service.marineUnservedMW=O.marine_unserved_mw;
p47.service.marineBelowRigid=logical(O.marine_below_rigid);
p47.service.marineViolationCount=O.marine_violation_count;
p47.audit.h2WithdrawnKg=O.h2_withdrawn_kg;
p47.audit.h2PipeWithdrawnKg=O.h2_pipe_withdrawn_kg;
p47.audit.h2ShipWithdrawnKg=O.h2_ship_withdrawn_kg;
p47.audit.bypassedLegacyFunctions={'compute_load.py PUE','hydrogen_output.py production/inventory', ...
    'balance.py system balance','objectives.py cross-channel objective'};
validate_module_packet_4_2(p47,'4.7',cfg,true);

%% STATE_COMMIT-equivalent state fields and actual-only 4.4 LEDGER
% 4.9's withdrawal plan already respects the 4.5 inventory recurrence and
% 4.7 channel cap. A mismatch is an interface infeasibility requiring
% redispatch; it is not silently resolved by a second zero-withdrawal pass.
assert(max(abs(O.h2_withdrawn_kg-redispatch46.h2DeliveryPlanKg))<=1e-6, ...
    '4.7 actual H2 withdrawal differs from the 4.9/4.5 feasible plan.');
assert(max(abs(prov45.pElectrolyzerMW-req45.electrolyzerMW))<=1e-6, ...
    '4.5 clipped the post-compute electrolyzer redispatch.');
assert(max(abs(prov45.h2InventoryKg-dispatch.h2InventoryPlanKg))<=1e-6, ...
    'Same-hour flow-through redispatch changed the planned H2 inventory path.');
p45=v4_finalize_4_5_packet(cfg,timeH,req45,prov45,O.h2_withdrawn_kg);
assert(all(h2Req<=p45.product.h2AvailableForDeliveryKg+1e-9), ...
    '4.7 hydrogen request exceeds committed 4.5 availability sequence.');
actual49=v4_reconcile_actuals_4_9(cfg,p43,p45,p46,p47,dispatch);
p44=v4_bus_ledger(cfg,timeH,p43,p45,p46,p47,actual49.spillMW,actual49.criticalUnservedMW);

assert(max(abs(p44.state.pBusResidualMW))<=cfg.commonBus.balanceToleranceMW, ...
    'V4 bus residual exceeds frozen tolerance.');
assert(all(p45.state.bessSOC>=cfg.bess.socMin-1e-9 & p45.state.bessSOC<=cfg.bess.socMax+1e-9));
assert(all(p45.state.h2InventoryKg>=-1e-9 & p45.state.h2InventoryKg<=cfg.hydrogen.storageMaxKg+1e-9));
assert(all(p45.state.terminalConstraintOK), ...
    '4.5 committed terminal constraint is not satisfied.');

%% 4.8 EVALUATION: committed actual quantities only
p48=v4_evaluate_objectives_4_8(cfg,p43,p44,p45,p46,p47,p49,[]);
capacityAudit=v4_capacity_audit_4_8( ...
    cfg,p43,p45,p46,p47,p49,p48.service.lifecycleAssetTable);
p48.service.capacityAuditTable=capacityAudit;

out=struct('cfg',cfg,'packet4_3',p43,'packet4_4',p44,'packet4_5Boundary',p45Boundary, ...
    'packet4_5',p45, ...
    'packet4_6',p46,'packet4_7',p47,'packet4_8',p48,'packet4_9',p49, ...
    'dispatchActual',actual49,'redispatchAfterCompute',redispatch46, ...
    'capacityAudit',capacityAudit, ...
    'storageFinalState',prov45.finalState, ...
    'schedulerId',p49.audit.schedulerId, ...
    'assumptionNotice','[假设值，待企业调研校准]');
out.scenarioId=scenarioId;
save(fullfile(outDir,'v4_integration_result.mat'),'out');
S=table(timeH,p43.ports.source.actualMW,p45.ports.bessCharge.actualMW, ...
    p45.ports.bessDischarge.actualMW,p45.ports.electrolyzer.actualMW, ...
    p45.state.bessSOC,p45.state.bessEnergyMWh,p45.product.h2ProductionKg, ...
    p45.state.h2InventoryKg,p47.product.h2DeliveredKg, ...
    p46.ports.dcFacility.actualMW,p47.ports.marine.actualMW, ...
    p47.ports.exportSend.actualMW,actual49.spillMW,p47.service.marineUnservedMW, ...
    p44.state.pBusResidualMW, ...
    'VariableNames',{'timeH','sourceMW','bessChargeMW','bessDischargeMW', ...
    'electrolyzerMW','bessSOC','bessEnergyMWh','h2ProductionKg', ...
    'h2InventoryKg','h2DeliveredKg','dcFacilityMW','marineMW', ...
    'exportSendMW','spillMW','marineUnservedMW','busResidualMW'});
writetable(S,fullfile(outDir,'v4_hourly_summary.csv'));

% Unified detail output for full-horizon indicator plots. This table keeps
% request, response, state, product-delivery and redispatch series together;
% module-native CSV files remain available for interface auditing.
D=table(timeH,p43.ports.source.maxMW,p43.ports.source.actualMW, ...
    p43.loss.pSourceAuxLoadMW,p43.loss.pCollectionLossMW, ...
    p45.ports.bessCharge.requestedMW,p45.ports.bessCharge.actualMW, ...
    p45.ports.bessDischarge.requestedMW,p45.ports.bessDischarge.actualMW, ...
    p45.ports.electrolyzer.requestedMW,p45.ports.electrolyzer.actualMW, ...
    p45.state.bessSOC,p45.state.bessEnergyMWh, ...
    p45.product.h2ProductionKg,p45.state.h2InventoryKg, ...
    p45.product.h2StorageLossKg,p45.product.waterConsumptionM3, ...
    p45.service.electrolyzerOnlineModules, ...
    p45.service.electrolyzerStartEvent, ...
    dispatch.computeRequestedMW,p46.ports.dcFacility.actualMW, ...
    p46.service.pITActualMW,p46.service.pDCAuxActualMW,C.pue, ...
    p46.service.computeServedMWhCS,p46.state.computeQueueMWhCS, ...
    p46.service.computeRigidUnservedMWhCS, ...
    p46.service.computeFlexOverdueMWhCS, ...
    p46.service.computeSpotDroppedMWhCS, ...
    p46.service.computeGrossRevenueCNY,p46.service.computeSLAPenaltyCNY, ...
    marineReq,p47.ports.marine.actualMW,p47.service.marineUnservedMW, ...
    dispatch.exportRequestedMW,redispatch46.exportRequestedMW, ...
    p47.ports.exportSend.actualMW,p47.service.pCableReceiveMW, ...
    p47.service.cableLossMW,p45.product.h2WithdrawnKg, ...
    p47.product.h2DeliveredKg,p47.product.h2PipeDeliveredKg, ...
    p47.product.h2ShipDeliveredKg,redispatch46.computeReleasedMW, ...
    redispatch46.marineTopUpMW,redispatch46.exportTopUpMW, ...
    redispatch46.electrolyzerTopUpMW,actual49.spillMW, ...
    actual49.criticalUnservedMW,actual49.totalUnservedMW, ...
    p44.state.pBusResidualMW, ...
    'VariableNames',{'timeH','sourceAvailableMW','sourceActualMW', ...
    'sourceAuxMW','collectionLossMW','bessChargeRequestedMW', ...
    'bessChargeActualMW','bessDischargeRequestedMW', ...
    'bessDischargeActualMW','electrolyzerRequestedMW', ...
    'electrolyzerActualMW','bessSOC','bessEnergyMWh', ...
    'h2ProductionKg','h2InventoryKg','h2StorageLossKg', ...
    'waterConsumptionM3','electrolyzerOnlineModules', ...
    'electrolyzerStartEvent','computeRequestedMW','dcFacilityActualMW', ...
    'itPowerMW','dcAuxPowerMW','pue','computeServedMWhCS', ...
    'computeQueueMWhCS','computeRigidUnservedMWhCS', ...
    'computeFlexOverdueMWhCS','computeSpotDroppedMWhCS', ...
    'computeGrossRevenueCNY','computeSLAPenaltyCNY', ...
    'marineRequestedMW','marineActualMW','marineUnservedMW', ...
    'exportInitialRequestedMW','exportFinalRequestedMW','exportSendActualMW', ...
    'cableReceiveMW','cableLossMW','h2WithdrawnKg','h2DeliveredKg', ...
    'h2PipeDeliveredKg','h2ShipDeliveredKg','computeReleasedMW', ...
    'marineTopUpMW','exportTopUpMW','electrolyzerTopUpMW','spillMW', ...
    'criticalUnservedMW','totalUnservedMW','busResidualMW'});
sourceTypes=string(p43.service.sourceType);
for j=1:numel(sourceTypes)
    stem=matlab.lang.makeValidName(char(sourceTypes(j)));
    D.([stem 'AvailableMW'])=p43.service.availableBySourceMW(:,j);
    D.([stem 'ActualMW'])=p43.service.actualBySourceMW(:,j);
    D.([stem 'AuxMW'])=p43.service.auxiliaryBySourceMW(:,j);
    D.([stem 'CollectionLossMW'])=p43.service.collectionLossBySourceMW(:,j);
end
writetable(D,fullfile(outDir,'v4_hourly_detail.csv'));

J=table(p48.product.economicNetCostCNY,p48.product.lifecycleEmissionKgCO2e, ...
    p48.product.EENSMWh,string(p48.quality.calibrationVersion), ...
    string(p48.audit.normalizationStatus), ...
    'VariableNames',{'economicNetCostCNY','lifecycleEmissionKgCO2e','EENSMWh', ...
    'calibrationVersion','normalizationStatus'});
writetable(J,fullfile(outDir,'v4_objective_summary.csv'));

dt=cfg.time.dispatchStepH;
marineDemandMWh=sum(marineReq)*dt;
metricName=[ ...
    "sourceEnergyMWh";"bessChargeEnergyMWh";"bessDischargeEnergyMWh"; ...
    "bessInitialSOC";"bessFinalSOC";"electrolyzerEnergyMWh"; ...
    "h2ProducedKg";"h2DeliveredKg";"h2DeliveryRatio"; ...
    "computeFacilityEnergyMWh";"computeDeliveredMWhCS"; ...
    "computeGrossRevenueCNY";"computeSLAPenaltyCNY"; ...
    "marineDemandMWh";"marineServedMWh";"marineUnservedMWh"; ...
    "marineServiceRatio";"exportSendMWh";"electricityDeliveredMWh"; ...
    "cableDeliveryRatio";"spillEnergyMWh";"renewableUtilization"; ...
    "totalCostCNY";"totalRevenueCNY";"economicNetCostCNY"; ...
    "lifecycleEmissionKgCO2e";"EENSMWh";"maxAbsBusResidualMW"; ...
    "terminalBessSOC";"terminalH2InventoryKg"];
metricValue=[ ...
    p48.service.sourceEnergyMWh;sum(p45.ports.bessCharge.actualMW)*dt; ...
    sum(p45.ports.bessDischarge.actualMW)*dt;cfg.bess.socInitial; ...
    p45.state.bessSOC(end);p48.service.electrolyzerEnergyMWh; ...
    p48.service.h2ProducedKg;p48.service.h2DeliveredKg; ...
    safe_ratio(p48.service.h2DeliveredKg,p48.service.h2ProducedKg); ...
    sum(p46.ports.dcFacility.actualMW)*dt;p48.service.computeDeliveredMWhCS; ...
    p48.service.computeGrossRevenueCNY;p48.service.computeSLAPenaltyCNY; ...
    marineDemandMWh;p48.service.marineServedMWh; ...
    p48.service.marineUnservedMWh; ...
    safe_ratio(p48.service.marineServedMWh,marineDemandMWh); ...
    sum(p47.ports.exportSend.actualMW)*dt;p48.service.electricityDeliveredMWh; ...
    safe_ratio(p48.service.electricityDeliveredMWh, ...
        sum(p47.ports.exportSend.actualMW)*dt); ...
    p48.service.spillEnergyMWh;p48.service.renewableUtilization; ...
    p48.service.totalCostCNY;p48.service.totalRevenueCNY; ...
    p48.product.economicNetCostCNY;p48.product.lifecycleEmissionKgCO2e; ...
    p48.product.EENSMWh;max(abs(p44.state.pBusResidualMW)); ...
    p45.state.bessSOC(end);p45.state.h2InventoryKg(end)];
metricUnit=[ ...
    "MWh";"MWh";"MWh";"p.u.";"p.u.";"MWh";"kg";"kg";"fraction"; ...
    "MWh";"MWh-CS";"CNY";"CNY";"MWh";"MWh";"MWh";"fraction"; ...
    "MWh";"MWh";"fraction";"MWh";"fraction";"CNY";"CNY";"CNY"; ...
    "kgCO2e";"MWh";"MW";"p.u.";"kg"];
metricCategory=[ ...
    "energy";"storage";"storage";"storage";"storage";"hydrogen"; ...
    "hydrogen";"hydrogen";"hydrogen";"compute";"compute";"compute"; ...
    "compute";"marine";"marine";"marine";"marine";"electricity"; ...
    "electricity";"electricity";"reliability";"reliability"; ...
    "economic";"economic";"economic";"environment";"reliability"; ...
    "validation";"validation";"validation"];
lifecycle=p48.service.lifecycle;
lifecycleMetricName=[ ...
    "grossCapexCNY";"constructionFinancingCNY";"financedCapexCNY"; ...
    "annualDepreciationCNY";"annualFinancingCostCNY"; ...
    "annualFixedOMCNY";"replacementPresentValueCNY"; ...
    "annualReplacementReserveCNY";"lifecycleCostPresentValueCNY"; ...
    "lifecycleNPVAfterPenaltyCNY";"lifecycleNPVBeforePenaltyCNY"];
lifecycleMetricValue=[ ...
    lifecycle.grossCapexCNY;lifecycle.constructionFinancingCNY; ...
    lifecycle.financedCapexCNY;lifecycle.annualDepreciationCNY; ...
    lifecycle.annualFinancingCostCNY;lifecycle.annualFixedOMCNY; ...
    lifecycle.replacementPresentValueCNY; ...
    lifecycle.annualReplacementReserveCNY; ...
    lifecycle.lifecycleCostPresentValueCNY; ...
    lifecycle.lifecycleNPVAfterPenaltyCNY; ...
    lifecycle.lifecycleNPVBeforePenaltyCNY];
metricName=[metricName;lifecycleMetricName];
metricValue=[metricValue;lifecycleMetricValue];
metricUnit=[metricUnit;repmat("CNY",numel(lifecycleMetricName),1)];
metricCategory=[metricCategory;repmat("lifecycle_economic", ...
    numel(lifecycleMetricName),1)];
sourceEnergyByType=double(p48.service.sourceEnergyByTypeMWh(:));
if ~isempty(sourceEnergyByType)
    metricName=[metricName;sourceTypes(:)+"EnergyMWh"];
    metricValue=[metricValue;sourceEnergyByType];
    metricUnit=[metricUnit;repmat("MWh",numel(sourceTypes),1)];
    metricCategory=[metricCategory;repmat("source",numel(sourceTypes),1)];
end
scenarioColumn=repmat(scenarioId,numel(metricName),1);
dataStatus=repmat("[模型仿真结果]",numel(metricName),1);
calibrationStatus=repmat(string(p48.quality.calibrationVersion),numel(metricName),1);
K=table(scenarioColumn,metricCategory,metricName,metricValue,metricUnit, ...
    dataStatus,calibrationStatus, ...
    'VariableNames',{'scenarioId','category','indicator','value','unit', ...
    'dataSourceType','calibrationStatus'});
writetable(K,fullfile(outDir,'v4_kpi_summary.csv'));

costNames=string(p48.service.costComponentNames(:));
revenueNames=string(p48.service.revenueComponentNames(:));
economicCategory=[repmat("cost",numel(costNames),1); ...
    repmat("revenue",numel(revenueNames),1)];
economicItem=[costNames;revenueNames];
economicValue=[double(p48.service.costComponentsCNY(:)); ...
    double(p48.service.revenueComponentsCNY(:))];
E=table(repmat(scenarioId,numel(economicItem),1),economicCategory, ...
    economicItem,economicValue,repmat("CNY",numel(economicItem),1), ...
    repmat("[模型仿真结果；参数含假设值]",numel(economicItem),1), ...
    'VariableNames',{'scenarioId','category','item','value','unit','dataStatus'});
writetable(E,fullfile(outDir,'v4_economic_breakdown.csv'));
writetable(p48.service.lifecycleAssetTable, ...
    fullfile(outDir,'v4_lifecycle_asset_ledger.csv'));
writetable(capacityAudit,fullfile(outDir,'v4_capacity_audit.csv'));
lifecycleSummary=struct2table(p48.service.lifecycle,'AsArray',true);
writetable(lifecycleSummary,fullfile(outDir,'v4_lifecycle_summary.csv'));

emissionNames=string(p48.service.emissionComponentNames(:));
G=table(repmat(scenarioId,numel(emissionNames),1),emissionNames, ...
    double(p48.service.emissionComponentsKgCO2e(:)), ...
    repmat("kgCO2e",numel(emissionNames),1), ...
    repmat("[模型仿真结果；排放因子含假设值]",numel(emissionNames),1), ...
    'VariableNames',{'scenarioId','item','value','unit','dataStatus'});
writetable(G,fullfile(outDir,'v4_environment_breakdown.csv'));
fprintf('BLUE HUB CH4 V4 INTEGRATION: PASSED\n');
fprintf('Maximum bus residual: %.3e MW\n',max(abs(p44.state.pBusResidualMW)));
fprintf('4.8 objective vector [CNY, kgCO2e, MWh]: [%.6g, %.6g, %.6g]\n', ...
    p48.state.objectiveVectorRaw);
end

function tf=is_absolute_path(p)
p=char(p);
tf=~isempty(regexp(p,'^[A-Za-z]:[\\/]','once')) || startsWith(p,'\\');
end

function value=safe_ratio(numerator,denominator)
if denominator>0, value=numerator/denominator;
else, value=NaN; end
end
