import sys, os  
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))  
exec(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gen_clean.py'), encoding='utf-8').read())  
  
params = CommonCaseV1()  
r1 = run_simulation(params, 'base')  
r2 = run_simulation(params, 'peak')  
  
out_dir = r'C:\Users\86188\Documents\Codex\2026-07-20\ge\outputs\v3'  
os.makedirs(out_dir, exist_ok=True)  
  
def report_str(r1, r2):  
    P = chr(124); L = []; A = L.append  
    A('# Energy Island Power Balance Model - Detailed Report')  
    A('')  
    A('## 1 Parameters')  
    A('- Site: common_case_v1, Source: 34MW wind + 4MW PV + 2MW tidal')  
    A('- BESS: 20MW/80MWh, Electrolyzer: 10MW, DC: 15MW')  
    A('- Cable: 40MW, 50km, Marine: 2MW')  
    A('')  
    A('## 2 Sub-model Derivations') 
    A('')  
    A('### 2.1 Section 4.3 Multi-Source Supply')  
    A('')  
    A('Wind: P_w(v)=0 for v in [0,3)U(25,inf]')  
    A('      P_w(v)=P_rated*(v-3)3/93 for v in [3,12]')  
    A('      P_w(v)=P_rated for v in (12,25]')  
    A('PV: P_pv(G)=P_pv_rated*G/1000 k=-0.0035')  
    A('Tidal: P_t(v)=P_t_rated*min(1,(v/2.5)3)')  
    A('Collection: P_poi=P_gross*(1-0.02) P_net=P_poi*(1-0.015)')  
    A('')  
    A('### 2.2 Section 4.5 Battery-H2 Storage')  
    A('')  
    A('BESS: SOC(t+1)=SOC(t)+(P_ch*eta_ch-P_dis/eta_dis)/E_b')  
    A('H2: m_H2(t)=P_elec/SEC H2_stock(t+1)=H2_stock+m_H2-m_del')  
    A('')  
    A('### 2.3 Section 4.6 Green Computing')  
    A('')  
    A('P_IT=P_IT_rated*util P_cool=P_IT*(PUE-1) P_DC=min(P_fac,P_IT+P_cool)')  
    A('')  
    A('### 2.4 Section 4.7 Export and Marine')  
    A('')  
    A('P_loss_cable=P_send*(0.005+0.001*L) P_recv=P_send-P_loss')  
    A('P_marine=2MW (constant)')  
    A('')  
    A('### 2.5 Section 4.4 Common Bus Balance')  
    A('')  
    A('P_inject=P_src_net+P_grid+max(0,P_bess)')  
    A('P_consume=P_DC+P_export+P_marine+P_spill+abs(min(0,P_bess))')  
    A('P_loss=(P_inject+P_consume)*0.015 Residual=P_inject-P_consume-P_loss')  
    A('')  
    A('## 3 Simulation Results')  
    A('')  
    A('### 3.1 Base Scenario (Normal)')  
    A('- Wind speed: 8 m/s, Irradiance: 600 W/m2, Tidal: 2.0 m/s')  
    A('- Source gross: {:.3f} MW, POI: {:.3f} MW, Net: {:.3f} MW'.format(r1['source']['gross'], r1['source']['poi'], r1['source']['net']))  
    A('- DC load: {:.3f} MW, Export: {:.3f} MW, Marine: {:.3f} MW'.format(r1['dc'], r1['export']['send'], r1['marine']))  
    A('- Balance: Inject={:.3f} MW, Consume={:.3f} MW, Residual={:.4f} MW, Status={}'.format(r1['balance']['inject'], r1['balance']['consume'], r1['balance']['residual'], r1['balance']['status'])) 
    A('')  
    A('### 3.2 Peak Scenario (Low RE, High Load)')  
    A('- Wind speed: 4 m/s, Irradiance: 200 W/m2, Tidal: 1.0 m/s')  
    A('- Source gross: {:.3f} MW, POI: {:.3f} MW, Net: {:.3f} MW'.format(r2['source']['gross'], r2['source']['poi'], r2['source']['net']))  
    A('- Balance: Inject={:.3f} MW, Consume={:.3f} MW, Residual={:.4f} MW, Status={}'.format(r2['balance']['inject'], r2['balance']['consume'], r2['balance']['residual'], r2['balance']['status']))  
    A('')  
    A('## 4 Code Architecture')  
    A('')  
    A('- SourceModel_4_3: Wind turbine + PV + tidal with physics models')  
    A('- BessH2Model_4_5: BESS SOC dynamics + electrolyzer + H2 storage')  
    A('- ComputingModel_4_6: IT load + cooling (PUE-based)')  
    A('- ExportMarineModel_4_7: Subsea cable loss + marine load')  
    A('- CommonBusBalance_4_4: MP-04 power conservation equation')  
    A('- run_simulation: Scenario-based simulation orchestration')  
    A('')  
    A('---')  
    A('*Case: common_case_v1 ' + chr(124) + ' Generated: 2026-07-20*')  
    return chr(10).join(L)  
  
report = report_str(r1, r2)  
rp = os.path.join(out_dir, 'island_report.md')  
with open(rp, 'w', encoding='utf-8') as f: f.write(report)  
  
mp = os.path.join(out_dir, 'model_v2.py')  
with open(mp, 'w', encoding='utf-8') as f:  
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gen_clean.py'), encoding='utf-8') as sf:  
        f.write(sf.read())  
  
print(f'Report: {rp}')  
print(f'Model: {mp}')  
print()  
print(report) 
