function [s,T]=v4_lifecycle_economics_4_8(cfg,p,periodOperatingCostCNY, ...
    periodRevenueCNY,periodPenaltyCostCNY,horizonH)
%V4_LIFECYCLE_ECONOMICS_4_8 Capital recovery and discounted lifecycle ledger.
% Public values are market proxies, not supplier quotations. The short
% dispatch horizon is repeated to create an annual equivalent; this is a
% scenario comparison convention, not a bankable forecast.
l=p.lifecycle;
life=l.analysisLifeYear;
if isfield(cfg,'economics') && isfield(cfg.economics,'analysisLifeYear') && ...
        isfinite(cfg.economics.analysisLifeYear)
    life=cfg.economics.analysisLifeYear;
end
r=l.discountRate;
if isfield(cfg,'economics') && isfield(cfg.economics,'discountRate') && ...
        isfinite(cfg.economics.discountRate)
    r=cfg.economics.discountRate;
end
assert(life>0 && r>=0 && horizonH>0,'Invalid lifecycle horizon or discount rate.');
constructionYear=0;
if isfield(cfg,'economics') && isfield(cfg.economics,'constructionPeriodYear') && ...
        isfinite(cfg.economics.constructionPeriodYear)
    constructionYear=cfg.economics.constructionPeriodYear;
end
crf=capital_recovery_factor(r,life);
annuity=(1-(1+r)^(-life))/r;
if r==0, annuity=life; end

windKW=cfg.source.windCapacityMW*1e3;
pvW=cfg.source.pvCapacityMW*1e6;
tidalKW=cfg.source.tidalCapacityMW*1e3;
bessKWh=cfg.bess.energyMWh*1e3;
bessKW=cfg.bess.powerMW*1e3;
electrolyzerKW=cfg.hydrogen.electrolyzerRatedMW*1e3;
computeW=cfg.compute.itCapacityMW*1e6;
distanceKm=cfg.output.cableDistanceKm;

assetName=["floatingWind";"marineFloatingPV";"tidalStream";"BESS"; ...
    "PEMElectrolyzer";"hydrogenStorage";"subseaCompute"; ...
    "powerExportCable";"fiberCable"];
capexCNY=[ ...
    windKW*l.windCapexCNYPerKW; ...
    pvW*l.pvCapexUSDPerW*l.usdToCNY; ...
    tidalKW*l.tidalCapexUSDPerKW*l.usdToCNY; ...
    (bessKWh*l.bessEnergyCapexUSDPerKWh+ ...
        bessKW*l.bessPowerCapexUSDPerKW)*l.usdToCNY; ...
    electrolyzerKW*l.electrolyzerCapexUSDPerKW*l.usdToCNY; ...
    cfg.hydrogen.storageMaxKg*l.hydrogenStorageCapexUSDPerKg*l.usdToCNY; ...
    computeW*l.computeCapexUSDPerWIT*l.usdToCNY; ...
    distanceKm*l.powerCableCapexEURPerKm*l.eurToCNY; ...
    distanceKm*l.fiberCableCapexEURPerKm*l.eurToCNY];
fixedOMAnnualCNY=[ ...
    windKW*l.windFixedOMUSDPerKWYear*l.usdToCNY; ...
    pvW/1e3*l.pvFixedOMUSDPerKWYear*l.usdToCNY; ...
    capexCNY(3)*l.tidalFixedOMFraction; ...
    capexCNY(4)*l.bessFixedOMFraction; ...
    capexCNY(5)*l.electrolyzerFixedOMFraction; ...
    capexCNY(6)*l.hydrogenStorageFixedOMFraction; ...
    capexCNY(7)*l.computeFixedOMFraction; ...
    capexCNY(8)*l.powerCableFixedOMFraction; ...
    capexCNY(9)*l.fiberCableFixedOMFraction];
depreciationLifeYear=[25;25;20;15;20;25;25;40;25];
dataStatus=[ ...
    "政府官网公开目标代理"; ...
    "国际合作组织数据库中位值代理"; ...
    "[假设值，待企业调研校准]"; ...
    "美国国家实验室公开成本代理"; ...
    "美国国家实验室公开制造价格代理"; ...
    "美国国家实验室陆上储氢代理"; ...
    "企业官网2 MW液冷数据中心代理"; ...
    "欧盟政府研究机构平均安装成本代理"; ...
    "欧盟政府研究机构平均安装成本代理"];
sourceCategory=[ ...
    "政府官网＋美国国家实验室官方报告"; ...
    "国际合作组织技术报告＋美国国家实验室官方基准"; ...
    "欧盟政府报告＋假设值"; ...
    "美国国家实验室官方技术报告"; ...
    "美国国家实验室官方技术报告"; ...
    "美国能源部/国家实验室官方技术报告"; ...
    "企业官方网站技术白皮书"; ...
    "欧盟政府研究机构官网"; ...
    "欧盟政府研究机构官网"];
sourceUrl=[ ...
    "https://www.nea.gov.cn/20260522/7cf96e984e124058922e2513523e8581/c.html ; https://www.nrel.gov/docs/fy25osti/91775.pdf"; ...
    "https://iea-pvps.org/key-topics/t13-floating-pv-plants-review-2025/ ; https://atb.nrel.gov/electricity/2024/utility-scale_pv"; ...
    "https://op.europa.eu/webpub/mare/eu-blue-economy-report-2025/blue-economic-sectors/marine-renewable-energy.html"; ...
    "https://www.nrel.gov/docs/fy24osti/87646.pdf"; ...
    "https://www.nrel.gov/docs/fy24osti/87625.pdf"; ...
    "https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/progress19/ins_sa173_hunter_2019.pdf"; ...
    "https://blog.se.com/datacenter/architecture/2020/02/24/liquid-vs-air-cooling-which-is-the-capex-winner/"; ...
    "https://joint-research-centre.ec.europa.eu/jrc-explains/subsea-cables-how-vulnerable-are-they-and-can-we-protect-them_en"; ...
    "https://joint-research-centre.ec.europa.eu/jrc-explains/subsea-cables-how-vulnerable-are-they-and-can-we-protect-them_en"];

replacementPVCNY=zeros(size(capexCNY));
replacementSchedule=strings(size(capexCNY));
replacementPVCNY(3)=discounted_events(0.25*capexCNY(3),[10 20],r);
replacementSchedule(3)="Y10/Y20: 25% major overhaul [假设值]";
bessReplacementCNY=(bessKWh*l.bessReplacementEnergyUSDPerKWh+ ...
    bessKW*l.bessReplacementPowerUSDPerKW)*l.usdToCNY;
replacementPVCNY(4)=discounted_events(bessReplacementCNY,[10 20],r);
replacementSchedule(4)="Y10/Y20: NREL replacement-cost proxy";
replacementPVCNY(5)=discounted_events( ...
    l.electrolyzerStackReplacementFraction*capexCNY(5),[10 20],r);
replacementSchedule(5)="Y10/Y20: 40% stack [假设值]";
replacementPVCNY(7)=discounted_events( ...
    l.computeITReplacementFraction*capexCNY(7),[5 10 15 20],r);
replacementSchedule(7)="Y5/Y10/Y15/Y20: 50% IT [假设值]";
replacementPVCNY(9)=discounted_events(0.30*capexCNY(9),12,r);
replacementSchedule(9)="Y12: 30% [假设值]";
replacementSchedule(replacementSchedule=="")="none within analysis life";

constructionFinancingCNY=capexCNY*construction_financing_fraction(r,constructionYear);
financedCapexCNY=capexCNY+constructionFinancingCNY;
annualDepreciationCNY=financedCapexCNY./depreciationLifeYear;
annualInitialCapitalRecoveryCNY=financedCapexCNY*crf;
annualFinancingCNY=annualInitialCapitalRecoveryCNY-annualDepreciationCNY;
assert(all(annualFinancingCNY>=-1e-8), ...
    'Depreciation life creates a negative financing split.');
annualFinancingCNY=max(0,annualFinancingCNY);
annualReplacementRecoveryCNY=replacementPVCNY*crf;

T=table(assetName,capexCNY,constructionFinancingCNY,financedCapexCNY, ...
    fixedOMAnnualCNY,depreciationLifeYear, ...
    annualDepreciationCNY,annualFinancingCNY,replacementPVCNY, ...
    annualReplacementRecoveryCNY,replacementSchedule,sourceCategory, ...
    sourceUrl,dataStatus);

periodFraction=horizonH/l.hoursPerYear;
annualRevenueCNY=periodRevenueCNY/periodFraction;
annualOperatingCostCNY=periodOperatingCostCNY/periodFraction;
annualPenaltyCostCNY=periodPenaltyCostCNY/periodFraction;
s=struct;
s.analysisLifeYear=life;
s.discountRate=r;
s.capitalRecoveryFactor=crf;
s.periodAnnualizationFactor=1/periodFraction;
s.grossCapexCNY=sum(capexCNY);
s.constructionPeriodYear=constructionYear;
s.constructionFinancingCNY=sum(constructionFinancingCNY);
s.financedCapexCNY=sum(financedCapexCNY);
s.annualDepreciationCNY=sum(annualDepreciationCNY);
s.annualFinancingCostCNY=sum(annualFinancingCNY);
s.annualFixedOMCNY=sum(fixedOMAnnualCNY);
s.replacementPresentValueCNY=sum(replacementPVCNY);
s.annualReplacementReserveCNY=sum(annualReplacementRecoveryCNY);
s.periodDepreciationCNY=s.annualDepreciationCNY*periodFraction;
s.periodFinancingCostCNY=s.annualFinancingCostCNY*periodFraction;
s.periodFixedOMCNY=s.annualFixedOMCNY*periodFraction;
s.periodReplacementReserveCNY=s.annualReplacementReserveCNY*periodFraction;
s.annualEquivalentRevenueCNY=annualRevenueCNY;
s.annualEquivalentOperatingCostCNY=annualOperatingCostCNY;
s.annualEquivalentPenaltyCostCNY=annualPenaltyCostCNY;
s.revenuePresentValueCNY=annualRevenueCNY*annuity;
s.operatingCostPresentValueCNY=annualOperatingCostCNY*annuity;
s.fixedOMPresentValueCNY=s.annualFixedOMCNY*annuity;
s.lifecycleCostPresentValueCNY=s.financedCapexCNY+s.replacementPresentValueCNY+ ...
    s.operatingCostPresentValueCNY+s.fixedOMPresentValueCNY;
s.lifecycleNPVAfterPenaltyCNY=s.revenuePresentValueCNY- ...
    s.lifecycleCostPresentValueCNY;
s.lifecycleNPVBeforePenaltyCNY=s.lifecycleNPVAfterPenaltyCNY+ ...
    annualPenaltyCostCNY*annuity;
s.equivalentAnnualNetAfterPenaltyCNY=annualRevenueCNY- ...
    annualOperatingCostCNY-s.annualFixedOMCNY- ...
    sum(annualInitialCapitalRecoveryCNY)-s.annualReplacementReserveCNY;
s.annualizationStatus='REPRESENTATIVE_PERIOD_REPEATED_ASSUMPTION';
s.taxStatus='EXCLUDED_TAX_BASIS_UNDECIDED';
s.decommissioningStatus='EXCLUDED_NO_VERIFIED_PROJECT_QUOTE';
s.priceBasisStatus='MIXED_PUBLIC_PRICE_YEARS_FX_CONVERSION_ONLY_NO_CPI_ESCALATION';
s.sourceNotice=l.meta.boundaryNotice;
end

function value=capital_recovery_factor(r,n)
if r==0, value=1/n; else, value=r*(1+r)^n/((1+r)^n-1); end
end

function value=discounted_events(eventCost,years,r)
value=sum(eventCost./((1+r).^years));
end

function value=construction_financing_fraction(r,n)
if n<=0 || r==0, value=0; return; end
midpoints=(0.5:1:(n-0.5));
value=mean((1+r).^(n-midpoints)-1);
end
