function p=v4_objective_parameters_4_8()
%V4_OBJECTIVE_PARAMETERS_4_8 Public-reference and uncalibrated coefficients.
p=struct;
p.economic=struct( ...
    'sourceVariableOMCNYPerMWh',20, ...
    'bessDischargeDegradationCNYPerMWh',30, ...
    'bessOpeningInventoryCNYPerMWh',347, ... % [假设值，待企业调研校准]
    'hydrogenVariableCostCNYPerKg',3.5, ...
    'hydrogenOpeningInventoryCNYPerKg',23.2, ... % [假设值，待企业调研校准]
    'hydrogenPipeTransportCNYPerKg',1.5, ... % [假设值，待企业调研校准]
    'hydrogenShipTransportCNYPerKg',3.0, ... % [假设值，待企业调研校准]
    'electrolyzerStartCostCNYPerStart',20000, ...
    'spillPenaltyCNYPerMWh',50, ...
    'unservedPenaltyCNYPerMWh',10000, ...
    'electricityRevenueCNYPerMWh',347, ...
    'hydrogenRevenueCNYPerKg',28.36, ...
    'computeRevenueCNYPerMWhCS',500, ... % uncalibrated fallback; integrated run uses 4.6 task-level revenue
    'marineServiceRevenueCNYPerMWh',300);
p.economic.sourceType={'wind','pv','tidal'};
p.economic.sourceVariableOMCNYPerMWhByType=[NaN NaN NaN];
p.lifecycle=struct( ...
    'analysisLifeYear',25, ...
    'discountRate',0.08, ... % project scenario assumption; overridden by cfg when available
    'hoursPerYear',8760, ...
    'usdToCNY',6.7933, ...
    'eurToCNY',7.7345, ...
    'fxEvidenceDate','2026-07-22', ...
    'windCapexCNYPerKW',20000, ...
    'windFixedOMUSDPerKWYear',108, ...
    'pvCapexUSDPerW',1.18, ...
    'pvFixedOMUSDPerKWYear',22, ...
    'tidalCapexUSDPerKW',8000, ... % [假设值，待企业调研校准]
    'tidalFixedOMFraction',0.03, ... % [假设值，待企业调研校准]
    'bessEnergyCapexUSDPerKWh',275, ...
    'bessPowerCapexUSDPerKW',289, ...
    'bessReplacementEnergyUSDPerKWh',203, ...
    'bessReplacementPowerUSDPerKW',282, ...
    'bessFixedOMFraction',0.025, ...
    'electrolyzerCapexUSDPerKW',1055, ...
    'electrolyzerFixedOMFraction',0.03, ... % [假设值，待企业调研校准]
    'electrolyzerStackReplacementFraction',0.40, ... % [假设值，待企业调研校准]
    'hydrogenStorageCapexUSDPerKg',1168, ...
    'hydrogenStorageFixedOMFraction',0.01, ...
    'computeCapexUSDPerWIT',6.02, ...
    'computeFixedOMFraction',0.04, ... % [假设值，待企业调研校准]
    'computeITReplacementFraction',0.50, ... % [假设值，待企业调研校准]
    'powerCableCapexEURPerKm',1.5e6, ...
    'powerCableFixedOMFraction',0.01, ... % [假设值，待企业调研校准]
    'fiberCableCapexEURPerKm',35000, ...
    'fiberCableFixedOMFraction',0.03); % [假设值，待企业调研校准]
p.lifecycle.meta=struct( ...
    'currencySourceType','政府官网（国家外汇管理局人民币汇率中间价）', ...
    'windSourceType','政府官网（国家能源局20 MW漂浮式风电示范目标）', ...
    'pvSourceType','国际合作组织技术报告（IEA-PVPS/SERIS FPV数据库中位数）', ...
    'batterySourceType','美国国家实验室官方技术报告（NREL/TP-7A40-87646）', ...
    'electrolyzerSourceType','美国国家实验室官方技术报告（NREL/TP-6A20-87625）', ...
    'hydrogenStorageSourceType','美国国家实验室/美国能源部官方技术报告（陆上储氢代理）', ...
    'computeSourceType','企业官方网站技术白皮书（Schneider Electric液冷数据中心代理）', ...
    'cableSourceType','欧盟政府研究机构官网（JRC海底电力/通信电缆平均安装成本）', ...
    'methodSourceType','美国国家实验室官方技术基准（NREL ATB）', ...
    'boundaryNotice',[ ...
    'Public values are non-binding market proxies. Tidal CAPEX, several fixed-O&M ', ...
    'rates and replacement fractions are [假设值，待企业调研校准]. Shared offshore ', ...
    'platform, converter station, insurance, tax and decommissioning are excluded.']);
p.environment=struct( ...
    'annualizedEmbodiedKgCO2e',0, ...
    'sourceKgCO2ePerMWh',15, ...
    'bessThroughputKgCO2ePerMWh',5, ...
    'gridImportKgCO2ePerMWh',500, ...
    'hydrogenDeliveryKgCO2ePerKg',1);
p.reliability=struct('criticalUnservedWeight',1,'marineUnservedWeight',1);
p.meta=struct('calibrationStatus','MIXED_PUBLIC_REFERENCE_AND_UNCALIBRATED', ...
    'notice','Public market references are scenario anchors, not project contract prices; remaining coefficients are [假设值，待企业调研校准].', ...
    'formulaStatus','[需查证文献支撑]', ...
    'electricityPriceSourceType','政府官网（国家能源局《2024年度中国电力市场发展报告》，广东日前均价）', ...
    'hydrogenPriceSourceType','数据网站（上海环境能源交易所绿色氢能价格指数）', ...
    'hydrogenPhysicalParameterSourceType','企业官方网站（Nel MC Series产品规格）', ...
    'sourceCostStatus','AGGREGATE_FALLBACK_UNTIL_COMPARABLE_SOURCE_COST_CASE', ...
    'lifecycleCostStatus','PUBLIC_PROXY_PLUS_UNCALIBRATED_REPLACEMENT_CASE');
end
