function p=v4_objective_parameters_4_8()
%V4_OBJECTIVE_PARAMETERS_4_8 Uncalibrated smoke-test coefficients.
% Every numerical coefficient below is [假设值，待企业调研校准].
p=struct;
p.economic=struct( ...
    'annualizedCapitalCNY',0, ...
    'sourceVariableOMCNYPerMWh',20, ...
    'bessThroughputCostCNYPerMWh',30, ...
    'electrolyzerVariableOMCNYPerMWh',15, ...
    'spillPenaltyCNYPerMWh',50, ...
    'unservedPenaltyCNYPerMWh',10000, ...
    'electricityRevenueCNYPerMWh',400, ...
    'hydrogenRevenueCNYPerKg',20, ...
    'computeRevenueCNYPerMWhCS',500, ...
    'marineServiceRevenueCNYPerMWh',300);
p.environment=struct( ...
    'annualizedEmbodiedKgCO2e',0, ...
    'sourceKgCO2ePerMWh',15, ...
    'bessThroughputKgCO2ePerMWh',5, ...
    'gridImportKgCO2ePerMWh',500, ...
    'hydrogenDeliveryKgCO2ePerKg',1);
p.reliability=struct('criticalUnservedWeight',1,'marineUnservedWeight',1);
p.meta=struct('calibrationStatus','UNCALIBRATED', ...
    'notice','[假设值，待企业调研校准]', ...
    'formulaStatus','[需查证文献支撑]');
end
