import os
base = r"C:\Users\86188\Documents\Codex\2026-07-20\ge\work\energy_island_model"
def w(p, c):
    fn = os.path.join(base, p)
    os.makedirs(os.path.dirname(fn), exist_ok=True)
    with open(fn, "w", encoding="utf-8") as f:
        f.write(c)
    print("OK:", p)

w("scenarios/__init__.py", "from .base_scenarios import create_base_scenario, create_stress_scenario, create_parameter_sweep_scenario\n")
w("scenarios/base_scenarios.py", "test")
print("done")
import os
base = r"C:\Users\86188\Documents\Codex\2026-07-20\ge\work\energy_island_model"
out = r"C:\Users\86188\Documents\Codex\2026-07-20\ge\outputs"
os.makedirs(out, exist_ok=True)
def w(p, c):
    fn = os.path.join(base, p)
    os.makedirs(os.path.dirname(fn), exist_ok=True)
    with open(fn, "w", encoding="utf-8") as f:
        f.write(c)
    print("OK:", p)

si = 'from .base_scenarios import create_base_scenario, create_stress_scenario, create_parameter_sweep_scenario\n__all__ = ["create_base_scenario", "create_stress_scenario", "create_parameter_sweep_scenario"]\n'
w("scenarios/__init__.py", si)

bs = 'from ..core.components import EnergyIslandSystem, SourceUnit, SourceType, StorageUnit, StorageType, ComputingUnit, LoadUnit\n'
bs += 'def create_base_scenario():\n'
bs += '    s = EnergyIslandSystem(name="Base")\n'
bs += '    s.add_source(SourceUnit("Wind", SourceType.WIND_OFFSHORE, 100.0, 70.0, 0.95, 0.85))\n'
bs += '    s.add_source(SourceUnit("Solar", SourceType.SOLAR_PV, 50.0, 30.0, 0.90, 0.75))\n'
bs += '    s.add_storage(StorageUnit("Battery", StorageType.BATTERY_LI, 40.0, 160.0, 0.6, 0.1, 0.9, 0.92, 0.92))\n'
bs += '    s.add_computing(ComputingUnit("DC", 30.0, 20.0, 0.67, 1.35, False))\n'
bs += '    s.add_load(LoadUnit("Industrial", 40.0, 35.0, 1.0, True, False))\n'
bs += '    s.add_load(LoadUnit("Residential", 20.0, 15.0, 1.0, False, True))\n'
bs += '    return s\n'
bs += 'def create_stress_scenario():\n'
bs += '    s = EnergyIslandSystem(name="Stress")\n'
bs += '    s.add_source(SourceUnit("Wind", SourceType.WIND_OFFSHORE, 100.0, 20.0, 0.90, 0.85))\n'
bs += '    s.add_source(SourceUnit("Solar", SourceType.SOLAR_PV, 50.0, 5.0, 0.85, 0.75))\n'
bs += '    s.add_source(SourceUnit("Diesel", SourceType.DIESEL, 30.0, 30.0, 0.85, 1.0, False))\n'
bs += '    s.add_storage(StorageUnit("Battery", StorageType.BATTERY_LI, 40.0, 160.0, 0.3, 0.1, 0.9, 0.92, 0.92))\n'
bs += '    s.add_computing(ComputingUnit("DC", 30.0, 28.0, 0.93, 1.40, False))\n'
bs += '    s.add_load(LoadUnit("Industrial", 40.0, 38.0, 1.0, True, False))\n'
bs += '    s.add_load(LoadUnit("Residential", 20.0, 18.0, 1.0, False, True))\n'
bs += '    return s\n'
bs += 'def create_parameter_sweep_scenario():\n'
bs += '    res = []\n'
bs += '    for s_lvl in [0.2, 0.4, 0.6, 0.8, 1.0]:\n'
bs += '        for l_lvl in [0.6, 0.8, 1.0, 1.2]:\n'
bs += '            s = EnergyIslandSystem(f"scan_{s_lvl}_{l_lvl}")\n'
bs += '            s.add_source(SourceUnit("Wind", SourceType.WIND_OFFSHORE, 100.0, 100.0*s_lvl, 0.95, 0.85))\n'
bs += '            s.add_source(SourceUnit("Solar", SourceType.SOLAR_PV, 50.0, 50.0*s_lvl, 0.90, 0.75))\n'
bs += '            s.add_storage(StorageUnit("Battery", StorageType.BATTERY_LI, 40.0, 160.0, 0.5, 0.1, 0.9, 0.92, 0.92))\n'
bs += '            s.add_computing(ComputingUnit("DC", 30.0, 20.0, 0.67, 1.35, False))\n'
bs += '            s.add_load(LoadUnit("Industrial", 40.0, 40.0*l_lvl))\n'
bs += '            s.add_load(LoadUnit("Residential", 20.0, 20.0*l_lvl))\n'
bs += '            res.append((s_lvl, l_lvl, s))\n'
bs += '    return res\n'
w("scenarios/base_scenarios.py", bs)

vi = 'from .plots import plot_power_balance, plot_system_overview, plot_parameter_sweep\n__all__ = ["plot_power_balance", "plot_system_overview", "plot_parameter_sweep"]\n'
w("visualization/__init__.py", vi)
print("Base files done")
print("Now run: python gen_all.py full")
print("to generate full visualization and main")
vl = []
vl.append('from ..core.power_balance import BalanceStatus\n')
vl.append('from ..core.components import EnergyIslandSystem\n')
vl.append('def plot_power_balance(system, result, title=None, save_path=None):\n')
vl.append('    import matplotlib\n')
vl.append('    matplotlib.use("Agg")\n')
vl.append('    import matplotlib.pyplot as plt\n')
vl.append('    import numpy as np\n')
vl.append('    fig, ((a1,a2),(a3,a4)) = plt.subplots(2,2,figsize=(14,10))\n')
vl.append('    fig.suptitle(title or f"{system.name} - Power Balance", fontsize=14, fontweight="bold")\n')
vl.append('    x = np.arange(7)\n')
vl.append('    cats = ["Gen","StgDis","Load","Comp","StgChg","Loss","Resv"]\n')
vl.append('    sup = [result.total_generation_mw, result.storage_discharge_mw, 0,0,0,0,0]\n')
vl.append('    dem = [0,0,result.total_load_mw,result.total_computing_mw,result.storage_charge_mw,result.total_loss_mw,result.reserve_gap_mw]\n')
vl.append('    a1.bar(x-0.15, sup, 0.3, label="Supply", color="green", alpha=0.7)\n')
vl.append('    a1.bar(x+0.15, dem, 0.3, label="Demand", color="red", alpha=0.7)\n')
vl.append('    a1.set_xticks(x); a1.set_xticklabels(cats, fontsize=9)\n')
vl.append('    a1.set_ylabel("MW"); a1.legend(); a1.grid(True, alpha=0.3)\n')
vl.append('    a1.set_title("Supply vs Demand")\n')
vl.append('    lbls = ["Gen","Load","Comp","Loss","ResvGap","NetImb"]\n')
vl.append('    vals = [result.total_generation_mw,result.total_load_mw,result.total_computing_mw,result.total_loss_mw,result.reserve_gap_mw,result.net_imbalance_mw]\n')
vl.append('    colors = ["green","red","orange","gray","purple","blue" if result.net_imbalance_mw>=0 else "darkred"]\n')
vl.append('    bars = a2.bar(lbls, vals, color=colors, alpha=0.7)\n')
vl.append('    for b,v in zip(bars,vals): a2.text(b.get_x()+b.get_width()/2, b.get_height()+max(vals)*0.02, f"{v:.1f}", ha="center", fontsize=9)\n')
vl.append('    a2.set_ylabel("MW"); a2.set_title("Summary"); a2.grid(True, alpha=0.3)\n')
vl.append('    rl = ["Req","Avail","Gap"]\n')
vl.append('    req_r = result.reserve_gap_mw + max(result.total_supply_mw-result.total_demand_mw, 0) * 0.15\n')
vl.append('    if req_r == 0: req_r = result.total_supply_mw * 0.15\n')
vl.append('    avail = max(result.total_supply_mw-result.total_demand_mw, 0)\n')
vl.append('    rv = [req_r, avail, result.reserve_gap_mw]\n')
vl.append('    a3.bar(rl, rv, color=["orange","green","red"], alpha=0.7)\n')
vl.append('    a3.set_ylabel("MW"); a3.set_title(f"Reserve: {result.status.value}"); a3.grid(True, alpha=0.3)\n')
vl.append('    if result.port_details:\n')
vl.append('        pn = list(result.port_details.keys())\n')
vl.append('        pv = list(result.port_details.values())\n')
vl.append('        pc = ["green" if v>=0 else "red" for v in pv]\n')
vl.append('        a4.barh(pn, pv, color=pc, alpha=0.7)\n')
vl.append('        a4.set_xlabel("MW")\n')
vl.append('        a4.set_title("Port Details")\n')
vl.append('    a4.grid(True, alpha=0.3)\n')
vl.append('    plt.tight_layout()\n')
vl.append('    if save_path: plt.savefig(save_path, dpi=150, bbox_inches="tight"); print("Saved:", save_path)\n')
vl.append('    plt.close()\n')
vl.append('    return fig\n')
vl.append('def plot_system_overview(system, save_path=None):\n')
vl.append('    import matplotlib; matplotlib.use("Agg")\n')
vl.append('    import matplotlib.pyplot as plt\n')
vl.append('    fig, (a1,a2) = plt.subplots(1,2,figsize=(12,5))\n')
vl.append('    fig.suptitle(f"Overview: {system.name}", fontsize=14)\n')
vl.append('    labels=[]; sizes=[]\n')
vl.append('    tsrc=sum(s.rated_capacity_mw for s in system.sources.values())\n')
vl.append('    tstg=sum(s.rated_power_mw for s in system.storages.values())\n')
vl.append('    tcmp=sum(c.rated_power_mw for c in system.computings.values())\n')
vl.append('    tld=sum(l.rated_power_mw for l in system.loads.values())\n')
vl.append('    for lbl,val,clr in [("Src",tsrc,"green"),("Stg",tstg,"blue"),("Cmp",tcmp,"orange"),("Load",tld,"red")]:\n')
vl.append('        if val>0: labels.append(f"{lbl}\\n{val:.0f}MW"); sizes.append(val)\n')
vl.append('    a1.pie(sizes, labels=labels, autopct="%1.1f%%", startangle=90, colors=["green","blue","orange","red"][:len(sizes)])\n')
vl.append('    a1.set_title("Installed Capacity")\n')
vl.append('    ol=[]; ov=[]\n')
vl.append('    for src in system.sources.values(): ol.append(f"{src.name}\\n({src.current_output_mw:.0f}MW)"); ov.append(src.current_output_mw)\n')
vl.append('    for stg in system.storages.values(): ol.append(f"{stg.name}\\nSOC={stg.current_soc:.0%}"); ov.append(stg.current_soc*stg.rated_power_mw)\n')
vl.append('    for cmp in system.computings.values(): ol.append(f"{cmp.name}\\n({cmp.current_load_mw:.0f}MW)"); ov.append(-cmp.current_load_mw)\n')
vl.append('    for ld in system.loads.values(): ol.append(f"{ld.name}\\n({ld.current_load_mw:.0f}MW)"); ov.append(-ld.current_load_mw)\n')
vl.append('    bc = ["green" if v>=0 else "red" for v in ov]\n')
vl.append('    a2.barh(ol, ov, color=bc, alpha=0.7)\n')
vl.append('    a2.axvline(0, color="black", linewidth=0.5)\n')
vl.append('    a2.set_xlabel("MW (+inject, -absorb)")\n')
vl.append('    a2.set_title("Current Operation")\n')
vl.append('    plt.tight_layout()\n')
vl.append('    if save_path: plt.savefig(save_path, dpi=150, bbox_inches="tight")\n')
vl.append('    plt.close()\n')
vl.append('    return fig\n')
vl.append('def plot_parameter_sweep(results, save_path=None):\n')
vl.append('    import matplotlib; matplotlib.use("Agg")\n')
vl.append('    import matplotlib.pyplot as plt; import numpy as np\n')
vl.append('    fig, ((a1,a2),(a3,a4)) = plt.subplots(2,2,figsize=(14,10))\n')
vl.append('    fig.suptitle("Parameter Sweep", fontsize=14)\n')
vl.append('    sl = sorted(set(r[0] for r in results))\n')
vl.append('    ll = sorted(set(r[1] for r in results))\n')
vl.append('    for a,metric,m,u in [(a1,"net_imbalance_mw","Net Imbalance","MW"),(a2,"total_loss_mw","Losses","MW"),(a3,"reserve_gap_mw","Reserve Gap","MW"),(a4,"surplus_ratio","Surplus Ratio","")]:\n')
vl.append('        for lv in ll:\n')
vl.append('            vals = []\n')
vl.append('            for s in sl:\n')
vl.append('                for si,li,res in results:\n')
vl.append('                    if abs(si-s)<0.01 and abs(li-lv)<0.01:\n')
vl.append('                        v = getattr(res, metric, 0)\n')
vl.append('                        if callable(v): v = v()\n')
vl.append('                        vals.append(v)\n')
vl.append('            if vals:\n')
vl.append('                a.plot(sl[:len(vals)], vals, marker="o", label=f"Load={lv:.1f}pu")\n')
vl.append('        a.set_xlabel("Source [pu]"); a.set_ylabel(f"{m} [{u}]" if u else m)\n')
vl.append('        a.set_title(metric); a.legend(fontsize=8); a.grid(True, alpha=0.3)\n')
vl.append('    plt.tight_layout()\n')
vl.append('    if save_path: plt.savefig(save_path, dpi=150, bbox_inches="tight")\n')
vl.append('    plt.close()\n')
vl.append('    return fig\n')
w("visualization/plots.py", "".join(vl))

mc = []
mc.append('import sys, os\n')
mc.append('sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\n')
mc.append('from core.components import EnergyIslandSystem, SourceUnit, SourceType, StorageUnit, StorageType, ComputingUnit, LoadUnit\n')
mc.append('from core.power_balance import BalanceStatus\n')
mc.append('from scenarios.base_scenarios import create_base_scenario, create_stress_scenario, create_parameter_sweep_scenario\n')
mc.append('from visualization.plots import plot_power_balance, plot_system_overview, plot_parameter_sweep\n')
mc.append('out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "outputs")\n')
mc.append('os.makedirs(out_dir, exist_ok=True)\n')
mc.append('def run_base():\n')
mc.append('    print("="*60)\n')
mc.append('    print("Scene 1: Base")\n')
mc.append('    print("="*60)\n')
mc.append('    sys = create_base_scenario()\n')
mc.append('    print(sys)\n')
mc.append('    res = sys.solve()\n')
mc.append('    print(f"  Gen:{res.total_generation_mw:>8.2f}  StgDis:{res.storage_discharge_mw:>8.2f}  Load:{res.total_load_mw:>8.2f}")\n')
mc.append('    print(f"  Comp:{res.total_computing_mw:>8.2f}  StgChg:{res.storage_charge_mw:>8.2f}  Loss:{res.total_loss_mw:>8.2f}")\n')
mc.append('    print(f"  ResvGap:{res.reserve_gap_mw:>8.2f}  Net:{res.net_imbalance_mw:>8.2f}  Status:{res.status.value}")\n')
mc.append('    print(f"  SurplusRatio: {res.surplus_ratio():.2%}")\n')
mc.append('    plot_power_balance(sys, res, save_path=os.path.join(out_dir,"base_scenario.png"))\n')
mc.append('    plot_system_overview(sys, save_path=os.path.join(out_dir,"system_overview.png"))\n')
mc.append('    return sys, res\n')
mc.append('def run_stress():\n')
mc.append('    print("="*60)\n')
mc.append('    print("Scene 2: Stress")\n')
mc.append('    print("="*60)\n')
mc.append('    sys = create_stress_scenario()\n')
mc.append('    print(sys)\n')
mc.append('    res = sys.solve()\n')
mc.append('    print(f"  Gen:{res.total_generation_mw:>8.2f}  StgDis:{res.storage_discharge_mw:>8.2f}  Load:{res.total_load_mw:>8.2f}")\n')
mc.append('    print(f"  Comp:{res.total_computing_mw:>8.2f}  StgChg:{res.storage_charge_mw:>8.2f}  Loss:{res.total_loss_mw:>8.2f}")\n')
mc.append('    print(f"  ResvGap:{res.reserve_gap_mw:>8.2f}  Net:{res.net_imbalance_mw:>8.2f}  Status:{res.status.value}")\n')
mc.append('    plot_power_balance(sys, res, save_path=os.path.join(out_dir,"stress_scenario.png"))\n')
mc.append('    return sys, res\n')
mc.append('def run_sweep():\n')
mc.append('    print("="*60)\n')
mc.append('    print("Scene 3: Parameter Sweep")\n')
mc.append('    print("="*60)\n')
mc.append('    scenarios = create_parameter_sweep_scenario()\n')
mc.append('    results = []\n')
mc.append('    for sl, ll, sys in scenarios:\n')
mc.append('        results.append((sl, ll, sys.solve()))\n')
mc.append('    print(f"Completed {len(results)} points")\n')
mc.append('    plot_parameter_sweep(results, save_path=os.path.join(out_dir,"param_sweep.png"))\n')
mc.append('    return results\n')
mc.append('if __name__ == "__main__":\n')
mc.append('    run_base()\n')
mc.append('    run_stress()\n')
mc.append('    run_sweep()\n')
mc.append('    print("\\nDone!")\n')
mc.append('    print(f"Outputs in: {out_dir}")\n')
w("main.py", "".join(mc))

w("run_model.py", 'import sys, os\nsys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\nfrom main import run_base, run_stress, run_sweep\nif __name__ == "__main__":\n    run_base()\n    run_stress()\n    run_sweep()\n    print("Done.")\n')

print("All files generated!")
print("Run: python main.py")
def gen_report():
    import sys, os
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from scenarios.base_scenarios import create_base_scenario, create_stress_scenario, create_parameter_sweep_scenario
    od = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "outputs")
    os.makedirs(od, exist_ok=True)
    s1 = create_base_scenario(); r1 = s1.solve()
    s2 = create_stress_scenario(); r2 = s2.solve()
    ss = create_parameter_sweep_scenario()
    rs = [(sl, ll, s.solve()) for sl, ll, s in ss]
    L = []
    def A(s): L.append(s)
    A("# Energy Island Power Balance Model Report")
    A("## Multi-Port Coupling and Electric Power Balance\n")
    A("## 1 Model Overview")
    A("This model establishes a multi-port coupled electric power balance for energy islands,")
    A("connecting Source, Storage, Computing, and Load ports into one conservation relationship,")
    A("with defined power direction conventions, loss models, and reserve gap analysis.\n")
    A("### 1.1 Model Boundary")
    A("- System boundary: Energy island AC bus node")
    A("- Port types: Source(inject), Storage(bi-dir), Computing(absorb), Load(absorb), Loss, Reserve")
    A("- Direction convention: POSITIVE=inject, NEGATIVE=absorb, BIDIRECTIONAL=bi-dir")
    A("- Time scale: Steady-state power balance\n")
    A("### 1.2 Base Parameters")
    A("| Category | Parameter | Symbol | Value | Unit |")
    A("|---|---|---|---|---|")
    A("| Source | Offshore Wind | P_wind | 100.0 | MW |")
    A("| Source | Solar PV | P_pv | 50.0 | MW |")
    A("| Source | Wind Efficiency | eta_w | 0.95 | - |")
    A("| Source | PV Efficiency | eta_pv | 0.90 | - |")
    A("| Storage | Battery Power | P_bat | 40.0 | MW |")
    A("| Storage | Battery Energy | E_bat | 160.0 | MWh |")
    A("| Storage | Charge Efficiency | eta_chg | 0.92 | - |")
    A("| Storage | Discharge Efficiency | eta_dis | 0.92 | - |")
    A("| Computing | DC Rated Power | P_dc | 30.0 | MW |")
    A("| Computing | PUE | PUE | 1.35 | - |")
    A("| Load | Industrial | P_ind | 40.0 | MW |")
    A("| Load | Residential | P_res | 20.0 | MW |")
    A("| Loss | Line Loss Ratio | rho_line | 0.02 | - |")
    A("| Loss | Transformer Loss Ratio | rho_tf | 0.01 | - |")
    A("| Loss | Converter Loss Ratio | rho_conv | 0.03 | - |")
    A("| Loss | Auxiliary Power Ratio | rho_aux | 0.01 | - |\n")
    A("## 2 Mathematical Model\n")
    A("### 2.1 Core Power Conservation Equation")
    A("Sum(P_src_i) + Sum(P_stg_dis_j) = Sum(P_load_k) + Sum(P_comp_m) + Sum(P_stg_chg_n) + P_loss + P_reserve_gap\n")
    A("### 2.2 Port Direction Convention")
    A("- SOURCE: POSITIVE, P>0 (inject into bus)")
    A("- LOAD: NEGATIVE, P<0 (absorb from bus)")
    A("- COMPUTING: NEGATIVE, P<0 (absorb from bus)")
    A("- STORAGE: BIDIRECTIONAL, P>0 discharge / P<0 charge")
    A("- LOSS: NEGATIVE, P<0")
    A("- RESERVE: NEGATIVE, P<0\n")
    A("### 2.3 Loss Model")
    A("P_loss = P_line + P_transformer + P_converter + P_auxiliary")
    A("P_line = P_avg * 0.02 | P_transformer = P_avg * 0.01")
    A("P_converter = P_avg * 0.03 | P_auxiliary = P_cap * 0.01\n")
    A("### 2.4 Reserve Gap Analysis")
    A("R_spin = max(P_max_unit, 0.1 * P_load)")
    A("R_contingency = 0.05 * P_load")
    A("P_reserve_gap = max(0, R_spin + R_contingency - R_available)\n")
    pd = lambda v: f"{v:.2f}"
    A("## 3 Scenario Analysis Results\n")
    A("### 3.1 Base Scenario")
    A(f"- Generation: {pd(r1.total_generation_mw)} MW")
    A(f"- Load: {pd(r1.total_load_mw)} MW")
    A(f"- Computing: {pd(r1.total_computing_mw)} MW")
    A(f"- Losses: {pd(r1.total_loss_mw)} MW")
    A(f"- Reserve Gap: {pd(r1.reserve_gap_mw)} MW")
    A(f"- Net Imbalance: {pd(r1.net_imbalance_mw)} MW")
    A(f"- Status: {r1.status.value}")
    A(f"- Surplus Ratio: {pd(r1.surplus_ratio()*100)}%\n")
    A("### 3.2 Stress Scenario")
    A(f"- Generation: {pd(r2.total_generation_mw)} MW")
    A(f"- Load: {pd(r2.total_load_mw)} MW")
    A(f"- Computing: {pd(r2.total_computing_mw)} MW")
    A(f"- Losses: {pd(r2.total_loss_mw)} MW")
    A(f"- Reserve Gap: {pd(r2.reserve_gap_mw)} MW")
    A(f"- Net Imbalance: {pd(r2.net_imbalance_mw)} MW")
    A(f"- Status: {r2.status.value}\n")
    A("### 3.3 Parameter Sweep (20 operating points)")
    A("Source levels: 0.2, 0.4, 0.6, 0.8, 1.0 pu")
    A("Load levels: 0.6, 0.8, 1.0, 1.2 pu\n")
    A("## 4 Code Architecture\n")
    A("### Directory structure:")
    A("- core/ports.py: Port direction conventions and base port class")
    A("- core/power_balance.py: Multi-port coupling power conservation equation")
    A("- core/components.py: Source, Storage, Computing, Load component classes")
    A("- core/losses.py: Loss model")
    A("- core/reserve.py: Reserve gap analysis")
    A("- scenarios/base_scenarios.py: Base and stress scenario definitions")
    A("- visualization/plots.py: Power balance visualization")
    A("- main.py: Entry point\n")
    A("## 5 Conclusions")
    A("1. Unified power conservation relation connecting all four port types")
    A("2. Clear port direction conventions and sign system")
    A("3. Comprehensive loss modeling (line, transformer, converter, auxiliary)")
    A("4. Dynamic reserve gap analysis")
    A("5. Scenario-based simulation capability\n")
    A("---\n*Generated: 2026-07-20 | Model v1.0*")
    fp = os.path.join(od, "energy_island_report.md")
    with open(fp, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("Report saved:", fp)
if __name__ == "__main__":
    gen_report()
print("gen_all.py updated with report generation")
print("Run: python gen_all.py to regenerate all files")
if __name__ == "__main__":
    gen_report()
