def gen_report():
    import sys, os
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from scenarios.base_scenarios import create_base_scenario, create_stress_scenario
    od = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "outputs")
    os.makedirs(od, exist_ok=True)
    s1 = create_base_scenario(); r1 = s1.solve()
    s2 = create_stress_scenario(); r2 = s2.solve()
    L = []
    def A(s): L.append(s)
    A("# Energy Island Power Balance Model Report")
    A("## Multi-Port Coupling and Electric Power Balance Model")
    A("")
    A("## 1 Model Overview")
    A("This model establishes a multi-port coupled electric power balance for energy islands,")
    A("connecting Source, Storage, Computing, and Load ports into one conservation relationship.")
    A("")
    A("### 1.1 Model Boundary")
    A("- System boundary: Energy island AC bus node")
    A("- Port types: Source(inject), Storage(bi-dir), Computing(absorb), Load(absorb), Loss, Reserve")
    A("- Direction convention: POSITIVE=inject bus, NEGATIVE=absorb from bus, BIDIRECTIONAL")
    A("- Time scale: Steady-state power balance")
    A("")
    A("### 1.2 Base Parameters")
    A("| Category | Parameter | Symbol | Value | Unit |")
    A("|---|---|---|---|---|")
    A("| Source | Offshore Wind | P_wind | 100.0 | MW |")
    A("| Source | Solar PV | P_pv | 50.0 | MW |")
    A("| Source | Wind Efficiency | eta_w | 0.95 | - |")
    A("| Source | PV Efficiency | eta_pv | 0.90 | - |")
    A("| Storage | Battery Power | P_bat | 40.0 | MW |")
    A("| Storage | Battery Energy | E_bat | 160.0 | MWh |")
    A("| Storage | Charge Efficiency | eta_chg | 0.92 | - |")
    A("| Storage | Discharge Efficiency | eta_dis | 0.92 | - |")
    A("| Computing | DC Rated Power | P_dc | 30.0 | MW |")
    A("| Computing | PUE | PUE | 1.35 | - |")
    A("| Load | Industrial | P_ind | 40.0 | MW |")
    A("| Load | Residential | P_res | 20.0 | MW |")
    A("| Loss | Line Loss Ratio | rho_line | 0.02 | - |")
    A("| Loss | Transformer | rho_tf | 0.01 | - |")
    A("| Loss | Converter | rho_conv | 0.03 | - |")
    A("| Loss | Auxiliary | rho_aux | 0.01 | - |")
    A("")
    A("## 2 Mathematical Model")
    A("")
    A("### 2.1 Core Power Conservation Equation")
    A("Sum(P_src_i) + Sum(P_stg_dis_j) = Sum(P_load_k) + Sum(P_comp_m) + Sum(P_stg_chg_n) + P_loss + P_reserve_gap")
    A("")
    A("### 2.2 Port Direction Convention")
    A("- SOURCE: POSITIVE, P>0 (inject)")
    A("- LOAD: NEGATIVE, P<0 (absorb)")
    A("- COMPUTING: NEGATIVE, P<0 (absorb)")
    A("- STORAGE: BIDIRECTIONAL, P>0 discharge / P<0 charge")
    A("- LOSS: NEGATIVE, P<0")
    A("- RESERVE: NEGATIVE, P<0")
    A("")
    A("### 2.3 Loss Model")
    A("P_loss = P_line + P_tf + P_conv + P_aux")
    A("P_line = Pavg*0.02 | P_tf = Pavg*0.01 | P_conv = Pavg*0.03 | P_aux = Pcap*0.01")
    A("")
    A("### 2.4 Reserve Gap Analysis")
    A("R_spin = max(P_max_unit, 0.1*P_load)")
    A("R_cont = 0.05*P_load")
    A("P_reserve_gap = max(0, R_spin+R_cont-R_available)")
    A("")
    A("## 3 Results")
    A("")
    A("### 3.1 Base Scenario")
    A(f"- Generation: {r1.total_generation_mw:.2f} MW")
    A(f"- Load: {r1.total_load_mw:.2f} MW")
    A(f"- Computing: {r1.total_computing_mw:.2f} MW")
    A(f"- Loss: {r1.total_loss_mw:.2f} MW")
    A(f"- Reserve Gap: {r1.reserve_gap_mw:.2f} MW")
    A(f"- Net Imbalance: {r1.net_imbalance_mw:.2f} MW")
    A(f"- Status: {r1.status.value}")
    A(f"- Surplus Ratio: {r1.surplus_ratio()*100:.2f}%")
    A("")
    A("### 3.2 Stress Scenario")
    A(f"- Generation: {r2.total_generation_mw:.2f} MW")
    A(f"- Load: {r2.total_load_mw:.2f} MW")
    A(f"- Computing: {r2.total_computing_mw:.2f} MW")
    A(f"- Loss: {r2.total_loss_mw:.2f} MW")
    A(f"- Reserve Gap: {r2.reserve_gap_mw:.2f} MW")
    A(f"- Net Imbalance: {r2.net_imbalance_mw:.2f} MW")
    A(f"- Status: {r2.status.value}")
    A("")
    A("## 4 Code Architecture")
    A("- core/ports.py: Port direction conventions and base port class")
    A("- core/power_balance.py: Multi-port coupling power conservation equation")
    A("- core/components.py: Source, Storage, Computing, Load component classes")
    A("- core/losses.py: Loss model")
    A("- core/reserve.py: Reserve gap analysis")
    A("- scenarios/base_scenarios.py: Scenario definitions")
    A("- visualization/plots.py: Power balance visualization")
    A("- main.py: Entry point")
    A("")
    A("## 5 Conclusions")
    A("1. Unified power conservation connecting all four port types")
    A("2. Clear port direction conventions")
    A("3. Comprehensive loss modeling")
    A("4. Dynamic reserve gap analysis")
    A("5. Scenario-based simulation capability")
    A("")
    A("---")
    A("*Generated: 2026-07-20 | Model v1.0*")
    fp = os.path.join(od, "energy_island_report.md")
    with open(fp, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("Report saved:", fp)
if __name__ == "__main__":
    gen_report()
