function actual=v4_reconcile_actuals_4_9(cfg,p43,p45,p46,p47,dispatch)
%V4_RECONCILE_ACTUALS_4_9 Derive actual spill and service shortfall before 4.4.
raw=p43.ports.source.actualMW+p45.ports.bessDischarge.actualMW+ ...
    p47.ports.gridImport.actualMW-p45.ports.bessCharge.actualMW ...
    -p45.ports.electrolyzer.actualMW-p46.ports.dcFacility.actualMW ...
    -p47.ports.exportSend.actualMW-p47.ports.marine.actualMW ...
    -p43.loss.pSourceAuxLoadMW-cfg.commonBus.commonAuxMW ...
    -cfg.commonBus.postPOILossMW;
assert(all(raw>=-cfg.commonBus.balanceToleranceMW), ...
    'Committed responses exceed available supply; redispatch is required.');
actual=struct;
actual.spillMW=max(0,raw);
actual.criticalUnservedMW=dispatch.computeUnservedPlannedMW;
actual.marineUnservedMW=p47.service.marineUnservedMW;
actual.totalUnservedMW=actual.criticalUnservedMW+actual.marineUnservedMW;
actual.preSpillResidualMW=raw;
end
