function cfg = v5_default_config(caseMode)
%V5_DEFAULT_CONFIG C4/V5 dispatch-optimization configuration.
%
% mechanism_test contains runnable mechanism-verification assumptions.
% engineering_base deliberately leaves unsigned engineering parameters NaN.
% Neither mode is a project design recommendation.

if nargin < 1 || isempty(caseMode)
    caseMode = 'mechanism_test';
end
caseMode = validatestring(caseMode, {'mechanism_test','engineering_base'});

cfg = struct;
cfg.meta = struct( ...
    'modelId','BLUE_HUB_C4_V5', ...
    'schemaId','BLUE_HUB_CH4_SCHEMA_V3', ...
    'schemaVersion','3.0.0', ...
    'caseMode',caseMode, ...
    'parameterVersion',[caseMode '_v5_20260728'], ...
    'status','V5_CANDIDATE_FOR_SCENARIO_VALIDATION', ...
    'assumptionNotice','[假设值，待企业调研校准]', ...
    'formulaNotice','[需查证文献支撑]');

cfg.time = struct( ...
    'dispatchStepH',1, ...
    'shortValidationHorizonH',48, ...
    'annualValidationHorizonH',8760, ...
    'energyLayer','HOURLY_DAY_AHEAD_OR_MECHANISM', ...
    'requiredIntradayCheck','5_TO_15_MIN_POWER_FEASIBILITY', ...
    'requiredDynamicCheck','SECOND_SCALE_GFM_EMT_OR_VALIDATED_PROXY');

cfg.site = struct( ...
    'distanceToShoreKm',NaN, ...
    'waterDepthM',NaN, ...
    'prototypeClass','UNSIGNED_DEEP_OFFSHORE_ENERGY_ISLAND');

cfg.source = struct( ...
    'installedMW',NaN, ...
    'windInstalledMW',NaN, ...
    'pvInstalledMW',NaN, ...
    'tidalInstalledMW',NaN, ...
    'meterPoint','MP-03-SOURCE-POI', ...
    'availablePowerIncludesCollectionLoss',true);

cfg.internal = struct( ...
    'commonAuxDemandMW',NaN, ...
    'postPOILossMW',NaN);

cfg.bess = struct( ...
    'powerMW',NaN, ...
    'energyMWh',NaN, ...
    'chargeMaxMW',NaN, ...
    'dischargeMaxMW',NaN, ...
    'etaCharge',NaN, ...
    'etaDischarge',NaN, ...
    'standingRetentionPerStep',NaN, ...
    'socMin',NaN, ...
    'socMax',NaN, ...
    'socInitial',NaN, ...
    'gfmReservePowerMW',NaN, ...
    'gfmReserveEnergyMWh',NaN, ...
    'gfmAbsorptionReservePowerMW',NaN, ...
    'gfmAbsorptionReserveEnergyMWh',NaN, ...
    'terminalRule','cyclic', ...
    'terminalTargetSOC',NaN, ...
    'dynamicEnvelopeRequiredForEngineering',true);

cfg.hydrogen = struct( ...
    'electrolyzerRatedMW',NaN, ...
    'moduleCount',NaN, ...
    'moduleRatedMW',NaN, ...
    'moduleMinMW',NaN, ...
    'rampUpMWPerH',NaN, ...
    'rampDownMWPerH',NaN, ...
    'startEnergyMWhPerModule',NaN, ...
    'secKWhPerKg',NaN, ...
    'secBoundary','AC_FACILITY_TO_30_BARG_H2_EXCLUDES_RAW_SEAWATER_PRETREATMENT_HIGHER_PRESSURE_LIQUEFACTION', ...
    'storageMaxKg',NaN, ...
    'storageInitialKg',NaN, ...
    'storageRetentionPerStep',NaN, ...
    'pipeCapacityKgPerH',NaN, ...
    'shipCapacityKgPerH',NaN, ...
    'pipeLossFraction',NaN, ...
    'shipLossFraction',NaN, ...
    'terminalRule','cyclic', ...
    'terminalTargetKg',NaN, ...
    'shippingModel','EQUIVALENT_HOURLY_THROUGHPUT_NO_VOYAGE_SCHEDULE');

cfg.h2Power = struct( ...
    'enabled',false, ...
    'ratedMW',0, ...
    'efficiencyLHV',NaN, ...
    'h2LHVKWhPerKg',33.33, ...
    'rampUpMWPerH',NaN, ...
    'rampDownMWPerH',NaN);

cfg.compute = struct( ...
    'moduleCount',NaN, ...
    'moduleFacilityMinMW',NaN, ...
    'moduleFacilityMaxMW',NaN, ...
    'facilityMaxMW',NaN, ...
    'pue',NaN, ...
    'rampUpMWPerH',NaN, ...
    'rampDownMWPerH',NaN, ...
    'serviceUnit','MWh-CS', ...
    'baseDemandIsReliabilityLoad',true, ...
    'flexDemandIsCurtailable',true);

cfg.output = struct( ...
    'cableSendCapacityMW',NaN, ...
    'gridAcceptCapacityMW',NaN, ...
    'cableLossFraction',NaN, ...
    'marineDemandMW',NaN, ...
    'powerExportEnabled',true, ...
    'hydrogenPipeEnabled',true, ...
    'hydrogenShipEnabled',true);

cfg.economic = struct( ...
    'sourceVariableOMCNYPerMWh',NaN, ...
    'bessDegradationCNYPerMWhDischarge',NaN, ...
    'hydrogenVariableCNYPerKgProduced',NaN, ...
    'electrolyzerStartCNYPerModule',NaN, ...
    'h2PipeTransportCNYPerKgWithdrawn',NaN, ...
    'h2ShipTransportCNYPerKgWithdrawn',NaN, ...
    'h2PowerVariableCNYPerMWh',NaN, ...
    'cableVariableOMCNYPerMWhReceived',NaN, ...
    'computeVariableOMCNYPerMWhCS',NaN, ...
    'bessTerminalValueCNYPerMWh',NaN, ...
    'h2InventoryTerminalValueCNYPerKg',NaN, ...
    'electricityPriceCNYPerMWhReceived',NaN, ...
    'hydrogenPriceCNYPerKgDelivered',NaN, ...
    'computePriceCNYPerMWhCS',NaN, ...
    'marineServiceValueCNYPerMWh',NaN, ...
    'internalUnservedPenaltyCNYPerMWh',NaN, ...
    'marineUnservedPenaltyCNYPerMWh',NaN, ...
    'computeBaseUnservedPenaltyCNYPerMWh',NaN, ...
    'investmentBudgetCNY',NaN, ...
    'minimumProjectIRR',NaN, ...
    'minimumDSCR',NaN, ...
    'maximumPaybackYear',NaN);

cfg.environment = struct( ...
    'sourceLifecycleKgCO2ePerMWhUsed',NaN, ...
    'bessThroughputKgCO2ePerMWh',NaN, ...
    'hydrogenNonElectricKgCO2ePerKgProduced',NaN, ...
    'h2ShipKgCO2ePerKgWithdrawn',NaN, ...
    'h2PipeKgCO2ePerKgWithdrawn',NaN, ...
    'h2PowerNonFuelKgCO2ePerMWh',NaN, ...
    'electricityBaselineKgCO2ePerMWhReceived',NaN, ...
    'hydrogenBaselineKgCO2ePerKgDelivered',NaN, ...
    'computeBaselineKgCO2ePerMWhCS',NaN, ...
    'marineBaselineKgCO2ePerMWh',NaN, ...
    'accountingBoundary','PROJECT_EMISSIONS_MINUS_AVOIDED_BASELINE_EMISSIONS');

cfg.objective = struct( ...
    'method','EPSILON_CONSTRAINT', ...
    'primary','economicNetCostCNY', ...
    'maxENSMWh',Inf, ...
    'maxNetGHGKgCO2e',Inf, ...
    'minRenewableUtilization',0, ...
    'tieBreak','minCurtailment', ...
    'temporalTieBreak','none', ...
    'primaryRelativeTolerance',1e-7);

cfg.solver = struct( ...
    'name','intlinprog', ...
    'relativeGapTolerance',1e-6, ...
    'maxTimeS',300, ...
    'display','off');

cfg.audit = struct( ...
    'distanceAndCapacityEvidenceStatus','UNSIGNED_UNLESS_MECHANISM_TEST', ...
    'hourlyScopeNotice',[ ...
        'Hourly optimization is an energy-scheduling layer. It does not ', ...
        'prove frequency, voltage, fault ride-through or black-start performance.'], ...
    'shipScopeNotice',[ ...
        'Hourly kg/h shipping is suitable for channel activation tests only; ', ...
        'commercial logistics requires vessel lot, berth, weather-window and ', ...
        'round-trip constraints.'], ...
    'ammoniaScopeNotice',[ ...
        'Ammonia synthesis and ammonia shipping are outside the current V5 ', ...
        'dispatch core and must not be reported as activated.']);

cfg.evidence = struct( ...
    'dispatchStep',struct( ...
        'sourceType','project modelling boundary plus NREL fast-dispatch study', ...
        'status','[假设值，待企业调研校准]'), ...
    'siteAndCapacity',struct( ...
        'sourceType','government and CHN Energy public prototypes', ...
        'status','[假设值，待企业调研校准]'), ...
    'bess',struct( ...
        'sourceType','Sandia journal model; project ratings unsigned', ...
        'status','[假设值，待企业/PCS调研校准]'), ...
    'electrolyzer',struct( ...
        'sourceType','Nel manufacturer data and DOE program record', ...
        'status','full-load SEC sourced; aggregation assumptions unsigned'), ...
    'compute',struct( ...
        'sourceType','government public sea-use report and V4 module model', ...
        'status','PUE is a public proxy, not a project guarantee'), ...
    'cableAndShipping',struct( ...
        'sourceType','NREL technical report; project logistics unsigned', ...
        'status','[假设值，待企业调研校准]'), ...
    'economics',struct( ...
        'sourceType','public scenario anchors plus unsigned project proxies', ...
        'status','[假设值，待企业调研校准]'), ...
    'environment',struct( ...
        'sourceType','ISO LCA method; inventory factors unsigned', ...
        'status','[假设值，待企业或第三方LCA校准]'), ...
    'gfm',struct( ...
        'sourceType','NREL/WECC/UNIFI dynamic model structure', ...
        'status','reserve values [假设值，待PCS厂商校准]'));

if strcmp(caseMode,'mechanism_test')
    cfg = apply_mechanism_values(cfg);
end
end

function cfg = apply_mechanism_values(cfg)
% Runnable values for mechanism verification only.
cfg.site.distanceToShoreKm = 200; % [假设值，待企业调研校准]
cfg.site.waterDepthM = 100; % [假设值，待企业调研校准]

cfg.source.installedMW = 800; % [假设值，待企业调研校准]
cfg.source.windInstalledMW = 680; % [假设值，待企业调研校准]
cfg.source.pvInstalledMW = 80; % [假设值，待企业调研校准]
cfg.source.tidalInstalledMW = 40; % [假设值，待企业调研校准]
cfg.internal.commonAuxDemandMW = 0.25; % [假设值，待企业调研校准]
cfg.internal.postPOILossMW = 0.20; % [假设值，待企业调研校准]

cfg.bess.powerMW = 80; % [假设值，待企业调研校准]
cfg.bess.energyMWh = 160; % [假设值，待企业调研校准]
cfg.bess.chargeMaxMW = 80;
cfg.bess.dischargeMaxMW = 80;
cfg.bess.etaCharge = 0.95; % [假设值，待企业调研校准]
cfg.bess.etaDischarge = 0.95; % [假设值，待企业调研校准]
cfg.bess.standingRetentionPerStep = 1;
cfg.bess.socMin = 0.10;
cfg.bess.socMax = 0.90;
cfg.bess.socInitial = 0.50;
cfg.bess.gfmReservePowerMW = 5; % [假设值，待PCS厂商校准]
cfg.bess.gfmReserveEnergyMWh = 1; % [假设值，待PCS厂商校准]
cfg.bess.gfmAbsorptionReservePowerMW = 5; % [假设值，待PCS厂商校准]
cfg.bess.gfmAbsorptionReserveEnergyMWh = 1; % [假设值，待PCS厂商校准]
cfg.bess.terminalTargetSOC = 0.50;

cfg.hydrogen.electrolyzerRatedMW = 100;
cfg.hydrogen.moduleCount = 5;
cfg.hydrogen.moduleRatedMW = 20;
cfg.hydrogen.moduleMinMW = 4;
cfg.hydrogen.rampUpMWPerH = 26640; % 7.4%/s × 100 MW; manufacturer capability
cfg.hydrogen.rampDownMWPerH = 26640;
cfg.hydrogen.startEnergyMWhPerModule = 0; % [假设值，待OEM校准]
cfg.hydrogen.secKWhPerKg = 56.77; % manufacturer full-load value, 30 barg boundary
cfg.hydrogen.storageMaxKg = 72000; % [假设值，待企业调研校准]
cfg.hydrogen.storageInitialKg = 0;
cfg.hydrogen.storageRetentionPerStep = 1; % [假设值，待储氢路线校准]
cfg.hydrogen.pipeCapacityKgPerH = 1800; % [假设值，待企业调研校准]
cfg.hydrogen.shipCapacityKgPerH = 1200; % [假设值，待企业调研校准]
cfg.hydrogen.pipeLossFraction = 0.01; % [假设值，待企业调研校准]
cfg.hydrogen.shipLossFraction = 0.02; % [假设值，待企业调研校准]
cfg.hydrogen.terminalTargetKg = 0;

cfg.h2Power.efficiencyLHV = 0.50; % [假设值，待设备路线校准]
cfg.h2Power.rampUpMWPerH = 1000; % [假设值，待设备路线校准]
cfg.h2Power.rampDownMWPerH = 1000; % [假设值，待设备路线校准]

cfg.compute.moduleCount = 16; % [假设值，待企业调研校准]
cfg.compute.moduleFacilityMinMW = 2.3937024865; % V4 single-unit model result
cfg.compute.moduleFacilityMaxMW = 7.618080; % V4 single-unit model result
cfg.compute.facilityMaxMW = 120; % [假设值，待企业调研校准]
cfg.compute.pue = 1.076; % public underwater-DC reference, not a project guarantee
cfg.compute.rampUpMWPerH = 120; % [假设值，待IT/BMS校准]
cfg.compute.rampDownMWPerH = 120; % [假设值，待IT/BMS校准]

cfg.output.cableSendCapacityMW = 200; % [假设值，待企业调研校准]
cfg.output.gridAcceptCapacityMW = 200; % [假设值，待接入批复校准]
cfg.output.cableLossFraction = 0.08; % [假设值，待电缆设计计算校准]
cfg.output.marineDemandMW = 18; % [假设值，待企业调研校准]

cfg.economic.sourceVariableOMCNYPerMWh = 20; % [假设值，待企业调研校准]
cfg.economic.bessDegradationCNYPerMWhDischarge = 30; % [假设值，待企业调研校准]
cfg.economic.hydrogenVariableCNYPerKgProduced = 3.5; % [假设值，待企业调研校准]
cfg.economic.electrolyzerStartCNYPerModule = 20000; % [假设值，待企业调研校准]
cfg.economic.h2PipeTransportCNYPerKgWithdrawn = 1.5; % [假设值，待企业调研校准]
cfg.economic.h2ShipTransportCNYPerKgWithdrawn = 3.0; % [假设值，待企业调研校准]
cfg.economic.h2PowerVariableCNYPerMWh = 30; % [假设值，待企业调研校准]
cfg.economic.cableVariableOMCNYPerMWhReceived = 0; % [假设值，待企业调研校准]
cfg.economic.computeVariableOMCNYPerMWhCS = 0; % [假设值，待企业调研校准]
cfg.economic.bessTerminalValueCNYPerMWh = 347; % [假设值，待企业调研校准]
cfg.economic.h2InventoryTerminalValueCNYPerKg = 28.36; % [假设值，待企业调研校准]
cfg.economic.electricityPriceCNYPerMWhReceived = 347; % public market scenario anchor
cfg.economic.hydrogenPriceCNYPerKgDelivered = 28.36; % public market scenario anchor
cfg.economic.computePriceCNYPerMWhCS = 500; % [假设值，待企业调研校准]
cfg.economic.marineServiceValueCNYPerMWh = 300; % [假设值，待企业调研校准]
cfg.economic.internalUnservedPenaltyCNYPerMWh = 50000; % [假设值，待企业调研校准]
cfg.economic.marineUnservedPenaltyCNYPerMWh = 10000; % [假设值，待企业调研校准]
cfg.economic.computeBaseUnservedPenaltyCNYPerMWh = 10000; % [假设值，待SLA校准]

cfg.environment.sourceLifecycleKgCO2ePerMWhUsed = 15; % [假设值，待LCA清单校准]
cfg.environment.bessThroughputKgCO2ePerMWh = 5; % [假设值，待LCA清单校准]
cfg.environment.hydrogenNonElectricKgCO2ePerKgProduced = 0; % [假设值，待LCA清单校准]
cfg.environment.h2ShipKgCO2ePerKgWithdrawn = 0; % [假设值，待航次校准]
cfg.environment.h2PipeKgCO2ePerKgWithdrawn = 0; % [假设值，待管输校准]
cfg.environment.h2PowerNonFuelKgCO2ePerMWh = 0; % [假设值，待LCA清单校准]
cfg.environment.electricityBaselineKgCO2ePerMWhReceived = 500; % [假设值，待基准情景校准]
cfg.environment.hydrogenBaselineKgCO2ePerKgDelivered = 10; % [假设值，待基准情景校准]
cfg.environment.computeBaselineKgCO2ePerMWhCS = 500; % [假设值，待基准情景校准]
cfg.environment.marineBaselineKgCO2ePerMWh = 500; % [假设值，待基准情景校准]
end
