function out = marine_source_hub_v3(sources,ports,storage,cfg)
%MARINE_SOURCE_HUB_V3 Compatibility orchestrator for Chapters 4.3 and 4.4.
% The implementation remains separated into aggregation, metrics and bus
% conservation so that storage and EMS can be replaced independently.

if nargin<3, storage=struct; end
if nargin<4, cfg=struct; end
src=source_aggregation_4_3_v3(sources,cfg);
bus=bus_balance_4_4_v3(src,ports,storage);

metrics=[];
if isfield(cfg,'capacity') && isfield(cfg,'metricWindowsSeconds') && ...
        isfield(cfg,'lowOutputFraction')
    metrics=source_complementarity_metrics_v3(src.time,src.perSource.actual, ...
        src.perSource.qualityFlag,cfg.capacity,cfg.metricWindowsSeconds, ...
        cfg.lowOutputFraction);
end
src.metrics=metrics;
coupling=struct( ...
    'sourceToBus4_4',src.interface.toBus4_4, ...
    'sourceBoundaryToStorage4_5',src.interface.toStorage4_5, ...
    'sourceBoundaryToEMS4_8_4_9',src.interface.toEMS4_8_4_9, ...
    'busToStorage4_5',struct( ...
        'pRequired',bus.balance.storageRequired, ...
        'scenarioRequired',bus.balance.netLoadResidualScenario), ...
    'storageToBus4_4',struct( ...
        'actualProvided',bus.balance.storageActualProvided, ...
        'pActual',bus.balance.storageActual));
out=struct('source',src,'bus',bus,'metrics',metrics,'interface',coupling);
end
