function cfg = common_config_4_2(caseMode, savePath)
%COMMON_CONFIG_4_2 Chapter 4 common configuration and interface contract.
%
% cfg = common_config_4_2('interface_smoke') returns a complete numerical
% interface test case. Every numerical value in this mode is an assumption
% and must not be used for engineering/economic conclusions.
%
% cfg = common_config_4_2('engineering_base') returns the frozen schema with
% unresolved P0 engineering values set to NaN. It is expected to fail strict
% validation until the project team signs the 4.1 freeze table.
%
% cfg = common_config_4_2(caseMode, savePath) also saves cfg to a MAT file.
%
% Units at the Chapter 4 optimization interface are MW, MWh, h, kg and kg/h.
% Existing 4.3 device models may remain in W/var/s, but must convert through
% their adapter before entering the common interface.

if nargin < 1 || isempty(caseMode)
    caseMode = 'interface_smoke';
end
if nargin < 2
    savePath = '';
end
caseMode = validatestring(caseMode, {'interface_smoke','engineering_base'});

cfg = struct;
cfg.meta = struct( ...
    'schemaId','BLUE_HUB_CH4_SCHEMA_V2', ...
    'schemaVersion','2.0.0', ...
    'schemaFrozen',true, ...
    'caseId','common_case_v2', ...
    'caseMode',caseMode, ...
    'parameterVersion',[caseMode '_v2'], ...
    'status','FROZEN_INTERFACE', ...
    'timezone','Asia/Shanghai', ...
    'intervalConvention','[t,t+dt)', ...
    'parameterNotice','[ASSUMPTION - CALIBRATE WITH OEM/PROJECT DATA]');

cfg.contract = struct( ...
    'schemaAuthority','4.2', ...
    'boundaryAuthority','4.1', ...
    'dispatchOwner','4.9', ...
    'actualBalanceOwner','4.4', ...
    'evaluationOwner','4.8', ...
    'noSilentDefaultsInIntegratedRun',true, ...
    'noCrossModuleStateMutation',true, ...
    'actualOnlyInBusLedger',true, ...
    'requestedAcceptedActualRequired',true, ...
    'moduleExecutionOrder',{{'4.3/4.5/4.6/4.7_BOUNDARY', ...
        '4.9_REQUEST','4.3/4.5/4.6/4.7_RESPONSE','4.4_ACTUAL_LEDGER', ...
        'STATE_COMMIT','4.8_EVALUATION'}});

cfg.boundary = struct( ...
    'offshoreSourceIncluded',true, ...
    'commonBusIncluded',true, ...
    'bessHydrogenIncluded',true, ...
    'subseaComputeIncluded',true, ...
    'outputChannelsIncluded',true, ...
    'electricitySettlementPoint','MP-CABLE-RECEIVE', ...
    'hydrogenSettlementPoint','MP-H2-DELIVERY', ...
    'computeSettlementPoint','MP-COMPUTE-DELIVERY');

cfg.time = struct( ...
    'sourceRawStepH',5/60, ...
    'dispatchStepH',1, ...
    'intradayCheckStepH',0.25, ...
    'dynamicMaxStepS',1, ...
    'planningStepYear',1, ...
    'dispatchHorizonH',168, ...
    'annualHorizonH',8760, ...
    'aggregationRulePower','energy_conserving_mean', ...
    'aggregationRuleEnergy','sum', ...
    'aggregationRuleState','end_of_interval', ...
    'stateTimestampConvention','stateOut(t)=end_of_[t,t+dt)', ...
    'powerTimestampConvention','power(t)=average_over_[t,t+dt)', ...
    'eventInterpolationAllowed',false);

cfg.units = struct( ...
    'power','MW','reactivePower','Mvar','energy','MWh','time','h','mass','kg', ...
    'massFlow','kg/h','priceElectricity','CNY/MWh', ...
    'priceHydrogen','CNY/kg','emission','kgCO2e', ...
    'devicePower','W','deviceReactivePower','var','deviceTime','s', ...
    'WtoMW',1e-6,'MWtoW',1e6,'secondsToHours',1/3600);

cfg.shape = struct( ...
    'scalarSeries','N-by-1', ...
    'sourceSeries','N-by-S', ...
    'scenarioSeries','N-by-K', ...
    'sourceScenarioSeries','N-by-S-by-K', ...
    'scenarioProbability','1-by-K', ...
    'sourceId','1-by-S', ...
    'timeAxis','N-by-1');

cfg.meter = struct( ...
    'device','MP-DEVICE', ...
    'sourcePOI','MP-03-SOURCE-POI', ...
    'commonBus','MP-04-COMMON-BUS', ...
    'cableSend','MP-CABLE-SEND', ...
    'cableReceive','MP-CABLE-RECEIVE', ...
    'dcFacility','MP-DC-FACILITY', ...
    'electrolyzer','MP-ELECTROLYZER', ...
    'hydrogenDelivery','MP-H2-DELIVERY', ...
    'computeDelivery','MP-COMPUTE-DELIVERY');

cfg.sign = struct( ...
    'generationInjectionPositive',true, ...
    'storageDischargeInjectionPositive',true, ...
    'gridImportInjectionPositive',true, ...
    'loadMagnitudeNonnegative',true, ...
    'storageChargeMagnitudeNonnegative',true, ...
    'storageDischargeMagnitudeNonnegative',true, ...
    'exportSendMagnitudeNonnegative',true, ...
    'electrolyzerMagnitudeNonnegative',true, ...
    'computeFacilityMagnitudeNonnegative',true, ...
    'marineLoadMagnitudeNonnegative',true, ...
    'spillMagnitudeNonnegative',true, ...
    'unservedMagnitudeNonnegative',true, ...
    'storageNetDefinition','pBessDischargeMW-pBessChargeMW', ...
    'dispatchChain',{{'requested','accepted','actual'}});

cfg.enums = struct;
cfg.enums.availabilityState = {'AVAILABLE','DERATED','STOPPED','MAINTENANCE','FAULT'};
cfg.enums.dispatchStatus = {'NOT_RUN','OPTIMAL','FEASIBLE','INFEASIBLE','FALLBACK'};
cfg.enums.packetPhase = {'BOUNDARY','REQUEST','RESPONSE','LEDGER','EVALUATION'};
cfg.enums.qualityFlagMeaning = {'true=valid','false=invalid_or_missing'};
cfg.enums.constraintCode = {'NONE','RESOURCE','ENVIRONMENT','FAULT', ...
    'MAINTENANCE','RAMP','EMS_CURTAILMENT','DATA_QUALITY','CAPACITY', ...
    'STATE','INVENTORY','SLA','DELIVERY_CHANNEL'};

cfg.site = struct( ...
    'siteId','SITE_REF_V1', ...
    'latitudeDeg',NaN, ...
    'longitudeDeg',NaN, ...
    'waterDepthM',NaN, ...
    'distanceToShoreKm',NaN, ...
    'landingPointId','LANDING_REF_V1', ...
    'isVirtualReferenceSite',true);

cfg.source = struct;
cfg.source.meterPoint = cfg.meter.sourcePOI;
cfg.source.sourceId = {'WIND_BASELINE','PV_BASELINE','TIDAL_BASELINE'};
cfg.source.sourceType = {'wind','pv','tidal'};
cfg.source.windCapacityMW = NaN;
cfg.source.pvCapacityMW = NaN;
cfg.source.tidalCapacityMW = NaN;
cfg.source.totalCapacityMW = NaN;
cfg.source.waveReserved = true;
cfg.source.availabilitySeriesRequired = true;
cfg.source.sharedResourceSeriesAcrossCases = true;
cfg.source.collectionLossOwner = '4.3';
cfg.source.auxiliaryCalculationOwner = '4.3';
cfg.source.auxiliaryAccountingOwner = '4.4';

cfg.commonBus = struct( ...
    'meterPoint',cfg.meter.commonBus, ...
    'balanceOwner','4.4', ...
    'balanceToleranceMW',1e-6, ...
    'commonAuxMW',NaN, ...
    'postPOILossMW',NaN, ...
    'allowGridImport',false, ...
    'allowEmergencyGridImport',false, ...
    'spillDecisionOwner','4.9', ...
    'unservedDecisionOwner','4.9', ...
    'residualCalculationOwner','4.4', ...
    'implicitClosureAllowed',false);

cfg.bess = struct( ...
    'owner','4.5', ...
    'powerMW',NaN, ...
    'energyMWh',NaN, ...
    'chargeMaxMW',NaN, ...
    'dischargeMaxMW',NaN, ...
    'etaCharge',NaN, ...
    'etaDischarge',NaN, ...
    'socMin',NaN, ...
    'socMax',NaN, ...
    'socInitial',NaN, ...
    'terminalRule','cyclic', ...
    'simultaneousChargeDischargeAllowed',false);

cfg.hydrogen = struct( ...
    'ownerInternal','4.5', ...
    'ownerDelivery','4.7', ...
    'inventoryCommitOwner','4.5', ...
    'deliverySequence','4.5_AVAILABLE_THEN_4.7_ACTUAL_THEN_4.5_COMMIT', ...
    'electrolyzerMeterPoint',cfg.meter.electrolyzer, ...
    'electrolyzerRatedMW',NaN, ...
    'electrolyzerMinMW',NaN, ...
    'secKWhPerKg',NaN, ...
    'secIncludesBOP',true, ...
    'secBoundary','FACILITY_TOTAL_INCLUDES_BOP_PURIFICATION_COMPRESSION', ...
    'storageMaxKg',NaN, ...
    'storageInitialKg',NaN, ...
    'terminalRule','cyclic_or_minimum', ...
    'waterLPerKg',NaN, ...
    'pipeCapacityKgPerH',NaN, ...
    'shipCapacityKgPerH',NaN, ...
    'pipeLossFraction',NaN, ...
    'shipLossFraction',NaN);

cfg.compute = struct( ...
    'ownerInternal','4.6', ...
    'ownerDelivery','4.7', ...
    'queueCommitOwner','4.6', ...
    'facilityMeterPoint',cfg.meter.dcFacility, ...
    'facilityMaxMW',NaN, ...
    'facilityMinMW',NaN, ...
    'itCapacityMW',NaN, ...
    'pueMin',NaN, ...
    'auxMinMW',NaN, ...
    'queueInitialMWhCS',NaN, ...
    'queueTerminalRule','rolling_or_cyclic', ...
    'fiberServiceCapacityMWhCSPerH',NaN, ...
    'fiberBandwidthGbps',NaN, ...
    'fiberLatencyMs',NaN);

cfg.output = struct( ...
    'owner','4.7', ...
    'cableScenario','GREENFIELD_NEW', ...
    'cableSendCapacityMW',NaN, ...
    'gridAcceptMaxMW',NaN, ...
    'cableDistanceKm',NaN, ...
    'cableLossFraction',NaN, ...
    'marineBaseLoadMW',NaN, ...
    'marineDesalLoadMW',NaN, ...
    'marineEquipmentLoadMW',NaN, ...
    'marineFlexibleFraction',NaN);

cfg.owner = struct( ...
    'sourcePhysics','4.3', ...
    'sourceCollectionLoss','4.3', ...
    'commonBusLedger','4.4', ...
    'commonAuxAndPostPOILoss','4.4', ...
    'bessState','4.5', ...
    'hydrogenProductionAndInventory','4.5', ...
    'computePowerAndQueue','4.6', ...
    'electricityHydrogenComputeDelivery','4.7', ...
    'marineDemandResponse','4.7', ...
    'objectiveEvaluation','4.8', ...
    'crossModuleDispatch','4.9');

cfg.economics = struct( ...
    'currency','CNY', ...
    'currencyBaseYear',2026, ...
    'commercialOperationYear','Y0', ...
    'analysisLifeYear',25, ...
    'taxBasis','UNDECIDED', ...
    'discountRate',NaN, ...
    'constructionPeriodYear',NaN, ...
    'sharedAssetAllocationMethod','UNDECIDED');

cfg.lca = struct( ...
    'electricityFunctionalUnit','1 MWh delivered at MP-CABLE-RECEIVE', ...
    'hydrogenFunctionalUnit','1 kg H2 delivered at MP-H2-DELIVERY', ...
    'computeFunctionalUnit','1 MWh-CS delivered at MP-COMPUTE-DELIVERY', ...
    'allocationMethod','UNDECIDED', ...
    'replacementBaseline','UNDECIDED');

cfg.scenario = struct( ...
    'randomSeed',20260716, ...
    'sameSourceAvailabilityAcrossAlternatives',true, ...
    'sameResourceSeriesAcrossAlternatives',true, ...
    'sameSiteAcrossAlternatives',true, ...
    'sameSourceCapacityAcrossOperatingAlternatives',true, ...
    'primaryCableComparison','GREENFIELD_NEW', ...
    'auxiliaryCableComparison','EXISTING_SUNK_CAPEX');

cfg.interface = struct;
cfg.interface.commonMeta = {'schemaId','schemaVersion','caseId','caseMode', ...
    'parameterVersion','moduleId','phase'};
cfg.interface.commonAxis = {'timeH','dtH','scenarioId','scenarioProbability'};
cfg.interface.commonQuality = {'qualityFlag','dataSourceType','calibrationVersion'};
cfg.interface.commonDispatchPort = {'requestedMW','acceptedMW','actualMW', ...
    'minMW','maxMW','upCapabilityMW','downCapabilityMW','constraintCode', ...
    'operatingState','meterPoint','qualityFlag'};
cfg.interface.sourceToBus = {'pSourceActualMW','pSourceAuxLoadMW', ...
    'pCollectionLossMW','collectionLossAlreadyDeducted','qualityFlag','meterPoint'};
cfg.interface.bessToBus = {'pBessChargeActualMW','pBessDischargeActualMW', ...
    'bessSOC','bessEnergyMWh','bessConstraintCode'};
cfg.interface.hydrogenToBus = {'pElectrolyzerActualMW','h2ProductionKg', ...
    'h2InventoryKg','h2AvailableForDeliveryKg','h2InternalConstraintCode'};
cfg.interface.computeToBus = {'pDCFacilityActualMW','pITActualMW', ...
    'pDCAuxActualMW','computeQueueMWhCS','computeConstraintCode'};
cfg.interface.outputToBus = {'pExportSendActualMW','pMarineActualMW', ...
    'pGridImportActualMW','pCableReceiveMW','cableLossMW','h2DeliveredKg', ...
    'computeDeliveredMWhCS','marineUnservedMW'};
cfg.interface.busLedger = {'pBusResidualMW','pSpillActualMW','pUnservedMW', ...
    'pCommonAuxMW','pPostPOILossMW','balanceStatus'};

cfg.p0 = struct( ...
    'siteDecisionClosed',false, ...
    'capacityDecisionClosed',false, ...
    'emergencyImportDecisionClosed',false, ...
    'economicBoundaryDecisionClosed',false, ...
    'lcaBoundaryDecisionClosed',false, ...
    'projectTeamSigned',false);

if strcmp(caseMode,'interface_smoke')
    cfg = apply_smoke_values(cfg);
end

if ~isempty(savePath)
    assert(ischar(savePath) || (isstring(savePath) && isscalar(savePath)), ...
        'savePath must be scalar text.');
    savePath = char(savePath);
    save(savePath,'cfg');
end
end

function cfg = apply_smoke_values(cfg)
% Existing demonstration values only; not an engineering baseline.
cfg.site.distanceToShoreKm = 200;
cfg.source.windCapacityMW = 34;
cfg.source.pvCapacityMW = 4;
cfg.source.tidalCapacityMW = 2;
cfg.source.totalCapacityMW = 40;
cfg.commonBus.commonAuxMW = 0.25;
cfg.commonBus.postPOILossMW = 0.20;
cfg.bess.powerMW = 50;
cfg.bess.energyMWh = 100;
cfg.bess.chargeMaxMW = 50;
cfg.bess.dischargeMaxMW = 50;
cfg.bess.etaCharge = 0.95;
cfg.bess.etaDischarge = 0.95;
cfg.bess.socMin = 0.10;
cfg.bess.socMax = 0.90;
cfg.bess.socInitial = 0.50;
cfg.hydrogen.electrolyzerRatedMW = 100;
cfg.hydrogen.electrolyzerMinMW = 20;
cfg.hydrogen.secKWhPerKg = 56.77;
cfg.hydrogen.storageMaxKg = 72000;
cfg.hydrogen.storageInitialKg = 30000;
cfg.hydrogen.waterLPerKg = 15.9;
cfg.hydrogen.pipeCapacityKgPerH = 1800;
cfg.hydrogen.shipCapacityKgPerH = 1200;
cfg.hydrogen.pipeLossFraction = 0.01;
cfg.hydrogen.shipLossFraction = 0.02;
cfg.compute.facilityMaxMW = 120;
cfg.compute.facilityMinMW = 10;
cfg.compute.itCapacityMW = 100;
cfg.compute.pueMin = 1.10;
cfg.compute.auxMinMW = 1;
cfg.compute.queueInitialMWhCS = 0;
cfg.compute.fiberServiceCapacityMWhCSPerH = 120;
cfg.compute.fiberBandwidthGbps = 800;
cfg.compute.fiberLatencyMs = 20;
cfg.output.cableSendCapacityMW = 700;
cfg.output.gridAcceptMaxMW = 450;
cfg.output.cableDistanceKm = 200;
cfg.output.cableLossFraction = 0.08;
cfg.output.marineBaseLoadMW = 8;
cfg.output.marineDesalLoadMW = 4;
cfg.output.marineEquipmentLoadMW = 6;
cfg.output.marineFlexibleFraction = 0.30;
cfg.economics.discountRate = 0.08;
cfg.economics.constructionPeriodYear = 3;
end
