function T=v4_capacity_audit_4_8(cfg,p43,p45,p46,p47,p49,assetLedger)
%V4_CAPACITY_AUDIT_4_8 Installed/requested/actual capacity consistency table.
dt=cfg.time.dispatchStepH;
N=numel(p43.axis.timeH);
sourceActual=double(p43.service.actualBySourceMW);
sourceInstalled=[cfg.source.windCapacityMW;cfg.source.pvCapacityMW; ...
    cfg.source.tidalCapacityMW];

assetName=["floatingWind";"marineFloatingPV";"tidalStream";"BESS"; ...
    "PEMElectrolyzer";"hydrogenStorage";"subseaCompute"; ...
    "powerExportCable";"converterAndSubstation";"fiberCable"];
unit=["MW";"MW";"MW";"MW";"MW";"kg";"MW";"MW";"MW";"MWh-CS/h"];
interfaceLimit=[sourceInstalled;cfg.bess.powerMW; ...
    cfg.hydrogen.electrolyzerRatedMW;cfg.hydrogen.storageMaxKg; ...
    cfg.compute.facilityMaxMW;cfg.output.cableSendCapacityMW; ...
    cfg.output.cableSendCapacityMW;cfg.compute.fiberServiceCapacityMWhCSPerH];
installedCapacity=interfaceLimit;
secondaryInstalledCapacity=nan(10,1);
secondaryUnit=repmat("",10,1);
if isfield(cfg,'capacity') && isfield(cfg.capacity,'installed')
    ci=cfg.capacity.installed;
    h2Design=v4_hydrogen_storage_sizing_4_8(cfg, ...
        max([cfg.hydrogen.storageInitialKg;double(p45.state.h2InventoryKg(:))]));
    installedCapacity=[ci.windMW;ci.pvMW;ci.tidalMW;ci.bessPowerMW; ...
        ci.electrolyzerMW;h2Design.installedKg; ...
        ci.computeFacilityMW;ci.powerCableMW;ci.powerCableMW; ...
        cfg.compute.fiberServiceCapacityMWhCSPerH];
    secondaryInstalledCapacity(4)=ci.bessEnergyMWh;
    secondaryUnit(4)="MWh";
    secondaryInstalledCapacity(7)=ci.computeITMW;
    secondaryUnit(7)="MW-IT";
end

dispatchRequestPeak=[nan(3,1); ...
    max([max(p49.service.bessChargeRequestedMW), ...
        max(p49.service.bessDischargeRequestedMW)]); ...
    max(p49.service.electrolyzerRequestedMW); ...
    max(p49.state.h2InventoryPlanKg); ...
    max(p49.service.computeRequestedMW); ...
    max(p49.service.exportRequestedMW); ...
    max(p49.service.exportRequestedMW); ...
    max(p46.service.computeServedMWhCS)];
actualPeak=[max(sourceActual,[],1)'; ...
    max([max(p45.ports.bessCharge.actualMW), ...
        max(p45.ports.bessDischarge.actualMW)]); ...
    max(p45.ports.electrolyzer.actualMW); ...
    max([cfg.hydrogen.storageInitialKg;double(p45.state.h2InventoryKg(:))]); ...
    max(p46.ports.dcFacility.actualMW); ...
    max(p47.ports.exportSend.actualMW); ...
    max(p47.ports.exportSend.actualMW); ...
    max(p47.service.computeDeliveredMWhCS)];
periodQuantity=[sum(sourceActual,1)'*dt; ...
    sum(p45.ports.bessDischarge.actualMW)*dt; ...
    sum(p45.ports.electrolyzer.actualMW)*dt; ...
    max([cfg.hydrogen.storageInitialKg;double(p45.state.h2InventoryKg(:))]); ...
    sum(p46.ports.dcFacility.actualMW)*dt; ...
    sum(p47.ports.exportSend.actualMW)*dt; ...
    sum(p47.ports.exportSend.actualMW)*dt; ...
    sum(p47.service.computeDeliveredMWhCS)];

equivalentFullLoadHours=nan(10,1);
periodUtilizationFraction=nan(10,1);
peakUtilizationFraction=nan(10,1);
for k=1:10
    if installedCapacity(k)>0
        peakUtilizationFraction(k)=min(1,actualPeak(k)/installedCapacity(k));
        if k==6
            periodUtilizationFraction(k)=peakUtilizationFraction(k);
        else
            equivalentFullLoadHours(k)=periodQuantity(k)/installedCapacity(k);
            periodUtilizationFraction(k)=min(1, ...
                equivalentFullLoadHours(k)/(N*dt));
        end
    end
end
idleFraction=1-periodUtilizationFraction;

[found,loc]=ismember(assetName,string(assetLedger.assetName));
assert(all(found),'Lifecycle asset ledger and capacity audit asset names differ.');
scenarioEnabled=logical(assetLedger.scenarioEnabled(loc));
enabled=logical(assetLedger.enabled(loc));
capexCNY=double(assetLedger.capexCNY(loc));
totalCapex=sum(capexCNY);
capexShare=zeros(10,1);
if totalCapex>0, capexShare=capexCNY/totalCapex; end
capacityStatus=repmat("MATCHED_OR_SCENARIO_DEPENDENT",10,1);
capacityStatus(~scenarioEnabled)="DISABLED_ZERO_COST";
capacityStatus(enabled & installedCapacity<=0)="ENABLED_WITH_ZERO_INSTALLED_CAPACITY";
capacityStatus(enabled & idleFraction>0.90)="LOW_PERIOD_UTILIZATION";
capacityStatus(6)=conditional_status(scenarioEnabled(6),installedCapacity(6));

designDetail=repmat("",10,1);
designDetail(4)="power/energy pair";
if exist('h2Design','var')
    designDetail(6)=sprintf( ...
        'max(process buffer %.3f kg at %.2f h, committed inventory %.3f kg)', ...
        h2Design.minimumProcessBufferKg,h2Design.minimumProcessBufferHours, ...
        h2Design.peakCrossTimeInventoryKg);
else
    designDetail(6)="process buffer plus committed inventory";
end
designDetail(7)=sprintf('%d units x %.6f MW facility', ...
    cfg.capacity.installed.computeUnitCount, ...
    cfg.capacity.installed.computeUnitFacilityMaxMW);
if isfield(cfg,'capacity') && isfield(cfg.capacity,'installed')
    designDetail(8)=sprintf('%.0f kV; %.0f km', ...
        cfg.capacity.installed.powerCableVoltageKV, ...
        cfg.capacity.installed.powerCableDistanceKm);
    designDetail(9)=designDetail(8);
end
designDetail(10)="fiber delivery channel";

T=table(assetName,scenarioEnabled,enabled,unit,interfaceLimit,installedCapacity, ...
    secondaryInstalledCapacity,secondaryUnit,dispatchRequestPeak,actualPeak, ...
    periodQuantity,equivalentFullLoadHours,periodUtilizationFraction, ...
    peakUtilizationFraction,idleFraction,capexCNY,capexShare, ...
    capacityStatus,designDetail);
end

function status=conditional_status(enabled,installed)
if ~enabled
    status="DISABLED_ZERO_COST";
elseif installed<=0
    status="DISABLED_ZERO_COST";
else
    status="PROCESS_BUFFER_OR_DYNAMIC_INVENTORY_SIZING";
end
end
