function seasonal=v4_seasonal_hydrogen_storage_4_5(cfg,timeH,availableElectrolyzerMW,h2DemandKg,options)
%V4_SEASONAL_HYDROGEN_STORAGE_4_5 Continuous long-duration H2 validation.
%
% This is a deterministic mechanism test, not a site resource forecast or
% an investment-sizing recommendation. It preserves every hourly state
% across the full horizon and therefore can expose multi-week/seasonal
% inventory transfer that repeated independent 24 h windows cannot.

if nargin<5 || isempty(options), options=struct; end
timeH=double(timeH(:)); N=numel(timeH);
availableElectrolyzerMW=series(availableElectrolyzerMW,N, ...
    'availableElectrolyzerMW');
h2DemandKg=series(h2DemandKg,N,'h2DemandKg');

policy=string(option_value(options,'dispatchPolicy','must_take_available'));
switch lower(policy)
    case "must_take_available"
        electrolyzerRequestMW=availableElectrolyzerMW;
    otherwise
        error('Unsupported seasonal dispatch policy %s.',policy);
end

request=struct( ...
    'bessChargeMW',zeros(N,1), ...
    'bessDischargeMW',zeros(N,1), ...
    'electrolyzerMW',electrolyzerRequestMW, ...
    'electrolyzerAvailable',true(N,1));
state0=option_value(options,'state0',struct( ...
    'bessEnergyMWh',cfg.bess.socInitial*cfg.bess.energyMWh, ...
    'h2InventoryKg',cfg.hydrogen.storageInitialKg));

coreOptions=struct( ...
    'strictWithdrawal',false, ...
    'electrolyzerMode',option_value(options,'electrolyzerMode','modular'), ...
    'electrolyzerModuleRatedMW', ...
        option_value(options,'electrolyzerModuleRatedMW',20), ...
    'electrolyzerModuleMinMW', ...
        option_value(options,'electrolyzerModuleMinMW',4), ...
    'electrolyzerModuleCount', ...
        option_value(options,'electrolyzerModuleCount',5), ...
    'h2StorageLossFractionPerH', ...
        option_value(options,'h2StorageLossFractionPerH', ...
        cfg.hydrogen.storageLossFractionPerH), ...
    'bessTerminalRule','cyclic', ...
    'bessTerminalTarget',state0.bessEnergyMWh, ...
    'h2TerminalRule',option_value(options,'h2TerminalRule','cyclic'), ...
    'h2TerminalTarget',option_value(options,'h2TerminalTarget', ...
        state0.h2InventoryKg), ...
    'tolerance',option_value(options,'tolerance',1e-6), ...
    'enforceTerminal',false);
if isfield(options,'dtH'), coreOptions.dtH=options.dtH; end

response=v4_storage_hydrogen_core_4_5( ...
    cfg,timeH,request,state0,h2DemandKg,coreOptions);
netStoredKg=response.h2ProductionKg-response.h2WithdrawnKg ...
    -response.h2StorageLossKg;
isSeasonalRelease=response.h2InventoryKg>1e-6 & netStoredKg<0;
longestReleaseH=longest_duration(isSeasonalRelease,response.dtH);

seasonal=struct;
seasonal.response=response;
seasonal.availableElectrolyzerMW=availableElectrolyzerMW;
seasonal.electrolyzerCurtailmentMW=max(0, ...
    availableElectrolyzerMW-response.pElectrolyzerMW);
seasonal.h2DemandKg=h2DemandKg;
seasonal.h2DeliveredKg=response.h2WithdrawnKg;
seasonal.h2UnservedKg=response.h2WithdrawalShortfallKg;
seasonal.horizonH=sum(response.dtH);
seasonal.maxInventoryKg=max(response.h2InventoryKg);
seasonal.minInventoryKg=min(response.h2InventoryKg);
seasonal.requiredWorkingInventoryKg=max(response.h2InventoryKg) ...
    -min(response.h2InventoryKg);
seasonal.longestContinuousReleaseH=longestReleaseH;
seasonal.crossWeekDemonstrated=longestReleaseH>=168;
seasonal.seasonalMechanismDemonstrated=longestReleaseH>=100;
seasonal.terminalOK=response.terminal.h2OK;
seasonal.deliveryOK=sum(response.h2WithdrawalShortfallKg)<=1e-6;
seasonal.feasible=seasonal.terminalOK && seasonal.deliveryOK;
seasonal.audit=struct( ...
    'timeTreatment','CONTINUOUS_FULL_HORIZON_NO_PERIOD_RESET', ...
    'dispatchPolicy',char(policy), ...
    'scenarioStatus','[assumption, mechanism test only; replace with continuous 4.3 site series]', ...
    'capacityStatus','[assumption, pending storage technology and enterprise calibration]', ...
    'durationDefinitionSourceType','national laboratory publication (NREL)', ...
    'claimBoundary',['Demonstrates mathematical inventory transfer only; ' ...
        'does not establish pressure vessel/cavern, leakage, safety or cost feasibility.']);
end

function x=series(x,N,name)
if isscalar(x), x=repmat(double(x),N,1); else, x=double(x(:)); end
assert(numel(x)==N && all(isfinite(x)) && all(x>=0), ...
    '%s must be nonnegative scalar or N-by-1.',name);
end

function value=option_value(options,name,defaultValue)
if isfield(options,name), value=options.(name); else, value=defaultValue; end
end

function duration=longest_duration(mask,dtH)
duration=0; running=0;
for k=1:numel(mask)
    if mask(k)
        running=running+dtH(k);
        duration=max(duration,running);
    else
        running=0;
    end
end
end
