function mdl = v5_build_problem(cfg,in)
%V5_BUILD_PROBLEM Build the C4/V5 hourly dispatch MILP.
%
% Boundary:
%   - Source availability is supplied by module 4.3 at MP-03.
%   - This model performs interval-average energy scheduling only.
%   - Voltage/frequency waveforms, current limiting, fault ride-through and
%     black start are acceptance gates outside this hourly MILP.

N=numel(in.timeH);
dt=cfg.time.dispatchStepH;
Mely=cfg.hydrogen.moduleCount;

problem=optimproblem('ObjectiveSense','minimize');
v=struct;

v.pSourceUsedMW=optimvar('pSourceUsedMW',N,1, ...
    'LowerBound',0,'UpperBound',in.pSourceAvailableMW);

v.pBessChargeMW=optimvar('pBessChargeMW',N,1,'LowerBound',0);
v.pBessDischargeMW=optimvar('pBessDischargeMW',N,1,'LowerBound',0);
v.bessEnergyMWh=optimvar('bessEnergyMWh',N,1,'LowerBound',0);
v.uBessCharge=optimvar('uBessCharge',N,1,'Type','integer', ...
    'LowerBound',0,'UpperBound',double(in.availability.bess>0));
v.uBessDischarge=optimvar('uBessDischarge',N,1,'Type','integer', ...
    'LowerBound',0,'UpperBound',double(in.availability.bess>0));

v.pElectrolyzerMW=optimvar('pElectrolyzerMW',N,1,'LowerBound',0);
v.nElectrolyzerOnline=optimvar('nElectrolyzerOnline',N,1, ...
    'Type','integer','LowerBound',0, ...
    'UpperBound',floor(Mely*in.availability.electrolyzer));
v.nElectrolyzerStart=optimvar('nElectrolyzerStart',N,1, ...
    'Type','integer','LowerBound',0,'UpperBound',Mely);
v.uElectrolyzerIncreasing=optimvar('uElectrolyzerIncreasing',N,1, ...
    'Type','integer','LowerBound',0,'UpperBound',1);
v.h2ProducedKg=optimvar('h2ProducedKg',N,1,'LowerBound',0);
v.h2InventoryKg=optimvar('h2InventoryKg',N,1,'LowerBound',0);
v.h2PipeWithdrawnKg=optimvar('h2PipeWithdrawnKg',N,1,'LowerBound',0);
v.h2ShipWithdrawnKg=optimvar('h2ShipWithdrawnKg',N,1,'LowerBound',0);

v.pH2PowerMW=optimvar('pH2PowerMW',N,1,'LowerBound',0);
v.h2ToPowerConsumedKg=optimvar('h2ToPowerConsumedKg',N,1, ...
    'LowerBound',0);
v.uH2Power=optimvar('uH2Power',N,1,'Type','integer', ...
    'LowerBound',0,'UpperBound',double(in.availability.h2Power>0));

v.pComputeBaseServedMW=optimvar('pComputeBaseServedMW',N,1, ...
    'LowerBound',0);
v.pComputeFlexibleMW=optimvar('pComputeFlexibleMW',N,1, ...
    'LowerBound',0);
v.pComputeBaseUnservedMW=optimvar('pComputeBaseUnservedMW',N,1, ...
    'LowerBound',0);
v.nComputeOnline=optimvar('nComputeOnline',N,1,'Type','integer', ...
    'LowerBound',0, ...
    'UpperBound',floor(cfg.compute.moduleCount*in.availability.compute));

v.pCableSendMW=optimvar('pCableSendMW',N,1,'LowerBound',0);
v.pCableReceivedMW=optimvar('pCableReceivedMW',N,1,'LowerBound',0);
v.pMarineServedMW=optimvar('pMarineServedMW',N,1,'LowerBound',0);
v.pMarineUnservedMW=optimvar('pMarineUnservedMW',N,1,'LowerBound',0);
v.pInternalUnservedMW=optimvar('pInternalUnservedMW',N,1, ...
    'LowerBound',0);
v.uCurtailmentMode=optimvar('uCurtailmentMode',N,1, ...
    'Type','integer','LowerBound',0,'UpperBound',1);

% Source use and exact bus ledger. Curtailment is the physical remainder.
problem.Constraints.busBalance = ...
    v.pSourceUsedMW+v.pBessDischargeMW+v.pH2PowerMW == ...
    v.pBessChargeMW+v.pElectrolyzerMW+ ...
    v.pComputeBaseServedMW+v.pComputeFlexibleMW+ ...
    v.pCableSendMW+v.pMarineServedMW+ ...
    (in.pInternalDemandMW-v.pInternalUnservedMW);
problem.Constraints.internalShortfall = ...
    v.pInternalUnservedMW<=in.pInternalDemandMW;
problem.Constraints.marineLedger = ...
    v.pMarineServedMW+v.pMarineUnservedMW==in.pMarineDemandMW;

% A common-bus interval cannot simultaneously curtail available source
% energy and report critical energy-not-served. Flexible compute that was
% never committed is not ENS and is intentionally excluded.
pCriticalUnservedMW=v.pInternalUnservedMW+v.pMarineUnservedMW+ ...
    v.pComputeBaseUnservedMW;
pCurtailmentMW=in.pSourceAvailableMW-v.pSourceUsedMW;
pCriticalDemandMW=in.pInternalDemandMW+in.pMarineDemandMW+ ...
    in.pComputeBaseDemandMW;
problem.Constraints.curtailmentModeUpper = ...
    pCurtailmentMW<=in.pSourceAvailableMW.*v.uCurtailmentMode;
problem.Constraints.criticalShortageModeUpper = ...
    pCriticalUnservedMW<= ...
    pCriticalDemandMW.*(1-v.uCurtailmentMode);

% BESS: end-of-interval energy, conversion losses and exclusive modes.
problem.Constraints.bessChargePower = ...
    v.pBessChargeMW<=cfg.bess.chargeMaxMW*v.uBessCharge;
problem.Constraints.bessChargeAvailability = ...
    v.pBessChargeMW<=cfg.bess.chargeMaxMW*in.availability.bess;
problem.Constraints.bessDischargePower = ...
    v.pBessDischargeMW<=cfg.bess.dischargeMaxMW*v.uBessDischarge;
% Symmetric hourly GFM reserve proxy. It preserves both upward injection
% headroom and downward absorption headroom. This is not a waveform-level
% frequency/voltage proof; dynamic acceptance remains mandatory.
pBessNetMW=v.pBessDischargeMW-v.pBessChargeMW;
problem.Constraints.bessGfmUpwardHeadroom = ...
    pBessNetMW+cfg.bess.gfmReservePowerMW*in.gfmRequired <= ...
    cfg.bess.dischargeMaxMW*in.availability.bess;
problem.Constraints.bessGfmDownwardHeadroom = ...
    -pBessNetMW+ ...
    cfg.bess.gfmAbsorptionReservePowerMW*in.gfmRequired <= ...
    cfg.bess.chargeMaxMW*in.availability.bess;
problem.Constraints.bessExclusive = ...
    v.uBessCharge+v.uBessDischarge<=1;
problem.Constraints.bessEnergyLower = ...
    v.bessEnergyMWh>= ...
    cfg.bess.socMin*cfg.bess.energyMWh+ ...
    cfg.bess.gfmReserveEnergyMWh*in.gfmRequired;
problem.Constraints.bessEnergyUpper = ...
    v.bessEnergyMWh<=cfg.bess.socMax*cfg.bess.energyMWh- ...
    cfg.bess.gfmAbsorptionReserveEnergyMWh*in.gfmRequired;
bessState=optimconstr(N,1);
bessState(1)=v.bessEnergyMWh(1)== ...
    cfg.bess.standingRetentionPerStep*in.initial.bessEnergyMWh+ ...
    cfg.bess.etaCharge*v.pBessChargeMW(1)*dt- ...
    v.pBessDischargeMW(1)*dt/cfg.bess.etaDischarge;
for t=2:N
    bessState(t)=v.bessEnergyMWh(t)== ...
        cfg.bess.standingRetentionPerStep*v.bessEnergyMWh(t-1)+ ...
        cfg.bess.etaCharge*v.pBessChargeMW(t)*dt- ...
        v.pBessDischargeMW(t)*dt/cfg.bess.etaDischarge;
end
problem.Constraints.bessState=bessState;
problem=add_terminal_constraint(problem,'bess',cfg.bess.terminalRule, ...
    v.bessEnergyMWh(N),in.initial.bessEnergyMWh, ...
    cfg.bess.terminalTargetSOC*cfg.bess.energyMWh);

% Modular electrolyzer and fixed-SEC hydrogen conversion.
problem.Constraints.electrolyzerModuleLower = ...
    v.pElectrolyzerMW>= ...
    cfg.hydrogen.moduleMinMW*v.nElectrolyzerOnline;
problem.Constraints.electrolyzerModuleUpper = ...
    v.pElectrolyzerMW<= ...
    cfg.hydrogen.moduleRatedMW*v.nElectrolyzerOnline;
problem.Constraints.electrolyzerPlantAvailability = ...
    v.pElectrolyzerMW<= ...
    cfg.hydrogen.electrolyzerRatedMW*in.availability.electrolyzer;
elyOnlineDelta=optimexpr(N,1);
elyOnlineDelta(1)=v.nElectrolyzerOnline(1)- ...
    in.initial.electrolyzerOnlineModules;
for t=2:N
    elyOnlineDelta(t)=v.nElectrolyzerOnline(t)- ...
        v.nElectrolyzerOnline(t-1);
end
% Exact positive-part linearization:
% nStart(t)=max(0,nOnline(t)-nOnline(t-1)).
% This prevents fictitious starts from consuming electricity without
% producing hydrogen when the start cost is zero or a non-economic
% objective is selected.
problem.Constraints.electrolyzerIncreaseSignUpper = ...
    elyOnlineDelta<=Mely*v.uElectrolyzerIncreasing;
problem.Constraints.electrolyzerIncreaseSignLower = ...
    elyOnlineDelta>=-Mely*(1-v.uElectrolyzerIncreasing);
problem.Constraints.electrolyzerStartLower = ...
    v.nElectrolyzerStart>=elyOnlineDelta;
problem.Constraints.electrolyzerStartDeltaUpper = ...
    v.nElectrolyzerStart<=elyOnlineDelta+ ...
        Mely*(1-v.uElectrolyzerIncreasing);
problem.Constraints.electrolyzerStartModeUpper = ...
    v.nElectrolyzerStart<=Mely*v.uElectrolyzerIncreasing;
elyRampUp=optimconstr(N,1);
elyRampDown=optimconstr(N,1);
elyRampUp(1)=v.pElectrolyzerMW(1)- ...
    in.initial.electrolyzerPowerMW<=cfg.hydrogen.rampUpMWPerH*dt;
elyRampDown(1)=in.initial.electrolyzerPowerMW- ...
    v.pElectrolyzerMW(1)<=cfg.hydrogen.rampDownMWPerH*dt;
for t=2:N
    elyRampUp(t)=v.pElectrolyzerMW(t)-v.pElectrolyzerMW(t-1)<= ...
        cfg.hydrogen.rampUpMWPerH*dt;
    elyRampDown(t)=v.pElectrolyzerMW(t-1)-v.pElectrolyzerMW(t)<= ...
        cfg.hydrogen.rampDownMWPerH*dt;
end
problem.Constraints.electrolyzerRampUp=elyRampUp;
problem.Constraints.electrolyzerRampDown=elyRampDown;
productiveElyMWh=v.pElectrolyzerMW*dt- ...
    cfg.hydrogen.startEnergyMWhPerModule*v.nElectrolyzerStart;
problem.Constraints.electrolyzerProductiveEnergy=productiveElyMWh>=0;
problem.Constraints.h2Production = ...
    v.h2ProducedKg==(1000/cfg.hydrogen.secKWhPerKg)*productiveElyMWh;

% Hydrogen storage, delivery channels and optional reconversion to power.
problem.Constraints.h2StorageUpper = ...
    v.h2InventoryKg<= ...
    cfg.hydrogen.storageMaxKg*in.availability.h2Storage;
problem.Constraints.h2PipeUpper = ...
    v.h2PipeWithdrawnKg<= ...
    in.h2PipeLimitKgPerH.*in.availability.h2Pipe*dt;
problem.Constraints.h2ShipUpper = ...
    v.h2ShipWithdrawnKg<= ...
    in.h2ShipLimitKgPerH.*in.availability.h2Ship*dt;
problem.Constraints.h2PipeMinimum = ...
    v.h2PipeWithdrawnKg>=in.h2PipeMinimumKgPerH*dt;
problem.Constraints.h2ShipMinimum = ...
    v.h2ShipWithdrawnKg>=in.h2ShipMinimumKgPerH*dt;
problem.Constraints.h2PowerCapacity = ...
    v.pH2PowerMW<=cfg.h2Power.ratedMW*in.availability.h2Power;
problem.Constraints.h2PowerCommitment = ...
    v.pH2PowerMW<=cfg.h2Power.ratedMW*v.uH2Power;
problem.Constraints.h2Conversion = ...
    v.h2ToPowerConsumedKg== ...
    1000*v.pH2PowerMW*dt/ ...
    (cfg.h2Power.efficiencyLHV*cfg.h2Power.h2LHVKWhPerKg);
problem.Constraints.noElectrolysisDuringH2Power = ...
    v.nElectrolyzerOnline+Mely*v.uH2Power<=Mely;
h2PowerRampUp=optimconstr(N,1);
h2PowerRampDown=optimconstr(N,1);
h2PowerRampUp(1)=v.pH2PowerMW(1)-in.initial.h2PowerMW<= ...
    cfg.h2Power.rampUpMWPerH*dt;
h2PowerRampDown(1)=in.initial.h2PowerMW-v.pH2PowerMW(1)<= ...
    cfg.h2Power.rampDownMWPerH*dt;
for t=2:N
    h2PowerRampUp(t)=v.pH2PowerMW(t)-v.pH2PowerMW(t-1)<= ...
        cfg.h2Power.rampUpMWPerH*dt;
    h2PowerRampDown(t)=v.pH2PowerMW(t-1)-v.pH2PowerMW(t)<= ...
        cfg.h2Power.rampDownMWPerH*dt;
end
problem.Constraints.h2PowerRampUp=h2PowerRampUp;
problem.Constraints.h2PowerRampDown=h2PowerRampDown;
h2State=optimconstr(N,1);
h2State(1)=v.h2InventoryKg(1)== ...
    cfg.hydrogen.storageRetentionPerStep*in.initial.h2InventoryKg+ ...
    v.h2ProducedKg(1)-v.h2PipeWithdrawnKg(1)- ...
    v.h2ShipWithdrawnKg(1)-v.h2ToPowerConsumedKg(1);
for t=2:N
    h2State(t)=v.h2InventoryKg(t)== ...
        cfg.hydrogen.storageRetentionPerStep*v.h2InventoryKg(t-1)+ ...
        v.h2ProducedKg(t)-v.h2PipeWithdrawnKg(t)- ...
        v.h2ShipWithdrawnKg(t)-v.h2ToPowerConsumedKg(t);
end
problem.Constraints.h2State=h2State;
problem=add_terminal_constraint(problem,'h2',cfg.hydrogen.terminalRule, ...
    v.h2InventoryKg(N),in.initial.h2InventoryKg, ...
    cfg.hydrogen.terminalTargetKg);

% Compute service: firm/base service is explicit; flexible service is optional.
problem.Constraints.computeBaseLedger = ...
    v.pComputeBaseServedMW+v.pComputeBaseUnservedMW== ...
    in.pComputeBaseDemandMW;
problem.Constraints.computeFlexibleLimit = ...
    v.pComputeFlexibleMW<=in.pComputeFlexibleMaxMW;
pComputeFacility=v.pComputeBaseServedMW+v.pComputeFlexibleMW;
problem.Constraints.computeModuleLower = ...
    pComputeFacility>= ...
    cfg.compute.moduleFacilityMinMW*v.nComputeOnline;
problem.Constraints.computeModuleUpper = ...
    pComputeFacility<= ...
    cfg.compute.moduleFacilityMaxMW*v.nComputeOnline;
problem.Constraints.computeFacilityAvailability = ...
    pComputeFacility<=cfg.compute.facilityMaxMW*in.availability.compute;
computeRampUp=optimconstr(N,1);
computeRampDown=optimconstr(N,1);
computeRampUp(1)=pComputeFacility(1)-in.initial.computePowerMW<= ...
    cfg.compute.rampUpMWPerH*dt;
computeRampDown(1)=in.initial.computePowerMW-pComputeFacility(1)<= ...
    cfg.compute.rampDownMWPerH*dt;
for t=2:N
    computeRampUp(t)=pComputeFacility(t)-pComputeFacility(t-1)<= ...
        cfg.compute.rampUpMWPerH*dt;
    computeRampDown(t)=pComputeFacility(t-1)-pComputeFacility(t)<= ...
        cfg.compute.rampDownMWPerH*dt;
end
problem.Constraints.computeRampUp=computeRampUp;
problem.Constraints.computeRampDown=computeRampDown;

% Cable and marine outputs. Cable revenue and emissions use receiving-end MWh.
problem.Constraints.cableLoss = ...
    v.pCableReceivedMW==(1-cfg.output.cableLossFraction)*v.pCableSendMW;
problem.Constraints.cableSendLimit = ...
    v.pCableSendMW<=in.cableSendLimitMW.*in.availability.cable;
problem.Constraints.gridAcceptLimit = ...
    v.pCableReceivedMW<=in.gridAcceptLimitMW.*in.availability.cable;

% Optional strategy constraint: allocate the actually dispatched product
% input energy among cable sending, electrolysis and compute. The shares
% use a common MWh denominator; heterogeneous delivered products remain
% separate KPIs.
eElectricityInputMWh=sum(v.pCableSendMW)*dt;
eHydrogenInputMWh=sum(v.pElectrolyzerMW)*dt;
eTotalComputeInputMWh=sum(pComputeFacility)*dt;
eFlexibleComputeInputMWh=sum(v.pComputeFlexibleMW)*dt;
eAllocatedProductInputMWh=eElectricityInputMWh+ ...
    eHydrogenInputMWh+eFlexibleComputeInputMWh;
if in.productMix.enabled
    names={'Electricity','Hydrogen','Compute'};
    if strcmpi(in.productMix.mode,'hourly')
        productInputsMW=[v.pCableSendMW,v.pElectrolyzerMW, ...
            v.pComputeFlexibleMW];
        allocatedInputMW=sum(productInputsMW,2);
        targets=[in.productMix.targetElectricityShare, ...
            in.productMix.targetHydrogenShare, ...
            in.productMix.targetComputeShare];
        problem.Constraints.productMixMinimumHourlyPower = ...
            allocatedInputMW>=in.productMix.minimumAllocatedInputMW;
        for k=1:3
            lowerShare=max(0,targets(:,k)-in.productMix.shareTolerance);
            upperShare=min(1,targets(:,k)+in.productMix.shareTolerance);
            zeroTarget=targets(:,k)<=1e-12;
            lowerShare(zeroTarget)=0;
            upperShare(zeroTarget)=0;
            problem.Constraints.(['productMixLowerHourly' names{k}]) = ...
                productInputsMW(:,k)>=lowerShare.*allocatedInputMW;
            problem.Constraints.(['productMixUpperHourly' names{k}]) = ...
                productInputsMW(:,k)<=upperShare.*allocatedInputMW;
        end
    else
        problem.Constraints.productMixMinimumEnergy = ...
            eAllocatedProductInputMWh>= ...
            in.productMix.minimumAllocatedInputMWh;
        targets=[in.productMix.targetElectricityShare, ...
            in.productMix.targetHydrogenShare, ...
            in.productMix.targetComputeShare];
        energies=[eElectricityInputMWh,eHydrogenInputMWh, ...
            eFlexibleComputeInputMWh];
        for k=1:3
            lowerShare=max(0,targets(k)-in.productMix.shareTolerance);
            upperShare=min(1,targets(k)+in.productMix.shareTolerance);
            if targets(k)<=1e-12
                lowerShare=0;
                upperShare=0;
            end
            problem.Constraints.(['productMixLower' names{k}]) = ...
                energies(k)>=lowerShare*eAllocatedProductInputMWh;
            problem.Constraints.(['productMixUpper' names{k}]) = ...
                energies(k)<=upperShare*eAllocatedProductInputMWh;
        end
    end
end

% Physical and value expressions.
eAvailableMWh=sum(in.pSourceAvailableMW)*dt;
eSourceUsedMWh=sum(v.pSourceUsedMW)*dt;
eCurtailmentMWh=eAvailableMWh-eSourceUsedMWh;
eCableReceivedMWh=sum(v.pCableReceivedMW)*dt;
eComputeServiceMWhCS=sum((pComputeFacility./in.pue))*dt;
h2PipeDeliveredKg=(1-cfg.hydrogen.pipeLossFraction)* ...
    sum(v.h2PipeWithdrawnKg);
h2ShipDeliveredKg=(1-cfg.hydrogen.shipLossFraction)* ...
    sum(v.h2ShipWithdrawnKg);
h2DeliveredKg=h2PipeDeliveredKg+h2ShipDeliveredKg;
ensInternalMWh=sum(v.pInternalUnservedMW)*dt;
ensMarineMWh=sum(v.pMarineUnservedMW)*dt;
ensComputeBaseMWh=sum(v.pComputeBaseUnservedMW)*dt;
ensMWh=ensInternalMWh+ensMarineMWh+ensComputeBaseMWh;

operatingCostCNY = ...
    cfg.economic.sourceVariableOMCNYPerMWh*eSourceUsedMWh+ ...
    cfg.economic.bessDegradationCNYPerMWhDischarge* ...
        sum(v.pBessDischargeMW)*dt+ ...
    cfg.economic.hydrogenVariableCNYPerKgProduced*sum(v.h2ProducedKg)+ ...
    cfg.economic.electrolyzerStartCNYPerModule* ...
        sum(v.nElectrolyzerStart)+ ...
    cfg.economic.h2PipeTransportCNYPerKgWithdrawn* ...
        sum(v.h2PipeWithdrawnKg)+ ...
    cfg.economic.h2ShipTransportCNYPerKgWithdrawn* ...
        sum(v.h2ShipWithdrawnKg)+ ...
    cfg.economic.h2PowerVariableCNYPerMWh*sum(v.pH2PowerMW)*dt+ ...
    cfg.economic.cableVariableOMCNYPerMWhReceived*eCableReceivedMWh+ ...
    cfg.economic.computeVariableOMCNYPerMWhCS*eComputeServiceMWhCS+ ...
    cfg.economic.internalUnservedPenaltyCNYPerMWh*ensInternalMWh+ ...
    cfg.economic.marineUnservedPenaltyCNYPerMWh*ensMarineMWh+ ...
    cfg.economic.computeBaseUnservedPenaltyCNYPerMWh*ensComputeBaseMWh;
outputRevenueCNY = ...
    sum(in.electricityPriceCNYPerMWh.*v.pCableReceivedMW)*dt+ ...
    sum(in.hydrogenPriceCNYPerKg.* ...
        ((1-cfg.hydrogen.pipeLossFraction)*v.h2PipeWithdrawnKg+ ...
         (1-cfg.hydrogen.shipLossFraction)*v.h2ShipWithdrawnKg))+ ...
    sum(in.computePriceCNYPerMWhCS.*(pComputeFacility./in.pue))*dt+ ...
    sum(in.marineServiceValueCNYPerMWh.*v.pMarineServedMW)*dt;
terminalAdjustmentCNY = ...
    cfg.economic.bessTerminalValueCNYPerMWh* ...
        (in.initial.bessEnergyMWh-v.bessEnergyMWh(N))+ ...
    cfg.economic.h2InventoryTerminalValueCNYPerKg* ...
        (in.initial.h2InventoryKg-v.h2InventoryKg(N));
economicNetCostCNY=operatingCostCNY-outputRevenueCNY+ ...
    terminalAdjustmentCNY;

projectGHGKgCO2e = ...
    cfg.environment.sourceLifecycleKgCO2ePerMWhUsed*eSourceUsedMWh+ ...
    cfg.environment.bessThroughputKgCO2ePerMWh* ...
        sum(v.pBessChargeMW+v.pBessDischargeMW)*dt+ ...
    cfg.environment.hydrogenNonElectricKgCO2ePerKgProduced* ...
        sum(v.h2ProducedKg)+ ...
    cfg.environment.h2ShipKgCO2ePerKgWithdrawn* ...
        sum(v.h2ShipWithdrawnKg)+ ...
    cfg.environment.h2PipeKgCO2ePerKgWithdrawn* ...
        sum(v.h2PipeWithdrawnKg)+ ...
    cfg.environment.h2PowerNonFuelKgCO2ePerMWh*sum(v.pH2PowerMW)*dt;
avoidedBaselineGHGKgCO2e = ...
    cfg.environment.electricityBaselineKgCO2ePerMWhReceived* ...
        eCableReceivedMWh+ ...
    cfg.environment.hydrogenBaselineKgCO2ePerKgDelivered*h2DeliveredKg+ ...
    cfg.environment.computeBaselineKgCO2ePerMWhCS*eComputeServiceMWhCS+ ...
    cfg.environment.marineBaselineKgCO2ePerMWh* ...
        sum(v.pMarineServedMW)*dt;
netGHGKgCO2e=projectGHGKgCO2e-avoidedBaselineGHGKgCO2e;

% Epsilon constraints avoid arbitrary dimensioned weights.
if isfinite(cfg.objective.maxENSMWh)
    problem.Constraints.reliabilityEpsilon=ensMWh<=cfg.objective.maxENSMWh;
end
if isfinite(cfg.objective.maxNetGHGKgCO2e)
    problem.Constraints.environmentEpsilon = ...
        netGHGKgCO2e<=cfg.objective.maxNetGHGKgCO2e;
end
if cfg.objective.minRenewableUtilization>0
    assert(eAvailableMWh>0, ...
        ['Positive renewable-utilization epsilon is undefined when ', ...
         'available renewable energy is zero.']);
    problem.Constraints.utilizationEpsilon = ...
        eSourceUsedMWh>=cfg.objective.minRenewableUtilization*eAvailableMWh;
end

expr=struct;
expr.pComputeFacilityMW=pComputeFacility;
expr.pCurtailmentMW=pCurtailmentMW;
expr.eAvailableMWh=eAvailableMWh;
expr.eSourceUsedMWh=eSourceUsedMWh;
expr.eCurtailmentMWh=eCurtailmentMWh;
expr.eCableReceivedMWh=eCableReceivedMWh;
expr.eComputeServiceMWhCS=eComputeServiceMWhCS;
expr.eElectricityInputMWh=eElectricityInputMWh;
expr.eHydrogenInputMWh=eHydrogenInputMWh;
expr.eTotalComputeInputMWh=eTotalComputeInputMWh;
% Backward-compatible alias; product-mix C uses flexible compute only.
expr.eComputeInputMWh=eTotalComputeInputMWh;
expr.eFlexibleComputeInputMWh=eFlexibleComputeInputMWh;
expr.eAllocatedProductInputMWh=eAllocatedProductInputMWh;
expr.h2PipeDeliveredKg=h2PipeDeliveredKg;
expr.h2ShipDeliveredKg=h2ShipDeliveredKg;
expr.h2DeliveredKg=h2DeliveredKg;
expr.ensInternalMWh=ensInternalMWh;
expr.ensMarineMWh=ensMarineMWh;
expr.ensComputeBaseMWh=ensComputeBaseMWh;
expr.ensMWh=ensMWh;
expr.operatingCostCNY=operatingCostCNY;
expr.outputRevenueCNY=outputRevenueCNY;
expr.terminalAdjustmentCNY=terminalAdjustmentCNY;
expr.economicNetCostCNY=economicNetCostCNY;
expr.projectGHGKgCO2e=projectGHGKgCO2e;
expr.avoidedBaselineGHGKgCO2e=avoidedBaselineGHGKgCO2e;
expr.netGHGKgCO2e=netGHGKgCO2e;

problem.Objective=select_objective(cfg.objective.primary,expr);
mdl=struct('problem',problem,'variables',v,'expressions',expr);
end

function problem=add_terminal_constraint(problem,prefix,rule,xFinal,xInitial,xTarget)
switch lower(rule)
    case 'cyclic'
        problem.Constraints.([prefix 'Terminal'])=xFinal==xInitial;
    case 'target'
        problem.Constraints.([prefix 'Terminal'])=xFinal>=xTarget;
    case 'none'
        % Terminal inventory is valued in the objective.
    otherwise
        error('Unknown %s terminal rule: %s',prefix,rule);
end
end

function objective=select_objective(primary,expr)
switch primary
    case 'economicNetCostCNY'
        objective=expr.economicNetCostCNY;
    case 'netGHGKgCO2e'
        objective=expr.netGHGKgCO2e;
    case 'ensMWh'
        objective=expr.ensMWh;
    case 'curtailmentMWh'
        objective=expr.eCurtailmentMWh;
    otherwise
        error('Unsupported primary objective: %s',primary);
end
end
