function in = v5_validate_and_normalize_input(cfg,in)
%V5_VALIDATE_AND_NORMALIZE_INPUT Validate the V5 common case input.

assert(isstruct(in),'V5 input must be a struct.');
assert(isfield(in,'timeH') && isfield(in,'pSourceAvailableMW'), ...
    'V5 input requires timeH and pSourceAvailableMW.');
in.timeH=double(in.timeH(:));
N=numel(in.timeH);
assert(N>=1 && all(isfinite(in.timeH)) && ...
    (N==1 || all(diff(in.timeH)>0)), ...
    'timeH must be a finite strictly increasing N-by-1 vector.');
dt=cfg.time.dispatchStepH;
validate_config(cfg);
if N>1
    assert(max(abs(diff(in.timeH)-dt))<=1e-10, ...
        'V5 currently requires a constant %.6g h dispatch step.',dt);
end

in.pSourceAvailableMW=series(in,'pSourceAvailableMW',NaN,N);
assert(all(in.pSourceAvailableMW<=cfg.source.installedMW+1e-8), ...
    'pSourceAvailableMW exceeds cfg.source.installedMW.');
in.pSourceAuxMW=series(in,'pSourceAuxMW',0,N);
in.pCommonAuxDemandMW=series(in,'pCommonAuxDemandMW', ...
    cfg.internal.commonAuxDemandMW,N);
in.pPostPOILossMW=series(in,'pPostPOILossMW', ...
    cfg.internal.postPOILossMW,N);
in.pMarineDemandMW=series(in,'pMarineDemandMW', ...
    cfg.output.marineDemandMW,N);
in.pComputeBaseDemandMW=series(in,'pComputeBaseDemandMW',0,N);
in.pComputeFlexibleMaxMW=series(in,'pComputeFlexibleMaxMW', ...
    cfg.compute.facilityMaxMW,N);
in.pInternalDemandMW=in.pSourceAuxMW+in.pCommonAuxDemandMW+ ...
    in.pPostPOILossMW;

in.electricityPriceCNYPerMWh=finite_series(in, ...
    'electricityPriceCNYPerMWh', ...
    cfg.economic.electricityPriceCNYPerMWhReceived,N);
in.hydrogenPriceCNYPerKg=finite_series(in,'hydrogenPriceCNYPerKg', ...
    cfg.economic.hydrogenPriceCNYPerKgDelivered,N);
in.computePriceCNYPerMWhCS=finite_series(in,'computePriceCNYPerMWhCS', ...
    cfg.economic.computePriceCNYPerMWhCS,N);
in.marineServiceValueCNYPerMWh=finite_series(in, ...
    'marineServiceValueCNYPerMWh', ...
    cfg.economic.marineServiceValueCNYPerMWh,N);

in.cableSendLimitMW=series(in,'cableSendLimitMW', ...
    cfg.output.cableSendCapacityMW,N);
in.gridAcceptLimitMW=series(in,'gridAcceptLimitMW', ...
    cfg.output.gridAcceptCapacityMW,N);
in.h2PipeLimitKgPerH=series(in,'h2PipeLimitKgPerH', ...
    cfg.hydrogen.pipeCapacityKgPerH,N);
in.h2ShipLimitKgPerH=series(in,'h2ShipLimitKgPerH', ...
    cfg.hydrogen.shipCapacityKgPerH,N);
in.h2PipeMinimumKgPerH=series(in,'h2PipeMinimumKgPerH',0,N);
in.h2ShipMinimumKgPerH=series(in,'h2ShipMinimumKgPerH',0,N);
assert(all(in.h2PipeMinimumKgPerH<=in.h2PipeLimitKgPerH+1e-9), ...
    'h2PipeMinimumKgPerH exceeds the pipe limit.');
assert(all(in.h2ShipMinimumKgPerH<=in.h2ShipLimitKgPerH+1e-9), ...
    'h2ShipMinimumKgPerH exceeds the ship limit.');
in.pue=series(in,'pue',cfg.compute.pue,N);
assert(all(in.pue>=1),'All PUE values must be at least 1.');
in.gfmRequired=series(in,'gfmRequired',1,N);
assert(all(in.gfmRequired==0 | in.gfmRequired==1), ...
    'gfmRequired must be a scalar or N-by-1 binary requirement.');

% Optional product allocation strategy. Shares are defined
% on common-bus input energy, not on nameplate MW or heterogeneous product
% outputs:
%   cable sending MWh / electrolyzer input MWh /
%   flexible-compute input MWh.
if ~isfield(in,'productMix') || isempty(in.productMix)
    in.productMix=struct('enabled',false, ...
        'mode','horizon', ...
        'targetElectricityShare',0, ...
        'targetHydrogenShare',0, ...
        'targetComputeShare',0, ...
        'shareTolerance',0, ...
        'minimumAllocatedInputMWh',0, ...
        'minimumAllocatedInputMW',zeros(N,1), ...
        'definition','OPTIONAL_COMMON_BUS_INPUT_ENERGY_SHARES');
else
    pm=in.productMix;
    enabled=logical(scalar_field(pm,'enabled',true));
    mode=lower(string(field_or(pm,'mode','horizon')));
    assert(isscalar(mode) && any(mode==["horizon","hourly"]), ...
        'productMix.mode must be horizon or hourly.');
    if mode=="hourly"
        target=[ ...
            finite_share_series(pm,'targetElectricityShare',0,N), ...
            finite_share_series(pm,'targetHydrogenShare',0,N), ...
            finite_share_series(pm,'targetComputeShare',0,N)];
    else
        target=[ ...
            scalar_field(pm,'targetElectricityShare',0), ...
            scalar_field(pm,'targetHydrogenShare',0), ...
            scalar_field(pm,'targetComputeShare',0)];
    end
    tolerance=scalar_field(pm,'shareTolerance',0);
    minimumEnergy=scalar_field(pm,'minimumAllocatedInputMWh',0);
    minimumPower=series(pm,'minimumAllocatedInputMW',0,N);
    assert(all(isfinite(target)) && all(target>=0) && all(target<=1), ...
        'productMix target shares must be finite values in [0,1].');
    if enabled
        assert(all(abs(sum(target,2)-1)<=1e-10), ...
            'Enabled productMix target shares must sum to one in every applicable interval.');
    end
    assert(isfinite(tolerance) && tolerance>=0 && tolerance<0.5, ...
        'productMix.shareTolerance must be in [0,0.5).');
    assert(isfinite(minimumEnergy) && minimumEnergy>=0, ...
        'productMix.minimumAllocatedInputMWh must be nonnegative.');
    if mode=="hourly"
        assert(minimumEnergy==0, ...
            ['Hourly productMix must use minimumAllocatedInputMW; ', ...
             'a horizon-energy minimum would reintroduce future coupling.']);
    else
        assert(all(minimumPower==0), ...
            'Horizon productMix cannot use minimumAllocatedInputMW.');
    end
    in.productMix=struct( ...
        'enabled',enabled, ...
        'mode',char(mode), ...
        'targetElectricityShare',target(:,1), ...
        'targetHydrogenShare',target(:,2), ...
        'targetComputeShare',target(:,3), ...
        'shareTolerance',tolerance, ...
        'minimumAllocatedInputMWh',minimumEnergy, ...
        'minimumAllocatedInputMW',minimumPower, ...
        'definition','OPTIONAL_COMMON_BUS_INPUT_SHARES');
end

availabilityNames={'bess','electrolyzer','h2Storage','compute', ...
    'cable','h2Pipe','h2Ship','h2Power'};
if ~isfield(in,'availability') || isempty(in.availability)
    in.availability=struct;
end
for k=1:numel(availabilityNames)
    name=availabilityNames{k};
    if isfield(in.availability,name)
        value=in.availability.(name);
    else
        value=1;
    end
    value=double(value(:));
    if isscalar(value), value=repmat(value,N,1); end
    assert(numel(value)==N && all(isfinite(value)) && ...
        all(value>=0) && all(value<=1), ...
        'availability.%s must be scalar or N-by-1 in [0,1].',name);
    in.availability.(name)=value;
end

if ~cfg.output.powerExportEnabled
    in.availability.cable(:)=0;
end
if ~cfg.output.hydrogenPipeEnabled
    in.availability.h2Pipe(:)=0;
end
if ~cfg.output.hydrogenShipEnabled
    in.availability.h2Ship(:)=0;
end
if ~cfg.h2Power.enabled
    in.availability.h2Power(:)=0;
end
assert(all(in.h2PipeMinimumKgPerH<= ...
    in.h2PipeLimitKgPerH.*in.availability.h2Pipe+1e-9), ...
    'h2PipeMinimumKgPerH exceeds available pipe capability.');
assert(all(in.h2ShipMinimumKgPerH<= ...
    in.h2ShipLimitKgPerH.*in.availability.h2Ship+1e-9), ...
    'h2ShipMinimumKgPerH exceeds available ship capability.');

if isfield(in,'initial') && ~isempty(in.initial)
    initial=in.initial;
else
    initial=struct;
end
in.initial=struct( ...
    'bessEnergyMWh',scalar_or_default(initial,'bessEnergyMWh', ...
        cfg.bess.socInitial*cfg.bess.energyMWh), ...
    'h2InventoryKg',scalar_or_default(initial,'h2InventoryKg', ...
        cfg.hydrogen.storageInitialKg), ...
    'electrolyzerOnlineModules',scalar_or_default(initial, ...
        'electrolyzerOnlineModules',0), ...
    'electrolyzerPowerMW',scalar_or_default(initial, ...
        'electrolyzerPowerMW',0), ...
    'computePowerMW',scalar_or_default(initial,'computePowerMW',0), ...
    'h2PowerMW',scalar_or_default(initial,'h2PowerMW',0));

eMin=cfg.bess.socMin*cfg.bess.energyMWh+ ...
    cfg.bess.gfmReserveEnergyMWh*in.gfmRequired(1);
eMax=cfg.bess.socMax*cfg.bess.energyMWh- ...
    cfg.bess.gfmAbsorptionReserveEnergyMWh*in.gfmRequired(1);
assert(in.initial.bessEnergyMWh>=eMin-1e-9 && ...
    in.initial.bessEnergyMWh<=eMax+1e-9, ...
    'Initial BESS energy violates SOC plus GFM reserve bounds.');
assert(in.initial.h2InventoryKg>=0 && ...
    in.initial.h2InventoryKg<=cfg.hydrogen.storageMaxKg, ...
    'Initial H2 inventory violates storage bounds.');
assert(in.initial.electrolyzerOnlineModules>=0 && ...
    in.initial.electrolyzerOnlineModules<=cfg.hydrogen.moduleCount && ...
    abs(in.initial.electrolyzerOnlineModules- ...
    round(in.initial.electrolyzerOnlineModules))<=1e-9, ...
    'Initial electrolyzer module count must be an integer in range.');

if strcmp(cfg.meta.caseMode,'engineering_base')
    requiredSigned={ ...
        'site.distanceToShoreKm',cfg.site.distanceToShoreKm; ...
        'bess.gfmReservePowerMW',cfg.bess.gfmReservePowerMW; ...
        'bess.gfmReserveEnergyMWh',cfg.bess.gfmReserveEnergyMWh; ...
        'bess.gfmAbsorptionReservePowerMW', ...
            cfg.bess.gfmAbsorptionReservePowerMW; ...
        'bess.gfmAbsorptionReserveEnergyMWh', ...
            cfg.bess.gfmAbsorptionReserveEnergyMWh; ...
        'economic.minimumProjectIRR',cfg.economic.minimumProjectIRR};
    missing=requiredSigned(cellfun(@(x)~isfinite(x), ...
        requiredSigned(:,2)),1);
    assert(isempty(missing), ...
        'engineering_base has unsigned P0 fields: %s', ...
        strjoin(missing,', '));
end

in.meta=struct( ...
    'horizonH',N*dt, ...
    'isShortValidationHorizon',abs(N*dt- ...
        cfg.time.shortValidationHorizonH)<=1e-9, ...
    'isAnnualValidationHorizon',abs(N*dt- ...
        cfg.time.annualValidationHorizonH)<=1e-9, ...
    'sourceMeterPoint',cfg.source.meterPoint, ...
    'powerMeaning','interval-average MW', ...
    'stateMeaning','end-of-interval state');
end

function x=series(s,name,defaultValue,N)
if isfield(s,name), x=s.(name); else, x=defaultValue; end
x=double(x(:));
if isscalar(x), x=repmat(x,N,1); end
assert(numel(x)==N && all(isfinite(x)) && all(x>=0), ...
    '%s must be a finite nonnegative scalar or N-by-1 series.',name);
end

function x=finite_series(s,name,defaultValue,N)
if isfield(s,name), x=s.(name); else, x=defaultValue; end
x=double(x(:));
if isscalar(x), x=repmat(x,N,1); end
assert(numel(x)==N && all(isfinite(x)), ...
    '%s must be a finite scalar or N-by-1 series.',name);
end

function x=scalar_or_default(s,name,defaultValue)
if isfield(s,name), x=s.(name); else, x=defaultValue; end
x=double(x);
assert(isscalar(x) && isfinite(x) && x>=0, ...
    'initial.%s must be a finite nonnegative scalar.',name);
end

function x=scalar_field(s,name,defaultValue)
if isfield(s,name), x=s.(name); else, x=defaultValue; end
x=double(x);
assert(isscalar(x) && isfinite(x), ...
    'productMix.%s must be a finite scalar.',name);
end

function x=finite_share_series(s,name,defaultValue,N)
if isfield(s,name), x=s.(name); else, x=defaultValue; end
x=double(x(:));
if isscalar(x), x=repmat(x,N,1); end
assert(numel(x)==N && all(isfinite(x)), ...
    'productMix.%s must be a finite scalar or N-by-1 series.',name);
end

function value=field_or(s,name,defaultValue)
if isfield(s,name), value=s.(name); else, value=defaultValue; end
end

function mustBeFinitePositive(x,name)
assert(isscalar(x) && isfinite(x) && x>0, ...
    '%s must be a finite positive scalar.',name);
end

function validate_config(cfg)
mustBeFinitePositive(cfg.time.dispatchStepH,'cfg.time.dispatchStepH');
mustBeFinitePositive(cfg.source.installedMW,'cfg.source.installedMW');
mustBeFiniteNonnegative(cfg.source.windInstalledMW, ...
    'cfg.source.windInstalledMW');
mustBeFiniteNonnegative(cfg.source.pvInstalledMW, ...
    'cfg.source.pvInstalledMW');
mustBeFiniteNonnegative(cfg.source.tidalInstalledMW, ...
    'cfg.source.tidalInstalledMW');
assert(cfg.source.windInstalledMW+cfg.source.pvInstalledMW+ ...
    cfg.source.tidalInstalledMW<=cfg.source.installedMW+1e-9, ...
    'Named source capacities exceed total installed source capacity.');
mustBeFinitePositive(cfg.bess.powerMW,'cfg.bess.powerMW');
mustBeFinitePositive(cfg.bess.energyMWh,'cfg.bess.energyMWh');
mustBeFiniteNonnegative(cfg.bess.chargeMaxMW,'cfg.bess.chargeMaxMW');
mustBeFiniteNonnegative(cfg.bess.dischargeMaxMW, ...
    'cfg.bess.dischargeMaxMW');
assert(cfg.bess.chargeMaxMW<=cfg.bess.powerMW+1e-9 && ...
    cfg.bess.dischargeMaxMW<=cfg.bess.powerMW+1e-9, ...
    'BESS charge/discharge capability exceeds the stated power rating.');
mustBeFractionPositive(cfg.bess.etaCharge,'cfg.bess.etaCharge');
mustBeFractionPositive(cfg.bess.etaDischarge,'cfg.bess.etaDischarge');
mustBeFractionPositive(cfg.bess.standingRetentionPerStep, ...
    'cfg.bess.standingRetentionPerStep');
mustBeFraction(cfg.bess.socMin,'cfg.bess.socMin');
mustBeFraction(cfg.bess.socMax,'cfg.bess.socMax');
assert(cfg.bess.socMin<cfg.bess.socMax, ...
    'BESS socMin must be smaller than socMax.');
mustBeFiniteNonnegative(cfg.bess.gfmReservePowerMW, ...
    'cfg.bess.gfmReservePowerMW');
mustBeFiniteNonnegative(cfg.bess.gfmReserveEnergyMWh, ...
    'cfg.bess.gfmReserveEnergyMWh');
mustBeFiniteNonnegative(cfg.bess.gfmAbsorptionReservePowerMW, ...
    'cfg.bess.gfmAbsorptionReservePowerMW');
mustBeFiniteNonnegative(cfg.bess.gfmAbsorptionReserveEnergyMWh, ...
    'cfg.bess.gfmAbsorptionReserveEnergyMWh');
assert(cfg.bess.gfmReservePowerMW<=cfg.bess.dischargeMaxMW, ...
    'GFM power reserve exceeds BESS discharge capability.');
assert(cfg.bess.gfmAbsorptionReservePowerMW<=cfg.bess.chargeMaxMW, ...
    'GFM absorption reserve exceeds BESS charge capability.');
assert(cfg.bess.socMin*cfg.bess.energyMWh+ ...
    cfg.bess.gfmReserveEnergyMWh<= ...
    cfg.bess.socMax*cfg.bess.energyMWh- ...
    cfg.bess.gfmAbsorptionReserveEnergyMWh, ...
    'GFM energy reserve leaves no feasible BESS SOC range.');

mustBeFinitePositive(cfg.hydrogen.electrolyzerRatedMW, ...
    'cfg.hydrogen.electrolyzerRatedMW');
mustBePositiveInteger(cfg.hydrogen.moduleCount, ...
    'cfg.hydrogen.moduleCount');
mustBeFinitePositive(cfg.hydrogen.moduleRatedMW, ...
    'cfg.hydrogen.moduleRatedMW');
mustBeFiniteNonnegative(cfg.hydrogen.moduleMinMW, ...
    'cfg.hydrogen.moduleMinMW');
assert(cfg.hydrogen.moduleMinMW<=cfg.hydrogen.moduleRatedMW, ...
    'Electrolyzer module minimum exceeds module rating.');
assert(cfg.hydrogen.moduleCount*cfg.hydrogen.moduleRatedMW<= ...
    cfg.hydrogen.electrolyzerRatedMW+1e-9, ...
    'Electrolyzer module ratings exceed plant rating.');
mustBeFiniteNonnegative(cfg.hydrogen.rampUpMWPerH, ...
    'cfg.hydrogen.rampUpMWPerH');
mustBeFiniteNonnegative(cfg.hydrogen.rampDownMWPerH, ...
    'cfg.hydrogen.rampDownMWPerH');
mustBeFiniteNonnegative(cfg.hydrogen.startEnergyMWhPerModule, ...
    'cfg.hydrogen.startEnergyMWhPerModule');
mustBeFinitePositive(cfg.hydrogen.secKWhPerKg, ...
    'cfg.hydrogen.secKWhPerKg');
mustBeFiniteNonnegative(cfg.hydrogen.storageMaxKg, ...
    'cfg.hydrogen.storageMaxKg');
mustBeFractionPositive(cfg.hydrogen.storageRetentionPerStep, ...
    'cfg.hydrogen.storageRetentionPerStep');
mustBeFiniteNonnegative(cfg.hydrogen.pipeCapacityKgPerH, ...
    'cfg.hydrogen.pipeCapacityKgPerH');
mustBeFiniteNonnegative(cfg.hydrogen.shipCapacityKgPerH, ...
    'cfg.hydrogen.shipCapacityKgPerH');
mustBeFraction(cfg.hydrogen.pipeLossFraction, ...
    'cfg.hydrogen.pipeLossFraction');
mustBeFraction(cfg.hydrogen.shipLossFraction, ...
    'cfg.hydrogen.shipLossFraction');

mustBeFiniteNonnegative(cfg.h2Power.ratedMW,'cfg.h2Power.ratedMW');
mustBeFractionPositive(cfg.h2Power.efficiencyLHV, ...
    'cfg.h2Power.efficiencyLHV');
mustBeFinitePositive(cfg.h2Power.h2LHVKWhPerKg, ...
    'cfg.h2Power.h2LHVKWhPerKg');
mustBeFiniteNonnegative(cfg.h2Power.rampUpMWPerH, ...
    'cfg.h2Power.rampUpMWPerH');
mustBeFiniteNonnegative(cfg.h2Power.rampDownMWPerH, ...
    'cfg.h2Power.rampDownMWPerH');
if cfg.h2Power.enabled
    mustBeFinitePositive(cfg.h2Power.ratedMW,'cfg.h2Power.ratedMW');
end

mustBePositiveInteger(cfg.compute.moduleCount,'cfg.compute.moduleCount');
mustBeFiniteNonnegative(cfg.compute.moduleFacilityMinMW, ...
    'cfg.compute.moduleFacilityMinMW');
mustBeFinitePositive(cfg.compute.moduleFacilityMaxMW, ...
    'cfg.compute.moduleFacilityMaxMW');
assert(cfg.compute.moduleFacilityMinMW<=cfg.compute.moduleFacilityMaxMW, ...
    'Compute module minimum exceeds maximum.');
mustBeFinitePositive(cfg.compute.facilityMaxMW, ...
    'cfg.compute.facilityMaxMW');
mustBeFinitePositive(cfg.compute.pue,'cfg.compute.pue');
assert(cfg.compute.pue>=1,'PUE must be at least 1.');
mustBeFiniteNonnegative(cfg.compute.rampUpMWPerH, ...
    'cfg.compute.rampUpMWPerH');
mustBeFiniteNonnegative(cfg.compute.rampDownMWPerH, ...
    'cfg.compute.rampDownMWPerH');

mustBeFiniteNonnegative(cfg.output.cableSendCapacityMW, ...
    'cfg.output.cableSendCapacityMW');
mustBeFiniteNonnegative(cfg.output.gridAcceptCapacityMW, ...
    'cfg.output.gridAcceptCapacityMW');
mustBeFraction(cfg.output.cableLossFraction, ...
    'cfg.output.cableLossFraction');
mustBeFiniteNonnegative(cfg.output.marineDemandMW, ...
    'cfg.output.marineDemandMW');
assert(isscalar(cfg.objective.minRenewableUtilization) && ...
    isfinite(cfg.objective.minRenewableUtilization) && ...
    cfg.objective.minRenewableUtilization>=0 && ...
    cfg.objective.minRenewableUtilization<=1, ...
    'minRenewableUtilization must be in [0,1].');
assert((isfinite(cfg.objective.maxENSMWh) && ...
    cfg.objective.maxENSMWh>=0) || ...
    (isinf(cfg.objective.maxENSMWh) && cfg.objective.maxENSMWh>0), ...
    'maxENSMWh must be nonnegative or Inf.');
assert(isscalar(cfg.objective.maxNetGHGKgCO2e) && ...
    (isfinite(cfg.objective.maxNetGHGKgCO2e) || ...
    (isinf(cfg.objective.maxNetGHGKgCO2e) && ...
    cfg.objective.maxNetGHGKgCO2e>0)), ...
    'maxNetGHGKgCO2e must be finite or positive Inf.');
assert(strcmp(cfg.objective.method,'EPSILON_CONSTRAINT'), ...
    'V5 currently implements EPSILON_CONSTRAINT only.');
assert(strcmp(cfg.solver.name,'intlinprog'), ...
    'V5 currently supports intlinprog only.');
mustBeFiniteNonnegative(cfg.objective.primaryRelativeTolerance, ...
    'cfg.objective.primaryRelativeTolerance');
mustBeFiniteNonnegative(cfg.solver.relativeGapTolerance, ...
    'cfg.solver.relativeGapTolerance');
mustBeFinitePositive(cfg.solver.maxTimeS,'cfg.solver.maxTimeS');

nonnegativeEconomic={ ...
    'sourceVariableOMCNYPerMWh', ...
    'bessDegradationCNYPerMWhDischarge', ...
    'hydrogenVariableCNYPerKgProduced', ...
    'electrolyzerStartCNYPerModule', ...
    'h2PipeTransportCNYPerKgWithdrawn', ...
    'h2ShipTransportCNYPerKgWithdrawn', ...
    'h2PowerVariableCNYPerMWh', ...
    'cableVariableOMCNYPerMWhReceived', ...
    'computeVariableOMCNYPerMWhCS', ...
    'bessTerminalValueCNYPerMWh', ...
    'h2InventoryTerminalValueCNYPerKg', ...
    'internalUnservedPenaltyCNYPerMWh', ...
    'marineUnservedPenaltyCNYPerMWh', ...
    'computeBaseUnservedPenaltyCNYPerMWh'};
for k=1:numel(nonnegativeEconomic)
    name=nonnegativeEconomic{k};
    mustBeFiniteNonnegative(cfg.economic.(name), ...
        ['cfg.economic.' name]);
end
finiteEconomic={ ...
    'electricityPriceCNYPerMWhReceived', ...
    'hydrogenPriceCNYPerKgDelivered', ...
    'computePriceCNYPerMWhCS', ...
    'marineServiceValueCNYPerMWh'};
for k=1:numel(finiteEconomic)
    name=finiteEconomic{k};
    assert(isscalar(cfg.economic.(name)) && ...
        isfinite(cfg.economic.(name)), ...
        'cfg.economic.%s must be a finite scalar.',name);
end
environmentNames={ ...
    'sourceLifecycleKgCO2ePerMWhUsed', ...
    'bessThroughputKgCO2ePerMWh', ...
    'hydrogenNonElectricKgCO2ePerKgProduced', ...
    'h2ShipKgCO2ePerKgWithdrawn', ...
    'h2PipeKgCO2ePerKgWithdrawn', ...
    'h2PowerNonFuelKgCO2ePerMWh', ...
    'electricityBaselineKgCO2ePerMWhReceived', ...
    'hydrogenBaselineKgCO2ePerKgDelivered', ...
    'computeBaselineKgCO2ePerMWhCS', ...
    'marineBaselineKgCO2ePerMWh'};
for k=1:numel(environmentNames)
    name=environmentNames{k};
    mustBeFiniteNonnegative(cfg.environment.(name), ...
        ['cfg.environment.' name]);
end
end

function mustBeFiniteNonnegative(x,name)
assert(isscalar(x) && isfinite(x) && x>=0, ...
    '%s must be a finite nonnegative scalar.',name);
end

function mustBeFraction(x,name)
assert(isscalar(x) && isfinite(x) && x>=0 && x<=1, ...
    '%s must be in [0,1].',name);
end

function mustBeFractionPositive(x,name)
assert(isscalar(x) && isfinite(x) && x>0 && x<=1, ...
    '%s must be in (0,1].',name);
end

function mustBePositiveInteger(x,name)
assert(isscalar(x) && isfinite(x) && x>=1 && ...
    abs(x-round(x))<=1e-9,'%s must be a positive integer.',name);
end
