function registry = v5_foundation_registry(v5Root)
%V5_FOUNDATION_REGISTRY Describe V5 ownership and copied-module use.

if nargin<1 || isempty(v5Root)
    v5Root=fileparts(fileparts(mfilename('fullpath')));
end
paths=v5_add_foundation_paths(v5Root);
moduleId=["4.1";"4.2";"4.3";"4.4";"4.5";"4.6";"4.7";"4.8";"4.9"];
location=[ ...
    "foundation/library/4.1*"; ...
    "foundation/library/4.2*"; ...
    "foundation/modules/4.3_source via source/v5_source_adapter.m"; ...
    "foundation/modules/4.4_bus"; ...
    "foundation/modules/4.5_storage_hydrogen"; ...
    "foundation/modules/4.6_compute"; ...
    "foundation/modules/4.7_outputs"; ...
    "foundation/modules/4.8_objectives"; ...
    "model/v5_build_problem.m"];
v5Role=[ ...
    "boundary and metering authority"; ...
    "legacy V2 packet validation and V3 bridge evidence"; ...
    "executable source availability engine"; ...
    "independent bus-ledger reference"; ...
    "physical equations and dynamic-validation reference"; ...
    "PUE, task, SLA and response-boundary reference"; ...
    "cable, hydrogen-delivery and marine-output reference"; ...
    "independent economics/LCA/reliability evaluation reference"; ...
    "sole V5 MILP dispatch and optimization owner"];
executionMode=[ ...
    "COPIED_REFERENCE"; ...
    "COPIED_SUPPORT"; ...
    "EXECUTED_WHEN_SOURCE_CASE_IS_USED"; ...
    "NATIVE_V5_LEDGER_PLUS_OPTIONAL_CROSS_CHECK"; ...
    "NATIVE_V5_MILP_CONSTRAINTS_PLUS_DYNAMIC_GATE"; ...
    "NATIVE_V5_AGGREGATE_CONSTRAINTS; COPIED_HIGH_FIDELITY_MODEL"; ...
    "NATIVE_V5_CHANNEL_CONSTRAINTS; COPIED_DELIVERY_MODEL"; ...
    "NATIVE_V5_OBJECTIVES; COPIED_INDEPENDENT_EVALUATOR"; ...
    "EXECUTED_ALWAYS"];
registry=struct;
registry.table=table(moduleId,location,v5Role,executionMode);
registry.paths=paths;
registry.externalV4RuntimeDependency=false;
registry.v4DispatchCopied=false;
registry.dispatchOwner='V5 model/v5_build_problem.m';
registry.manifest=fullfile(v5Root,'manifests', ...
    'v5_foundation_manifest.csv');
registry.assumptionNotice='[假设值，待企业调研校准]';
end
