function [s,T]=v4_lifecycle_economics_4_8(cfg,p,periodOperatingCostCNY, ...
    periodRevenueCNY,periodPenaltyCostCNY,horizonH,assetContext)
%V4_LIFECYCLE_ECONOMICS_4_8 Capital recovery and discounted lifecycle ledger.
% Public values are market proxies, not supplier quotations. The short
% dispatch horizon is repeated to create an annual equivalent; this is a
% scenario comparison convention, not a bankable forecast.
l=p.lifecycle;
if nargin<7 || isempty(assetContext), assetContext=struct; end
life=l.analysisLifeYear;
if isfield(cfg,'economics') && isfield(cfg.economics,'analysisLifeYear') && ...
        isfinite(cfg.economics.analysisLifeYear)
    life=cfg.economics.analysisLifeYear;
end
r=l.discountRate;
if isfield(cfg,'economics') && isfield(cfg.economics,'discountRate') && ...
        isfinite(cfg.economics.discountRate)
    r=cfg.economics.discountRate;
end
assert(life>0 && r>=0 && horizonH>0,'Invalid lifecycle horizon or discount rate.');
constructionYear=0;
if isfield(cfg,'economics') && isfield(cfg.economics,'constructionPeriodYear') && ...
        isfinite(cfg.economics.constructionPeriodYear)
    constructionYear=cfg.economics.constructionPeriodYear;
end
crf=capital_recovery_factor(r,life);
annuity=(1-(1+r)^(-life))/r;
if r==0, annuity=life; end

installed=installed_capacity(cfg);
windKW=installed.windMW*1e3;
pvW=installed.pvMW*1e6;
tidalKW=installed.tidalMW*1e3;
bessKWh=installed.bessEnergyMWh*1e3;
bessKW=installed.bessPowerMW*1e3;
electrolyzerKW=installed.electrolyzerMW*1e3;
computeW=installed.computeITMW*1e6;
distanceKm=installed.powerCableDistanceKm;
h2StorageKg=0;
if isfield(assetContext,'hydrogenStorageInstalledKg')
    h2StorageKg=max(0,assetContext.hydrogenStorageInstalledKg);
elseif isfinite(installed.hydrogenStorageKg)
    h2StorageKg=max(0,installed.hydrogenStorageKg);
end
[powerCableCapexCNY,converterCapexCNY,cableDesign]= ...
    power_cable_capex(installed.powerCableMW,distanceKm,l);

assetName=["floatingWind";"marineFloatingPV";"tidalStream";"BESS"; ...
    "PEMElectrolyzer";"hydrogenStorage";"subseaCompute"; ...
    "powerExportCable";"converterAndSubstation";"fiberCable"];
scenarioEnabled=[ ...
    asset_enabled(cfg,'floatingWind',true); ...
    asset_enabled(cfg,'marineFloatingPV',true); ...
    asset_enabled(cfg,'tidalStream',true); ...
    asset_enabled(cfg,'BESS',true); ...
    asset_enabled(cfg,'PEMElectrolyzer',true); ...
    asset_enabled(cfg,'hydrogenStorage',true); ...
    asset_enabled(cfg,'subseaCompute',true); ...
    asset_enabled(cfg,'powerExportCable',true); ...
    asset_enabled(cfg,'converterAndSubstation',true); ...
    asset_enabled(cfg,'fiberCable',true)];
enabled=scenarioEnabled;
enabled(6)=scenarioEnabled(6) && h2StorageKg>1e-9;
capexCNY=[ ...
    windKW*l.windCapexCNYPerKW; ...
    pvW*l.pvCapexUSDPerW*l.usdToCNY; ...
    tidalKW*l.tidalCapexUSDPerKW*l.usdToCNY; ...
    (bessKWh*l.bessEnergyCapexUSDPerKWh+ ...
        bessKW*l.bessPowerCapexUSDPerKW)*l.usdToCNY; ...
    electrolyzerKW*l.electrolyzerCapexUSDPerKW*l.usdToCNY; ...
    h2StorageKg*l.hydrogenStorageCapexUSDPerKg*l.usdToCNY; ...
    computeW*l.computeCapexUSDPerWIT*l.usdToCNY; ...
    powerCableCapexCNY; ...
    converterCapexCNY; ...
    installed.fiberCableDistanceKm*l.fiberCableCapexEURPerKm*l.eurToCNY];
capexCNY=capexCNY.*double(enabled);
fixedOMAnnualCNY=[ ...
    windKW*l.windFixedOMUSDPerKWYear*l.usdToCNY; ...
    pvW/1e3*l.pvFixedOMUSDPerKWYear*l.usdToCNY; ...
    capexCNY(3)*l.tidalFixedOMFraction; ...
    capexCNY(4)*l.bessFixedOMFraction; ...
    capexCNY(5)*l.electrolyzerFixedOMFraction; ...
    capexCNY(6)*l.hydrogenStorageFixedOMFraction; ...
    capexCNY(7)*l.computeFixedOMFraction; ...
    capexCNY(8)*l.powerCableFixedOMFraction; ...
    capexCNY(9)*l.powerCableFixedOMFraction; ...
    capexCNY(10)*l.fiberCableFixedOMFraction];
depreciationLifeYear=[25;25;20;15;20;25;25;40;30;25];
dataStatus=[ ...
    "政府官网公开目标代理"; ...
    "国际合作组织数据库中位值代理"; ...
    "[假设值，待企业调研校准]"; ...
    "美国国家实验室公开成本代理"; ...
    "美国国家实验室公开制造价格代理"; ...
    "美国国家实验室陆上储氢代理"; ...
    "企业官网2 MW液冷数据中心代理"; ...
    "NREL电压等级/线路安装成本代理"; ...
    "NREL换流站/变电站成本代理"; ...
    "欧盟政府研究机构平均安装成本代理"];
sourceCategory=[ ...
    "政府官网＋美国国家实验室官方报告"; ...
    "国际合作组织技术报告＋美国国家实验室官方基准"; ...
    "欧盟政府报告＋假设值"; ...
    "美国国家实验室官方技术报告"; ...
    "美国国家实验室官方技术报告"; ...
    "美国能源部/国家实验室官方技术报告"; ...
    "企业官方网站技术白皮书"; ...
    "美国国家实验室官方技术报告"; ...
    "美国国家实验室官方技术报告"; ...
    "欧盟政府研究机构官网"];
sourceUrl=[ ...
    "https://www.nea.gov.cn/20260522/7cf96e984e124058922e2513523e8581/c.html ; https://www.nrel.gov/docs/fy25osti/91775.pdf"; ...
    "https://iea-pvps.org/key-topics/t13-floating-pv-plants-review-2025/ ; https://atb.nrel.gov/electricity/2024/utility-scale_pv"; ...
    "https://op.europa.eu/webpub/mare/eu-blue-economy-report-2025/blue-economic-sectors/marine-renewable-energy.html"; ...
    "https://www.nrel.gov/docs/fy24osti/87646.pdf"; ...
    "https://www.nrel.gov/docs/fy24osti/87625.pdf"; ...
    "https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/progress19/ins_sa173_hunter_2019.pdf"; ...
    "https://blog.se.com/datacenter/architecture/2020/02/24/liquid-vs-air-cooling-which-is-the-capex-winner/"; ...
    "https://docs.nrel.gov/docs/fy24osti/88003.pdf"; ...
    "https://docs.nrel.gov/docs/fy24osti/88003.pdf"; ...
    "https://joint-research-centre.ec.europa.eu/jrc-explains/subsea-cables-how-vulnerable-are-they-and-can-we-protect-them_en"];

replacementPVCNY=zeros(size(capexCNY));
replacementSchedule=strings(size(capexCNY));
replacementPVCNY(3)=discounted_events(0.25*capexCNY(3),[10 20],r);
replacementSchedule(3)="Y10/Y20: 25% major overhaul [假设值]";
bessReplacementCNY=(bessKWh*l.bessReplacementEnergyUSDPerKWh+ ...
    bessKW*l.bessReplacementPowerUSDPerKW)*l.usdToCNY;
replacementPVCNY(4)=discounted_events(bessReplacementCNY,[10 20],r);
replacementSchedule(4)="Y10/Y20: NREL replacement-cost proxy";
replacementPVCNY(5)=discounted_events( ...
    l.electrolyzerStackReplacementFraction*capexCNY(5),[10 20],r);
replacementSchedule(5)="Y10/Y20: 40% stack [假设值]";
replacementPVCNY(7)=discounted_events( ...
    l.computeITReplacementFraction*capexCNY(7),[5 10 15 20],r);
replacementSchedule(7)="Y5/Y10/Y15/Y20: 50% IT [假设值]";
replacementPVCNY(10)=discounted_events(0.30*capexCNY(10),12,r);
replacementSchedule(10)="Y12: 30% [假设值]";
replacementSchedule(replacementSchedule=="")="none within analysis life";

constructionFinancingCNY=capexCNY*construction_financing_fraction(r,constructionYear);
financedCapexCNY=capexCNY+constructionFinancingCNY;
annualDepreciationCNY=financedCapexCNY./depreciationLifeYear;
annualInitialCapitalRecoveryCNY=financedCapexCNY*crf;
annualFinancingCNY=annualInitialCapitalRecoveryCNY-annualDepreciationCNY;
assert(all(annualFinancingCNY>=-1e-8), ...
    'Depreciation life creates a negative financing split.');
annualFinancingCNY=max(0,annualFinancingCNY);
annualReplacementRecoveryCNY=replacementPVCNY*crf;

T=table(assetName,scenarioEnabled,enabled,capexCNY, ...
    constructionFinancingCNY,financedCapexCNY, ...
    fixedOMAnnualCNY,depreciationLifeYear, ...
    annualDepreciationCNY,annualFinancingCNY,replacementPVCNY, ...
    annualReplacementRecoveryCNY,replacementSchedule,sourceCategory, ...
    sourceUrl,dataStatus);

periodFraction=horizonH/l.hoursPerYear;
annualRevenueCNY=periodRevenueCNY/periodFraction;
annualOperatingCostCNY=periodOperatingCostCNY/periodFraction;
annualPenaltyCostCNY=periodPenaltyCostCNY/periodFraction;
s=struct;
s.analysisLifeYear=life;
s.discountRate=r;
s.capitalRecoveryFactor=crf;
s.periodAnnualizationFactor=1/periodFraction;
s.grossCapexCNY=sum(capexCNY);
s.constructionPeriodYear=constructionYear;
s.constructionFinancingCNY=sum(constructionFinancingCNY);
s.financedCapexCNY=sum(financedCapexCNY);
s.annualDepreciationCNY=sum(annualDepreciationCNY);
s.annualFinancingCostCNY=sum(annualFinancingCNY);
s.annualFixedOMCNY=sum(fixedOMAnnualCNY);
s.replacementPresentValueCNY=sum(replacementPVCNY);
s.annualReplacementReserveCNY=sum(annualReplacementRecoveryCNY);
s.periodDepreciationCNY=s.annualDepreciationCNY*periodFraction;
s.periodFinancingCostCNY=s.annualFinancingCostCNY*periodFraction;
s.periodFixedOMCNY=s.annualFixedOMCNY*periodFraction;
s.periodReplacementReserveCNY=s.annualReplacementReserveCNY*periodFraction;
s.annualEquivalentRevenueCNY=annualRevenueCNY;
s.annualEquivalentOperatingCostCNY=annualOperatingCostCNY;
s.annualEquivalentPenaltyCostCNY=annualPenaltyCostCNY;
s.revenuePresentValueCNY=annualRevenueCNY*annuity;
s.operatingCostPresentValueCNY=annualOperatingCostCNY*annuity;
s.fixedOMPresentValueCNY=s.annualFixedOMCNY*annuity;
s.lifecycleCostPresentValueCNY=s.financedCapexCNY+s.replacementPresentValueCNY+ ...
    s.operatingCostPresentValueCNY+s.fixedOMPresentValueCNY;
s.lifecycleNPVAfterPenaltyCNY=s.revenuePresentValueCNY- ...
    s.lifecycleCostPresentValueCNY;
s.lifecycleNPVBeforePenaltyCNY=s.lifecycleNPVAfterPenaltyCNY+ ...
    annualPenaltyCostCNY*annuity;
s.equivalentAnnualNetAfterPenaltyCNY=annualRevenueCNY- ...
    annualOperatingCostCNY-s.annualFixedOMCNY- ...
    sum(annualInitialCapitalRecoveryCNY)-s.annualReplacementReserveCNY;
s.annualizationStatus='REPRESENTATIVE_PERIOD_REPEATED_ASSUMPTION';
s.taxStatus='EXCLUDED_TAX_BASIS_UNDECIDED';
s.decommissioningStatus='EXCLUDED_NO_VERIFIED_PROJECT_QUOTE';
s.priceBasisStatus='MIXED_PUBLIC_PRICE_YEARS_FX_CONVERSION_ONLY_NO_CPI_ESCALATION';
s.cableTechnology=cableDesign.technology;
s.cableVoltageKV=cableDesign.voltageKV;
s.cableCircuitCount=cableDesign.circuitCount;
s.cableCapacityMW=installed.powerCableMW;
s.cableDistanceKm=distanceKm;
s.hydrogenStorageInstalledKg=h2StorageKg;
s.assetMode=char(cfg.scenario.outputMode);
s.sourceNotice=l.meta.boundaryNotice;
end

function value=capital_recovery_factor(r,n)
if r==0, value=1/n; else, value=r*(1+r)^n/((1+r)^n-1); end
end

function value=discounted_events(eventCost,years,r)
value=sum(eventCost./((1+r).^years));
end

function value=construction_financing_fraction(r,n)
if n<=0 || r==0, value=0; return; end
midpoints=(0.5:1:(n-0.5));
value=mean((1+r).^(n-midpoints)-1);
end

function installed=installed_capacity(cfg)
installed=struct( ...
    'windMW',cfg.source.windCapacityMW, ...
    'pvMW',cfg.source.pvCapacityMW, ...
    'tidalMW',cfg.source.tidalCapacityMW, ...
    'bessPowerMW',cfg.bess.powerMW, ...
    'bessEnergyMWh',cfg.bess.energyMWh, ...
    'electrolyzerMW',cfg.hydrogen.electrolyzerRatedMW, ...
    'hydrogenStorageKg',cfg.hydrogen.storageMaxKg, ...
    'computeITMW',cfg.compute.itCapacityMW, ...
    'powerCableMW',cfg.output.cableSendCapacityMW, ...
    'powerCableDistanceKm',cfg.output.cableDistanceKm, ...
    'fiberCableDistanceKm',cfg.output.cableDistanceKm);
if isfield(cfg,'capacity') && isfield(cfg.capacity,'installed')
    names=fieldnames(cfg.capacity.installed);
    for k=1:numel(names)
        installed.(names{k})=cfg.capacity.installed.(names{k});
    end
end
end

function [cableCNY,stationCNY,design]=power_cable_capex(capacityMW,distanceKm,l)
if capacityMW<=0 || distanceKm<=0
    cableCNY=0; stationCNY=0;
    design=struct('technology','DISABLED','voltageKV',0,'circuitCount',0);
    return;
end
kmPerMile=1.609344;
if distanceKm<=l.cableHVACCrossoverKm
    ratingMW=l.cable220KVCircuitRatingMW;
    circuitCount=ceil(capacityMW/ratingMW);
    cableUSD=l.cable220KVHVACUSDPerMile*distanceKm/kmPerMile*circuitCount;
    stationUSD=l.hvacSubstationUSD*circuitCount;
    technology='220_KV_HVAC';
    voltageKV=220;
elseif capacityMW<=l.cable320KVCircuitRatingMW
    ratingMW=l.cable320KVCircuitRatingMW; %#ok<NASGU>
    circuitCount=ceil(capacityMW/l.cable320KVCircuitRatingMW);
    cableUSD=l.cable320KVHVDCUSDPerMile*distanceKm/kmPerMile*circuitCount;
    stationUSD=(l.converterStationCount*l.hvdc320ConverterUSDPerStation+ ...
        l.hvdc320ConstructionUSD)*circuitCount;
    technology='320_KV_HVDC_MONOPOLE';
    voltageKV=320;
else
    circuitCount=ceil(capacityMW/l.cable525KVCircuitRatingMW);
    cableUSD=l.cable525KVHVDCUSDPerMile*distanceKm/kmPerMile*circuitCount;
    stationUSD=(l.converterStationCount*l.hvdc525ConverterUSDPerStation+ ...
        l.hvdc525ConstructionUSD)*circuitCount;
    technology='525_KV_HVDC_BIPOLE';
    voltageKV=525;
end
cableCNY=cableUSD*l.usdToCNY;
stationCNY=stationUSD*l.usdToCNY;
design=struct('technology',technology,'voltageKV',voltageKV, ...
    'circuitCount',circuitCount);
end

function enabled=asset_enabled(cfg,name,defaultValue)
enabled=defaultValue;
if isfield(cfg,'assetEnabled') && isfield(cfg.assetEnabled,name)
    enabled=logical(cfg.assetEnabled.(name));
end
end
