function [out,report]=run_all_channel_validation_v4()
%RUN_ALL_CHANNEL_VALIDATION_V4 Forty-eight-hour all-channel stress sequence.
% All capacities and phase multipliers are assumptions for interface and
% strategy validation, not a recommended engineering design.
here=fileparts(mfilename('fullpath'));
v4Root=fileparts(here);
addpath(v4Root, ...
    fullfile(v4Root,'library','4.2变量与接口'), ...
    fullfile(v4Root,'modules','4.3_source','integration'));

cfg=common_config_4_2('interface_smoke');
cfg.meta.parameterVersion='chapter5_all_channel_48h_assumption_v1';
cfg.time.dispatchHorizonH=48;
cfg.source.windCapacityMW=680;
cfg.source.pvCapacityMW=80;
cfg.source.tidalCapacityMW=40;
cfg.source.totalCapacityMW=800;
cfg.bess.powerMW=80;
cfg.bess.energyMWh=160;
cfg.bess.chargeMaxMW=80;
cfg.bess.dischargeMaxMW=80;
cfg.bess.socInitial=0.50;
cfg.bess.terminalRule='minimum';
cfg.bess.terminalTargetSOC=0.20;
cfg.hydrogen.electrolyzerRatedMW=100;
cfg.hydrogen.electrolyzerMinMW=20;
cfg.hydrogen.storageMaxKg=200000;
cfg.hydrogen.storageInitialKg=0;
cfg.hydrogen.deliveryDemandKgPerH=2500;
cfg.hydrogen.pipeCapacityKgPerH=0;
cfg.hydrogen.shipCapacityKgPerH=5000;
cfg.output.cableSendCapacityMW=200;
cfg.output.gridAcceptMaxMW=200;
validate_common_schema_4_2(cfg,true);

sourcePacket=build_all_channel_source_scenario_4_3(cfg,48);
dispatchOptions=struct( ...
    'computeRequestMW',120, ...
    'computeFirmRequestMW',0, ...
    'h2DeliveryCapKgPerH',2500, ...
    'h2SalePriceCNYPerKg',20, ... % [假设值，待企业调研校准]
    'h2VariableCostCNYPerKg',3.5, ...
    'electricityPriceCNYPerMWh',347);
options=struct('cfg',cfg,'sourcePacket',sourcePacket, ...
    'dispatchOptions',dispatchOptions,'computeMode','power_following', ...
    'scenarioId','chapter5_all_channel_48h', ...
    'outputDir',fullfile('outputs','chapter5_all_channel_48h'));
out=run_v4_integration(options);

dt=cfg.time.dispatchStepH;
p43=out.packet4_3; p44=out.packet4_4; p45=out.packet4_5;
p46=out.packet4_6; p47=out.packet4_7;
tol=cfg.commonBus.balanceToleranceMW;

checkName=[ ...
    "早期新能源不足触发电池放电"; ...
    "上升阶段触发电池充电"; ...
    "算力柔性负荷启动"; ...
    "海缆达到送端上限"; ...
    "富余电力触发制氢"; ...
    "电解槽达到额定功率"; ...
    "全通道饱和后出现弃电"; ...
    "骤降阶段电池放电"; ...
    "骤降阶段算力下降"; ...
    "骤降阶段不继续弃电"; ...
    "不存在弃电与电气/海洋缺供并存"; ...
    "船运氢气交付非零"; ...
    "公共母线残差合格"];
passed=false(size(checkName));
evidence=strings(size(checkName));

passed(1)=any(p45.ports.bessDischarge.actualMW(1:6)>tol);
evidence(1)=sprintf('max early discharge %.3f MW',max(p45.ports.bessDischarge.actualMW(1:6)));
passed(2)=any(p45.ports.bessCharge.actualMW(7:20)>tol);
evidence(2)=sprintf('max rise charge %.3f MW',max(p45.ports.bessCharge.actualMW(7:20)));
passed(3)=any(p46.ports.dcFacility.actualMW(7:30)>tol);
evidence(3)=sprintf('max compute %.3f MW',max(p46.ports.dcFacility.actualMW));
passed(4)=max(p47.ports.exportSend.actualMW)>=cfg.output.cableSendCapacityMW-1e-6;
evidence(4)=sprintf('max cable send %.3f MW',max(p47.ports.exportSend.actualMW));
passed(5)=any(p45.ports.electrolyzer.actualMW>tol);
evidence(5)=sprintf('electrolyzer energy %.3f MWh',sum(p45.ports.electrolyzer.actualMW)*dt);
passed(6)=max(p45.ports.electrolyzer.actualMW)>=cfg.hydrogen.electrolyzerRatedMW-1e-6;
evidence(6)=sprintf('max electrolyzer %.3f MW',max(p45.ports.electrolyzer.actualMW));
passed(7)=any(p44.state.pSpillActualMW>tol);
evidence(7)=sprintf('spill energy %.3f MWh',sum(p44.state.pSpillActualMW)*dt);
passed(8)=any(p45.ports.bessDischarge.actualMW(39:44)>tol);
evidence(8)=sprintf('max drop discharge %.3f MW',max(p45.ports.bessDischarge.actualMW(39:44)));
preDrop=max(p46.ports.dcFacility.actualMW(31:38));
dropMax=max(p46.ports.dcFacility.actualMW(39:44));
passed(9)=dropMax<preDrop-1e-6;
evidence(9)=sprintf('compute pre/drop %.3f / %.3f MW',preDrop,dropMax);
passed(10)=all(p44.state.pSpillActualMW(39:44)<=tol);
evidence(10)=sprintf('max drop spill %.3e MW',max(p44.state.pSpillActualMW(39:44)));
totalUnserved=out.dispatchActual.totalUnservedMW;
passed(11)=~any(p44.state.pSpillActualMW>tol & totalUnserved>tol);
evidence(11)=sprintf('coexistence count %d',sum(p44.state.pSpillActualMW>tol & totalUnserved>tol));
passed(12)=sum(p47.product.h2ShipDeliveredKg)>0;
evidence(12)=sprintf('ship-delivered H2 %.3f kg',sum(p47.product.h2ShipDeliveredKg));
passed(13)=max(abs(p44.state.pBusResidualMW))<=tol;
evidence(13)=sprintf('max residual %.3e MW',max(abs(p44.state.pBusResidualMW)));

report=table(checkName,passed,evidence);
disp(report);
assert(all(passed),'All-channel validation failed.');
writetable(report,fullfile(v4Root,'outputs','chapter5_all_channel_48h', ...
    'all_channel_validation_report.csv'));

summary=table( ...
    sum(p43.ports.source.actualMW)*dt, ...
    sum(p45.ports.bessCharge.actualMW)*dt, ...
    sum(p45.ports.bessDischarge.actualMW)*dt, ...
    sum(p46.ports.dcFacility.actualMW)*dt, ...
    sum(p47.ports.exportSend.actualMW)*dt, ...
    sum(p45.product.h2ProductionKg), ...
    sum(p47.product.h2ShipDeliveredKg), ...
    sum(p44.state.pSpillActualMW)*dt, ...
    sum(totalUnserved)*dt, ...
    'VariableNames',{'SourceMWh','BessChargeMWh','BessDischargeMWh', ...
    'ComputeMWh','CableSendMWh','H2ProducedKg','H2ShipDeliveredKg', ...
    'SpillMWh','TotalUnservedMWh'});
writetable(summary,fullfile(v4Root,'outputs','chapter5_all_channel_48h', ...
    'all_channel_summary.csv'));
end
