function report=run_chapter5_readiness_audit()
%RUN_CHAPTER5_READINESS_AUDIT Non-blocking readiness audit for Chapter 5.
% This audit distinguishes interface correctness from comparative-study
% readiness. It reports gaps and does not claim that a failed readiness
% check is a numerical integration failure.

here=fileparts(mfilename('fullpath'));
v4Root=fileparts(here);
addpath(v4Root, ...
    fullfile(v4Root,'library','4.2变量与接口'), ...
    fullfile(v4Root,'integration','common'), ...
    fullfile(v4Root,'modules','4.6_compute','integration'), ...
    fullfile(v4Root,'modules','4.8_objectives','model'));

out=run_v4_integration();
cfg=out.cfg;
p43=out.packet4_3; p44=out.packet4_4; p45=out.packet4_5;
p46=out.packet4_6; p47=out.packet4_7;
params=v4_objective_parameters_4_8();
dt=cfg.time.dispatchStepH;

dimension=strings(0,1); checkName=strings(0,1); status=strings(0,1);
evidence=strings(0,1); impact=strings(0,1);

add("数值闭合","公共母线实际功率平衡", ...
    passfail(max(abs(p44.state.pBusResidualMW))<=cfg.commonBus.balanceToleranceMW), ...
    sprintf('max residual = %.3e MW',max(abs(p44.state.pBusResidualMW))), ...
    "可支撑小时级能量守恒核对");

N=numel(p43.axis.timeH);
add("时间范围","至少168 h多日场景",passfail(N>=168), ...
    sprintf('current horizon = %d h',N), ...
    "不足时不能验证连续低风、跨日移峰和船运窗口");
add("时间范围","8760 h年度经济与消纳分析",passfail(N>=8760), ...
    sprintf('current horizon = %d h',N), ...
    "不足时不能计算年度收益、弃电率和容量因子");

bessInitial=cfg.bess.socInitial;
bessEnd=p45.state.bessSOC(end);
add("状态公平性","电池期末SOC回归初值", ...
    passfail(abs(bessEnd-bessInitial)<=1e-6), ...
    sprintf('SOC initial/end = %.6f / %.6f',bessInitial,bessEnd), ...
    "不满足时方案可通过透支初始电量获得虚假收益");

h2Initial=cfg.hydrogen.storageInitialKg;
h2End=p45.state.h2InventoryKg(end);
add("状态公平性","储氢期末库存回归初值", ...
    passfail(abs(h2End-h2Initial)<=1e-6), ...
    sprintf('H2 inventory initial/end = %.3f / %.3f kg',h2Initial,h2End), ...
    "不满足时氢方案会把初始库存当作无成本产品");

boundaryMin=cfg.compute.facilityMinMW;
responseMin=double(p46.service.pDCOnlineMinMW(:));
minMismatch=max(abs(responseMin-boundaryMin));
add("接口可行域","4.6预发布在线底座与响应一致", ...
    passfail(minMismatch<=cfg.commonBus.balanceToleranceMW), ...
    sprintf('published = %.6f MW; response range = %.6f..%.6f MW', ...
        boundaryMin,min(responseMin),max(responseMin)), ...
    "不一致会使4.9错误判断算力启停和刚性保供");

electricityMWh=sum(p47.service.pCableReceiveMW)*dt;
h2ProducedKg=sum(p45.product.h2ProductionKg);
h2DeliveredKg=sum(p47.product.h2DeliveredKg);
computeMWhCS=sum(p47.service.computeDeliveredMWhCS);
marineMWh=sum(p47.ports.marine.actualMW)*dt;
add("通道覆盖","电力外送通道非零",passfail(electricityMWh>1e-9), ...
    sprintf('delivered electricity = %.6f MWh',electricityMWh), ...
    "当前场景不能验证电力外输方案");
add("通道覆盖","当期制氢通道非零",passfail(h2ProducedKg>1e-9), ...
    sprintf('produced/delivered H2 = %.3f / %.3f kg',h2ProducedKg,h2DeliveredKg), ...
    "只有库存交付不能验证风电制氢与船运方案");
add("通道覆盖","算力交付通道非零",passfail(computeMWhCS>1e-9), ...
    sprintf('delivered compute = %.6f MWh-CS',computeMWhCS), ...
    "可用于算力链路接口验证");
add("通道覆盖","海洋用能通道非零",passfail(marineMWh>1e-9), ...
    sprintf('served marine energy = %.6f MWh',marineMWh), ...
    "可用于海洋刚柔负荷接口验证");

releasedMWh=sum(out.redispatchAfterCompute.remainingReleasedMW)*dt;
exportHeadroomMW=max(0,min(cfg.output.cableSendCapacityMW, ...
    cfg.output.gridAcceptMaxMW)-p47.ports.exportSend.actualMW);
missedRedispatch=(releasedMWh>1e-9) && any(exportHeadroomMW>1e-9);
add("调度完整性","4.6释放功率继续分配到剩余价值通道", ...
    passfail(~missedRedispatch), ...
    sprintf('remaining released = %.6f MWh; spill = %.6f MWh', ...
        releasedMWh,sum(p44.state.pSpillActualMW)*dt), ...
    "当前释放功率只补海洋负荷，可能在海缆仍有余量时高估弃电");
add("调度完整性","电力/氢气/算力统一边际价值排序", ...
    "NOT_READY", ...
    "4.9 fixes compute before comparing H2 net value with electricity value", ...
    "混合方案当前是优先级规则，不是三产品价值最优");
add("氢储船运","管道与船运分流、船期和成本独立计量", ...
    "BLOCKED", ...
    "4.7 bridge uses pipe-first allocation and returns only aggregate H2 delivery", ...
    "当前结果不能代表独立氢储船运方案");

add("经济性","年度化CAPEX已配置", ...
    passfail(params.economic.annualizedCapitalCNY>0), ...
    sprintf('annualizedCapitalCNY = %.3f',params.economic.annualizedCapitalCNY), ...
    "为0时不能比较电缆、制氢船运、算力和混合方案");
sourceCost=params.economic.sourceVariableOMCNYPerMWhByType;
add("经济性","风光潮分源成本参数完整",passfail(all(isfinite(sourceCost))), ...
    sprintf('source cost vector = %s CNY/MWh',mat2str(sourceCost)), ...
    "缺失时不能比较供能组合成本及容量策略");
add("经济性","初始氢库存成本或机会价值已计入", ...
    passfail(~(h2DeliveredKg>h2ProducedKg+1e-9)), ...
    sprintf('delivered minus produced = %.3f kg',h2DeliveredKg-h2ProducedKg), ...
    "当前经济目标会确认初始库存带来的收入但不确认其形成成本");

availableMWh=sum(p43.ports.source.maxMW)*dt;
spillMWh=sum(p44.state.pSpillActualMW)*dt;
curtailmentRate=spillMWh/max(availableMWh,eps);
add("消纳","弃电量及分母可追溯", ...
    passfail(isfinite(curtailmentRate) && curtailmentRate>=0 && curtailmentRate<=1), ...
    sprintf('spill/available = %.6f / %.6f = %.4f%%', ...
        spillMWh,availableMWh,100*curtailmentRate), ...
    "当前仅为24 h指标，年度比较仍需同源8760 h序列");

add("碳减排","统一反事实基准与替代排放因子", ...
    "BLOCKED","No counterfactual baseline packet or avoided-emission field", ...
    "当前只能给出项目排放代理值，不能给出碳减排量");
add("稳定性","频率/电压/故障动态指标", ...
    "BLOCKED","No frequency nadir, RoCoF, voltage deviation, FRT or black-start result", ...
    "小时级功率残差不能替代构网稳定性验证");
add("方案可比性","电力/氢储船运/算力/混合统一场景入口", ...
    "BLOCKED","run_v4_integration has no strategy/scenario input argument", ...
    "尚不能自动保证四方案使用同一资源、初态、期末状态和可靠性约束");

report=table(dimension,checkName,status,evidence,impact, ...
    'VariableNames',{'Dimension','Check','Status','Evidence','Chapter5Impact'});
writetable(report,fullfile(here,'chapter5_readiness_report.csv'));
disp(report);

    function add(d,c,s,e,i)
        dimension(end+1,1)=string(d);
        checkName(end+1,1)=string(c);
        status(end+1,1)=string(s);
        evidence(end+1,1)=string(e);
        impact(end+1,1)=string(i);
    end
end

function s=passfail(tf)
if tf, s="PASS"; else, s="NOT_READY"; end
end
