function cfg=v4_apply_unified_capacity_case_4_2(cfg,outputMode)
%V4_APPLY_UNIFIED_CAPACITY_CASE_4_2 Unified 24 h/48 h installed-capacity case.
% Extends, but does not replace, the frozen 4.2 interface. Legacy capacity
% fields remain the physical/runtime limits consumed by existing modules.
if nargin<2 || isempty(outputMode), outputMode='M'; end
outputMode=upper(char(outputMode));
assert(any(strcmp(outputMode,{'E','H','C','M'})), ...
    'outputMode must be E, H, C or M.');

unitFacilityMaxMW=7.618080005; % [模型仿真结果] current 4.6 single unit
unitITMaxMW=7.08;              % [模型仿真结果] current 4.6 single unit
unitCount=16;                  % [假设值，待企业调研校准]
installedComputeFacilityMW=unitCount*unitFacilityMaxMW;
installedComputeITMW=unitCount*unitITMaxMW;

enabled=struct( ...
    'floatingWind',true,'marineFloatingPV',true,'tidalStream',true, ...
    'BESS',true,'PEMElectrolyzer',any(outputMode==['H','M']), ...
    'hydrogenStorage',any(outputMode==['H','M']), ...
    'subseaCompute',any(outputMode==['C','M']), ...
    'powerExportCable',any(outputMode==['E','M']), ...
    'converterAndSubstation',any(outputMode==['E','M']), ...
    'fiberCable',any(outputMode==['C','M']));

cfg.scenario.outputMode=outputMode;
cfg.assetEnabled=enabled;
cfg.capacity=struct;
cfg.capacity.interfaceLimit=struct( ...
    'sourceMW',800,'bessPowerMW',80,'bessEnergyMWh',160, ...
    'electrolyzerMW',100,'hydrogenStoragePhysicalUpperKg',200000, ...
    'computeFacilityMW',120,'powerCableMW',200, ...
    'fiberServiceMWhCSPerH',120);
cfg.capacity.installed=struct( ...
    'windMW',680,'pvMW',80,'tidalMW',40,'sourceMW',800, ...
    'bessPowerMW',80,'bessEnergyMWh',160, ...
    'electrolyzerMW',100, ...
    'hydrogenStorageKg',NaN, ... % determined from process buffer and inventory path
    'computeUnitCount',unitCount, ...
    'computeUnitFacilityMaxMW',unitFacilityMaxMW, ...
    'computeUnitITMaxMW',unitITMaxMW, ...
    'computeFacilityMW',installedComputeFacilityMW, ...
    'computeITMW',installedComputeITMW, ...
    'powerCableMW',200,'powerCableDistanceKm',200, ...
    'powerCableVoltageKV',320,'fiberCableDistanceKm',200);
cfg.capacity.dispatchRequest=struct( ...
    'computeMW',120,'computeFirmMW',0, ...
    'hydrogenDeliveryKgPerH',2500,'marineMW',18);
cfg.capacity.status=struct( ...
    'capacityCase','UNIFIED_800MW_MIXED_24H_48H_V1', ...
    'interfaceMeaning','Hard exchange/port ceiling', ...
    'installedMeaning','Physical asset nameplate used by 4.8 CAPEX', ...
    'dispatchMeaning','Scenario request sent by 4.9', ...
    'computeAggregationStatus','16 identical 4.6 units [假设值，待企业调研校准]', ...
    'hydrogenStorageSizingStatus', ...
        'Installed kg=max(rated-production process buffer, committed maximum inventory)');

% Existing modules continue to consume the frozen legacy fields.
cfg.source.windCapacityMW=cfg.capacity.installed.windMW;
cfg.source.pvCapacityMW=cfg.capacity.installed.pvMW;
cfg.source.tidalCapacityMW=cfg.capacity.installed.tidalMW;
cfg.source.totalCapacityMW=cfg.capacity.installed.sourceMW;
cfg.bess.powerMW=cfg.capacity.installed.bessPowerMW;
cfg.bess.energyMWh=cfg.capacity.installed.bessEnergyMWh;
cfg.bess.chargeMaxMW=cfg.capacity.interfaceLimit.bessPowerMW;
cfg.bess.dischargeMaxMW=cfg.capacity.interfaceLimit.bessPowerMW;
cfg.hydrogen.electrolyzerRatedMW=cfg.capacity.interfaceLimit.electrolyzerMW;
cfg.hydrogen.electrolyzerMinMW=20;
cfg.hydrogen.storageMaxKg= ...
    cfg.capacity.interfaceLimit.hydrogenStoragePhysicalUpperKg;
cfg.hydrogen.minimumProcessBufferHours=1; % [假设值，待企业调研校准]
cfg.hydrogen.deliveryDemandKgPerH= ...
    cfg.capacity.dispatchRequest.hydrogenDeliveryKgPerH;
cfg.compute.facilityMaxMW=cfg.capacity.interfaceLimit.computeFacilityMW;
cfg.compute.itCapacityMW=cfg.capacity.installed.computeITMW;
cfg.compute.fiberServiceCapacityMWhCSPerH= ...
    cfg.capacity.interfaceLimit.fiberServiceMWhCSPerH;
cfg.output.cableSendCapacityMW=cfg.capacity.interfaceLimit.powerCableMW;
cfg.output.gridAcceptMaxMW=cfg.capacity.interfaceLimit.powerCableMW;
cfg.output.cableDistanceKm=cfg.capacity.installed.powerCableDistanceKm;
cfg.meta.parameterVersion=[cfg.meta.parameterVersion ...
    '_unified_capacity_' lower(outputMode)];
end
