function report=test_v4_dispatch_scenarios_4_9()
%TEST_V4_DISPATCH_SCENARIOS_4_9 Targeted surplus and sudden-drop regression.
% All numerical values use interface_smoke assumptions and are not an
% engineering capacity recommendation.
modelDir=fileparts(mfilename('fullpath'));
v4Root=fileparts(fileparts(fileparts(modelDir)));
addpath(fullfile(v4Root,'library','4.2变量与接口'), ...
    fullfile(v4Root,'integration','common'), ...
    fullfile(v4Root,'modules','4.3_source','integration'), ...
    fullfile(v4Root,'modules','4.5_storage_hydrogen','integration'), ...
    fullfile(v4Root,'modules','4.6_compute','integration'),modelDir);

cfg=common_config_4_2('interface_smoke');
cfg=v4_apply_4_5_parameter_overlay(cfg);
cfg.bess.terminalRule='minimum';
cfg.bess.terminalTargetSOC=0.20;
[p43,~]=v4_source_adapter(cfg,'BOUNDARY');
timeH=p43.axis.timeH(:); N=numel(timeH);
p46=v4_compute_boundary_4_6(cfg,timeH);
state0=struct('bessEnergyMWh',cfg.bess.socInitial*cfg.bess.energyMWh, ...
    'h2InventoryKg',cfg.hydrogen.storageInitialKg);
[p45,~]=v4_storage_hydrogen_boundary_4_5(cfg,timeH,state0, ...
    struct('gfmReservePowerMW',cfg.bess.gfmReservePowerMW, ...
    'gfmReserveEnergyMWh',cfg.bess.gfmReserveEnergyMWh, ...
    'blackStartSOCMin',cfg.bess.blackStartSOCMin));

% 23 h surplus followed by a one-hour renewable collapse.
p43.ports.source.actualMW(:)=700; % [假设值，待企业调研校准]
p43.ports.source.actualMW(end)=0;
options=struct('computeRequestMW',80); % [假设值，待企业调研校准]
[~,d]=v4_dispatch_4_9(cfg,p43,p46,options,p45);

assert(max(d.req45.electrolyzerMW)>=cfg.hydrogen.electrolyzerRatedMW-1e-9, ...
    'Surplus case did not raise the electrolyzer to rated power.');
assert(any(d.spillPlannedMW(1:end-1)>0), ...
    'Fully saturated surplus case did not produce spill.');
assert(d.req45.bessDischargeMW(end)>0, ...
    'Sudden-drop terminal hour did not trigger battery discharge.');
assert(d.computeRequestedMW(end)<d.computeRequestedMW(end-1), ...
    'Sudden-drop terminal hour did not reduce flexible compute.');
assert(d.spillPlannedMW(end)<=cfg.commonBus.balanceToleranceMW, ...
    'Sudden-drop terminal hour incorrectly continued spilling.');
assert(~any(d.spillPlannedMW>cfg.commonBus.balanceToleranceMW & ...
    d.unservedPlannedMW>cfg.commonBus.balanceToleranceMW), ...
    'Planned spill and dispatchable unserved load coexist.');

report=table(true,max(d.req45.electrolyzerMW),d.req45.bessDischargeMW(end), ...
    d.computeRequestedMW(end-1),d.computeRequestedMW(end),d.spillPlannedMW(end), ...
    'VariableNames',{'Passed','ElectrolyzerMaxMW','TerminalBessDischargeMW', ...
    'ComputeBeforeDropMW','ComputeAfterDropMW','TerminalSpillMW'});
disp(report);
end
