function report=test_v4_terminal_path_rules_4_9()
%TEST_V4_TERMINAL_PATH_RULES_4_9 Terminal-only, not all-period, regression.

modelDir=fileparts(mfilename('fullpath'));
v4Root=fileparts(fileparts(fileparts(modelDir)));
interfaceFolders=dir(fullfile(v4Root,'library','4.2*'));
assert(~isempty(interfaceFolders), ...
    'Cannot locate the frozen 4.2 interface folder.');
addpath(fullfile(interfaceFolders(1).folder,interfaceFolders(1).name), ...
    fullfile(v4Root,'integration','common'), ...
    fullfile(v4Root,'modules','4.3_source','integration'), ...
    fullfile(v4Root,'modules','4.5_storage_hydrogen','integration'), ...
    fullfile(v4Root,'modules','4.6_compute','integration'));

cfg=common_config_4_2('interface_smoke');
cfg=v4_apply_4_5_parameter_overlay(cfg);
[p43,~]=v4_source_adapter(cfg,'BOUNDARY');
timeH=p43.axis.timeH(:);
p46=v4_compute_boundary_4_6(cfg,timeH);

% BESS: discharge below the cyclic target early, then restore at horizon end.
stateBess=struct('bessEnergyMWh',30,'h2InventoryKg',0);
[p45Bess,~]=v4_storage_hydrogen_boundary_4_5( ...
    cfg,timeH,stateBess,struct);
p43Bess=p43;
p43Bess.ports.source.actualMW(:)=700;
p43Bess.ports.source.actualMW(1)=0;
[~,dBess]=v4_dispatch_4_9(cfg,p43Bess,p46, ...
    struct('computeRequestMW',0),p45Bess);

% H2: withdraw opening inventory in hour 1, produce later, and restore only
% at the final boundary. Intermediate inventory may remain below target.
cfgH=cfg;
cfgH.hydrogen.terminalRule='cyclic';
stateH2=struct('bessEnergyMWh', ...
    cfgH.bess.socInitial*cfgH.bess.energyMWh, ...
    'h2InventoryKg',1000);
[p45H2,~]=v4_storage_hydrogen_boundary_4_5( ...
    cfgH,timeH,stateH2,struct);
p43H2=p43;
p43H2.ports.source.actualMW(:)=70;
p43H2.ports.source.actualMW(1)=0;
[~,dH2]=v4_dispatch_4_9(cfgH,p43H2,p46, ...
    struct('computeRequestMW',0, ...
    'electricityPriceCNYPerMWh',2000),p45H2);

% Direct API: 4.9 receives raw frozen config plus the explicit 4.5 packet.
rawCfg=common_config_4_2('interface_smoke');
[p43Raw,~]=v4_source_adapter(rawCfg,'BOUNDARY');
p46Raw=v4_compute_boundary_4_6(rawCfg,p43Raw.axis.timeH);
[p45Raw,~]=v4_storage_hydrogen_boundary_4_5( ...
    rawCfg,p43Raw.axis.timeH,[],struct);
[~,dRaw]=v4_dispatch_4_9( ...
    rawCfg,p43Raw,p46Raw,struct,p45Raw);

checkName=[ ...
    "BESS cyclic target is not imposed as an all-hour floor"; ...
    "BESS cyclic target is restored exactly at the horizon"; ...
    "H2 cyclic target is not imposed as an all-hour floor"; ...
    "H2 cyclic target is restored exactly at the horizon"; ...
    "both repaired paths preserve physical bounds"; ...
    "4.9 direct API uses the explicit 4.5 packet without overlay coupling"];
passed=false(size(checkName)); evidence=strings(size(checkName));
passed(1)=min(dBess.bessEnergyPlanMWh)< ...
    dBess.bessTerminalTargetMWh-1e-6;
evidence(1)=sprintf('minimum/target %.6f/%.6f MWh', ...
    min(dBess.bessEnergyPlanMWh),dBess.bessTerminalTargetMWh);
passed(2)=dBess.bessTerminalOK && ...
    abs(dBess.bessEnergyPlanMWh(end)- ...
    dBess.bessTerminalTargetMWh)<=1e-7;
evidence(2)=sprintf('terminal residual %.3e MWh', ...
    dBess.bessEnergyPlanMWh(end)-dBess.bessTerminalTargetMWh);
passed(3)=min(dH2.h2InventoryPlanKg)< ...
    dH2.h2TerminalTargetKg-1e-6;
evidence(3)=sprintf('minimum/target %.6f/%.6f kg', ...
    min(dH2.h2InventoryPlanKg),dH2.h2TerminalTargetKg);
passed(4)=dH2.h2TerminalOK && ...
    abs(dH2.h2InventoryPlanKg(end)- ...
    dH2.h2TerminalTargetKg)<=1e-6;
evidence(4)=sprintf('terminal residual %.3e kg', ...
    dH2.h2InventoryPlanKg(end)-dH2.h2TerminalTargetKg);
physicalFloor=cfg.bess.socMin*cfg.bess.energyMWh+ ...
    dBess.gfmReserveEnergyMWh;
passed(5)=all(dBess.bessEnergyPlanMWh>=physicalFloor-1e-9) && ...
    all(dH2.h2InventoryPlanKg>=-1e-9) && ...
    all(dH2.h2InventoryPlanKg<=cfgH.hydrogen.storageMaxKg+1e-9);
evidence(5)=sprintf('BESS floor %.3f MWh, H2 range %.3f..%.3f kg', ...
    physicalFloor,min(dH2.h2InventoryPlanKg), ...
    max(dH2.h2InventoryPlanKg));
passed(6)=dRaw.bessTerminalOK && dRaw.h2TerminalOK && ...
    isfinite(dRaw.bessStandingLossFractionPerH);
evidence(6)=sprintf('rules %s/%s, reserve %.3f MW', ...
    dRaw.bessTerminalRule,dRaw.h2TerminalRule,dRaw.gfmReservePowerMW);

report=table(checkName,passed,evidence);
disp(report);
assert(all(passed),'Terminal-only path regression failed.');
end
