function [out,report]=run_4_5_standalone_validation(outputDir)
%RUN_4_5_STANDALONE_VALIDATION Three-timescale 4.5 acceptance run.
%
% Cases:
%   1) 72 h BESS/electrolyzer/H2 physical state transition;
%   2) seconds-scale WECC REGFM_B1 proxy and black-start sequence;
%   3) continuous 8760 h seasonal hydrogen inventory mechanism.
%
% Synthetic sequences and uncalibrated controller/storage values are
% [assumption values, pending enterprise/vendor calibration].

here=fileparts(mfilename('fullpath'));
v4Root=fileparts(fileparts(here));
addpath(fullfile(here,'model'),fullfile(here,'integration'), ...
    fullfile(v4Root,'integration','common'), ...
    fullfile(v4Root,'library','4.2变量与接口'));
if nargin<1 || isempty(outputDir)
    outputDir=fullfile(here,'outputs','multiscale_validation');
end
if ~isfolder(outputDir), mkdir(outputDir); end

cfg=common_config_4_2('interface_smoke');
cfg=v4_apply_4_5_parameter_overlay(cfg);
cfg.meta.parameterVersion='4.5_multiscale_mechanism_assumption_v1';

%% 72 h operational production and cyclic BESS state
time72=(0:71)';
ely72=[zeros(12,1);20*ones(12,1);50*ones(12,1); ...
    100*ones(12,1);4*ones(12,1);zeros(12,1)];
charge72=zeros(72,1); discharge72=zeros(72,1);
charge72(1)=10;
discharge72(2)=10*cfg.bess.etaCharge*cfg.bess.etaDischarge;
request72=struct( ...
    'bessChargeMW',charge72, ...
    'bessDischargeMW',discharge72, ...
    'electrolyzerMW',ely72);
state72=struct( ...
    'bessEnergyMWh',cfg.bess.socInitial*cfg.bess.energyMWh, ...
    'h2InventoryKg',0);
options72=struct( ...
    'electrolyzerMode','modular', ...
    'electrolyzerModuleRatedMW',20, ...
    'electrolyzerModuleMinMW',4, ...
    'electrolyzerModuleCount',5, ...
    'bessTerminalRule','cyclic', ...
    'bessTerminalTarget',state72.bessEnergyMWh, ...
    'h2TerminalRule','free', ...
    'enforceTerminal',true, ...
    'tolerance',1e-7);
operational=v4_storage_hydrogen_core_4_5( ...
    cfg,time72,request72,state72,zeros(72,1),options72);

% Explicit modular minimum-load check: 3 MW stays off; 4 MW starts one unit.
moduleRequest=struct( ...
    'bessChargeMW',zeros(2,1), ...
    'bessDischargeMW',zeros(2,1), ...
    'electrolyzerMW',[3;4]);
moduleCheck=v4_storage_hydrogen_core_4_5( ...
    cfg,[0;1],moduleRequest,state72,zeros(2,1), ...
    struct('electrolyzerMode','modular', ...
    'electrolyzerModuleRatedMW',20, ...
    'electrolyzerModuleMinMW',4, ...
    'electrolyzerModuleCount',5));

% A net-discharge case must be identified as terminal-infeasible.
badRequest=struct( ...
    'bessChargeMW',zeros(2,1), ...
    'bessDischargeMW',[5;0], ...
    'electrolyzerMW',zeros(2,1));
badTerminal=v4_storage_hydrogen_core_4_5( ...
    cfg,[0;1],badRequest,state72,zeros(2,1), ...
    struct('bessTerminalRule','cyclic', ...
    'bessTerminalTarget',state72.bessEnergyMWh, ...
    'h2TerminalRule','free','enforceTerminal',false));
terminalHardError=false;
try
    v4_storage_hydrogen_core_4_5( ...
        cfg,[0;1],badRequest,state72,zeros(2,1), ...
        struct('bessTerminalRule','cyclic', ...
        'bessTerminalTarget',state72.bessEnergyMWh, ...
        'h2TerminalRule','free','enforceTerminal',true));
catch ME
    terminalHardError=strcmp(ME.identifier,'BLUEHUB:TerminalConstraint45');
end

%% 4.5 BOUNDARY publication with explicit state and GFM reserve
[boundaryPacket,boundary]=v4_storage_hydrogen_boundary_4_5( ...
    cfg,time72,state72,struct( ...
    'gfmReservePowerMW',cfg.bess.gfmReservePowerMW, ...
    'gfmReserveEnergyMWh',cfg.bess.gfmReserveEnergyMWh, ...
    'blackStartSOCMin',cfg.bess.blackStartSOCMin));

%% Seconds-scale REGFM_B1 active/reactive load step
gfmParams=v4_gfm_parameters_4_5(cfg);
timeDynamic=(0:0.002:20)';
pBase=gfmParams.ratedMW-boundary.gfmReservePowerMW;
pStep=pBase*ones(size(timeDynamic)); qStep=zeros(size(timeDynamic));
pStep(timeDynamic>=2)=pBase+boundary.gfmReservePowerMW;
qStep(timeDynamic>=2)=2;
initialLoadAdmittance=complex(pBase,0)/gfmParams.ratedMVA;
initialInternalPhasor=1+complex(gfmParams.filterResistancePU, ...
    gfmParams.filterReactancePU)*initialLoadAdmittance;
stepScenario=struct( ...
    'timeS',timeDynamic, ...
    'pDemandMW',pStep, ...
    'qDemandMvar',qStep, ...
    'baseDispatchMW',pBase, ...
    'pReferencePU',pBase/gfmParams.ratedMVA, ...
    'initialInternalVoltagePU',abs(initialInternalPhasor), ...
    'initialVoltageIntegratorPU',abs(initialInternalPhasor), ...
    'initialFilteredVoltagePU',1, ...
    'initialAngleRad',angle(initialInternalPhasor), ...
    'reservedPowerMW',boundary.gfmReservePowerMW, ...
    'reservedEnergyMWh',boundary.gfmReserveEnergyMWh);
gfmStep=v4_gfm_regfm_b1_dynamic_4_5(gfmParams,stepScenario);

%% Two-minute continuous support using the same hourly reserve boundary
timeMinute=(0:0.004:120)';
pMinute=pBase*ones(size(timeMinute));
qMinute=zeros(size(timeMinute));
minuteEvent=timeMinute>=2 & timeMinute<118;
pMinute(minuteEvent)=pBase+2;
qMinute(minuteEvent)=0.5;
minuteScenario=struct( ...
    'timeS',timeMinute, ...
    'pDemandMW',pMinute, ...
    'qDemandMvar',qMinute, ...
    'baseDispatchMW',pBase, ...
    'pReferencePU',pBase/gfmParams.ratedMVA, ...
    'initialInternalVoltagePU',abs(initialInternalPhasor), ...
    'initialVoltageIntegratorPU',abs(initialInternalPhasor), ...
    'initialFilteredVoltagePU',1, ...
    'initialAngleRad',angle(initialInternalPhasor), ...
    'reservedPowerMW',boundary.gfmReservePowerMW, ...
    'reservedEnergyMWh',boundary.gfmReserveEnergyMWh);
gfmMinute=v4_gfm_regfm_b1_dynamic_4_5(gfmParams,minuteScenario);

%% Black-start behavioral sequence: establish V/f, then staged pickup
timeBlack=(0:0.002:20)';
frequencyReference=min(1,timeBlack/5);
voltageReference=min(1,timeBlack/8);
pBlack=zeros(size(timeBlack)); qBlack=zeros(size(timeBlack));
pBlack(timeBlack>=10)=3;
qBlack(timeBlack>=10)=1;
blackScenario=struct( ...
    'timeS',timeBlack, ...
    'pDemandMW',pBlack, ...
    'qDemandMvar',qBlack, ...
    'frequencyReferencePU',frequencyReference, ...
    'voltageReferencePU',voltageReference, ...
    'initialInternalVoltagePU',0, ...
    'initialVoltageIntegratorPU',0, ...
    'blackStart',true, ...
    'blackStartSOCMin',boundary.blackStartSOCMin, ...
    'baseDispatchMW',0, ...
    'reservedPowerMW',boundary.gfmReservePowerMW, ...
    'reservedEnergyMWh',boundary.gfmReserveEnergyMWh);
gfmBlack=v4_gfm_regfm_b1_dynamic_4_5(gfmParams,blackScenario);

%% Explicit overload rejection: bounded current is not full service
overloadScenario=struct( ...
    'timeS',timeDynamic, ...
    'pDemandMW',zeros(size(timeDynamic)), ...
    'qDemandMvar',40*ones(size(timeDynamic)));
gfmOverload=v4_gfm_regfm_b1_dynamic_4_5( ...
    gfmParams,overloadScenario);

%% Continuous 8760 h seasonal mechanism and current 72 t counterexample
timeYear=(0:8759)';
% Mean 56.77 MW produces 1000 kg/h at SEC=56.77 kWh/kg. The sinusoid is a
% mechanism-test assumption, not a 4.3 site resource series.
seasonalPowerMW=cfg.hydrogen.secKWhPerKg + ...
    (100-cfg.hydrogen.secKWhPerKg)*sin(2*pi*timeYear/8760);
seasonalDemandKg=1000*ones(size(timeYear));
cfgSeasonal=cfg;
cfgSeasonal.hydrogen.storageMaxKg=2.2e6; % [assumption, mechanism test only]
cfgSeasonal.hydrogen.storageInitialKg=0;
seasonalOptions=struct( ...
    'dispatchPolicy','must_take_available', ...
    'electrolyzerMode','modular', ...
    'electrolyzerModuleRatedMW',20, ...
    'electrolyzerModuleMinMW',4, ...
    'electrolyzerModuleCount',5, ...
    'h2TerminalRule','cyclic', ...
    'h2TerminalTarget',0, ...
    'tolerance',1e-3);
seasonal=v4_seasonal_hydrogen_storage_4_5( ...
    cfgSeasonal,timeYear,seasonalPowerMW,seasonalDemandKg,seasonalOptions);

cfg72t=cfgSeasonal;
cfg72t.hydrogen.storageMaxKg=72000;
smallTank=v4_seasonal_hydrogen_storage_4_5( ...
    cfg72t,timeYear,seasonalPowerMW,seasonalDemandKg,seasonalOptions);

%% Rolling-state inheritance equivalence (12 x 730 h, no state reset)
rollingInventory=zeros(8760,1);
rollingProduction=zeros(8760,1);
rollingState=struct( ...
    'bessEnergyMWh',cfgSeasonal.bess.socInitial*cfgSeasonal.bess.energyMWh, ...
    'h2InventoryKg',0);
rollingOptions=struct( ...
    'strictWithdrawal',false, ...
    'electrolyzerMode','modular', ...
    'electrolyzerModuleRatedMW',20, ...
    'electrolyzerModuleMinMW',4, ...
    'electrolyzerModuleCount',5, ...
    'bessTerminalRule','free', ...
    'h2TerminalRule','free');
for block=1:12
    idx=(block-1)*730+(1:730);
    localTime=(0:729)';
    localRequest=struct( ...
        'bessChargeMW',zeros(730,1), ...
        'bessDischargeMW',zeros(730,1), ...
        'electrolyzerMW',seasonalPowerMW(idx));
    local=v4_storage_hydrogen_core_4_5( ...
        cfgSeasonal,localTime,localRequest,rollingState, ...
        seasonalDemandKg(idx),rollingOptions);
    rollingInventory(idx)=local.h2InventoryKg;
    rollingProduction(idx)=local.h2ProductionKg;
    rollingState=local.finalState;
end
rollingDifferenceKg=max(abs(rollingInventory- ...
    seasonal.response.h2InventoryKg));
rollingProductionDifferenceKg=max(abs(rollingProduction- ...
    seasonal.response.h2ProductionKg));

%% Acceptance table
secExpected100MW=1000*100/cfg.hydrogen.secKWhPerKg;
checkName=[ ...
    "72 h electrolyzer produces nonzero hydrogen"; ...
    "100 MW fixed-SEC production identity"; ...
    "hourly hydrogen mass balance"; ...
    "hourly BESS energy balance"; ...
    "modular 3 MW off and 4 MW one-module on"; ...
    "cyclic BESS terminal state"; ...
    "infeasible cyclic terminal state is detected"; ...
    "terminal rule raises a hard error when enforced"; ...
    "4.5 BOUNDARY packet validates"; ...
    "REGFM_B1 step response remains finite and inside current limit"; ...
    "REGFM_B1 step response consumes physical BESS energy"; ...
    "two-minute continuous support remains inside the published reserve"; ...
    "black-start proxy energizes before staged load pickup"; ...
    "seconds-scale event is covered by the hourly GFM reserve"; ...
    "current-limited overload is rejected as infeasible"; ...
    "8760 h seasonal inventory has nonzero production"; ...
    "8760 h seasonal delivery and cyclic terminal constraints pass"; ...
    "seasonal release duration exceeds one week"; ...
    "seasonal working inventory exceeds the current 72 t tank"; ...
    "current 72 t tank fails the seasonal delivery case"; ...
    "12-block rolling state equals one-shot 8760 h state"];
passed=false(size(checkName));
evidence=strings(size(checkName));

passed(1)=sum(operational.h2ProductionKg)>0;
evidence(1)=sprintf('production %.3f kg',sum(operational.h2ProductionKg));
atRated=find(operational.pElectrolyzerMW>=100-1e-9,1,'first');
passed(2)=~isempty(atRated) && ...
    abs(operational.h2ProductionKg(atRated)-secExpected100MW)<=1e-8;
evidence(2)=sprintf('actual/expected %.6f / %.6f kg', ...
    operational.h2ProductionKg(atRated),secExpected100MW);
passed(3)=max(abs(operational.h2MassBalanceResidualKg))<=1e-9;
evidence(3)=sprintf('max residual %.3e kg', ...
    max(abs(operational.h2MassBalanceResidualKg)));
passed(4)=max(abs(operational.bessMassBalanceResidualMWh))<=1e-12;
evidence(4)=sprintf('max residual %.3e MWh', ...
    max(abs(operational.bessMassBalanceResidualMWh)));
passed(5)=moduleCheck.pElectrolyzerMW(1)==0 && ...
    abs(moduleCheck.pElectrolyzerMW(2)-4)<=1e-12 && ...
    moduleCheck.electrolyzerOnlineModules(2)==1;
evidence(5)=sprintf('actual [%.3f, %.3f] MW',moduleCheck.pElectrolyzerMW);
passed(6)=operational.terminal.bessOK;
evidence(6)=sprintf('terminal residual %.3e MWh', ...
    operational.terminal.bessResidualMWh);
passed(7)=~badTerminal.terminal.bessOK;
evidence(7)=sprintf('terminal residual %.3f MWh', ...
    badTerminal.terminal.bessResidualMWh);
passed(8)=terminalHardError;
evidence(8)=string(terminalHardError);
boundaryValidation=validate_module_packet_4_2( ...
    boundaryPacket,'4.5',cfg,false);
passed(9)=boundaryValidation.ok && boundary.blackStartAvailable;
evidence(9)=sprintf('charge/discharge initial max %.3f / %.3f MW', ...
    boundary.bessChargeMaxInitialMW,boundary.bessDischargeMaxInitialMW);
passed(10)=all(isfinite(gfmStep.frequencyHz)) && ...
    max(gfmStep.currentPU)<=gfmParams.currentMaxFPU+1e-9 && ...
    gfmStep.frequencyNadirHz>48 && gfmStep.feasible;
evidence(10)=sprintf('nadir %.4f Hz, max current %.4f pu', ...
    gfmStep.frequencyNadirHz,max(gfmStep.currentPU));
passed(11)=gfmStep.energyMWh(end)<gfmStep.energyMWh(1) && ...
    all(gfmStep.energyMWh>=gfmParams.energyMinMWh-1e-9);
evidence(11)=sprintf('energy change %.6f MWh', ...
    gfmStep.energyMWh(end)-gfmStep.energyMWh(1));
passed(12)=gfmMinute.feasible && gfmMinute.reservePowerAdequate && ...
    gfmMinute.reserveEnergyAdequate && ...
    gfmMinute.energyMWh(end)<gfmMinute.energyMWh(1);
evidence(12)=sprintf('required %.3f MW / %.6f MWh, nadir %.4f Hz', ...
    gfmMinute.requiredReservePowerMW, ...
    gfmMinute.requiredReserveEnergyMWh,gfmMinute.frequencyNadirHz);
passed(13)=gfmBlack.blackStart.socReady && ...
    gfmBlack.blackStart.energized && ...
    gfmBlack.blackStart.loadPickupAfterEnergization && ...
    ~any(gfmBlack.currentLimited) && gfmBlack.feasible;
evidence(13)=sprintf('energized at %.3f s, first load at 10 s', ...
    gfmBlack.blackStart.energizedTimeS);
passed(14)=gfmStep.reservePowerAdequate && ...
    gfmStep.reserveEnergyAdequate && ...
    gfmStep.requiredReservePowerMW<=boundary.gfmReservePowerMW+1e-9 && ...
    gfmStep.requiredReserveEnergyMWh<=boundary.gfmReserveEnergyMWh+1e-9;
evidence(14)=sprintf('required/published %.3f/%.3f MW, %.6f/%.6f MWh', ...
    gfmStep.requiredReservePowerMW,boundary.gfmReservePowerMW, ...
    gfmStep.requiredReserveEnergyMWh,boundary.gfmReserveEnergyMWh);
passed(15)=any(gfmOverload.currentLimited) && ~gfmOverload.feasible && ...
    max(gfmOverload.currentPU)<=gfmParams.currentMaxFPU+1e-9;
evidence(15)=sprintf('limited=%d, max current %.3f pu, feasible=%d', ...
    any(gfmOverload.currentLimited),max(gfmOverload.currentPU), ...
    gfmOverload.feasible);
passed(16)=sum(seasonal.response.h2ProductionKg)>0 && ...
    seasonal.maxInventoryKg>0;
evidence(16)=sprintf('production %.3f t, peak inventory %.3f t', ...
    sum(seasonal.response.h2ProductionKg)/1000, ...
    seasonal.maxInventoryKg/1000);
passed(17)=seasonal.feasible;
evidence(17)=sprintf('unserved %.3e kg, terminal residual %.3e kg', ...
    sum(seasonal.h2UnservedKg),seasonal.response.terminal.h2ResidualKg);
passed(18)=seasonal.longestContinuousReleaseH>=168;
evidence(18)=sprintf('continuous release %.1f h', ...
    seasonal.longestContinuousReleaseH);
passed(19)=seasonal.requiredWorkingInventoryKg>72000;
evidence(19)=sprintf('required working inventory %.3f t', ...
    seasonal.requiredWorkingInventoryKg/1000);
passed(20)=~smallTank.deliveryOK && sum(smallTank.h2UnservedKg)>0;
evidence(20)=sprintf('72 t unserved %.3f t', ...
    sum(smallTank.h2UnservedKg)/1000);
passed(21)=rollingDifferenceKg<=1e-6 && ...
    rollingProductionDifferenceKg<=1e-6;
evidence(21)=sprintf('inventory/production max diff %.3e / %.3e kg', ...
    rollingDifferenceKg,rollingProductionDifferenceKg);

report=table(checkName,passed,evidence);
writetable(report,fullfile(outputDir,'4_5_multiscale_test_report.csv'));

operationalTable=table(time72,operational.pChargeMW, ...
    operational.pDischargeMW,operational.pElectrolyzerMW, ...
    operational.bessSOC,operational.h2ProductionKg, ...
    operational.h2InventoryKg, ...
    'VariableNames',{'timeH','bessChargeMW','bessDischargeMW', ...
    'electrolyzerMW','bessSOC','h2ProductionKg','h2InventoryKg'});
writetable(operationalTable, ...
    fullfile(outputDir,'4_5_operational_72h.csv'));
gfmTable=table(gfmStep.timeS,gfmStep.frequencyHz, ...
    gfmStep.terminalVoltagePU,gfmStep.pActualMW,gfmStep.qActualMvar, ...
    gfmStep.currentPU,gfmStep.soc, ...
    'VariableNames',{'timeS','frequencyHz','voltagePU','pActualMW', ...
    'qActualMvar','currentPU','soc'});
writetable(gfmTable,fullfile(outputDir,'4_5_gfm_step_seconds.csv'));
blackTable=table(gfmBlack.timeS,gfmBlack.frequencyHz, ...
    gfmBlack.terminalVoltagePU,gfmBlack.pActualMW, ...
    gfmBlack.currentPU,gfmBlack.soc, ...
    'VariableNames',{'timeS','frequencyHz','voltagePU','pActualMW', ...
    'currentPU','soc'});
writetable(blackTable,fullfile(outputDir,'4_5_black_start_proxy.csv'));
seasonalTable=table(timeYear,seasonalPowerMW, ...
    seasonal.response.pElectrolyzerMW,seasonal.response.h2ProductionKg, ...
    seasonal.h2DeliveredKg,seasonal.h2UnservedKg, ...
    seasonal.response.h2InventoryKg, ...
    'VariableNames',{'timeH','availableElectrolyzerMW', ...
    'actualElectrolyzerMW','h2ProductionKg','h2DeliveredKg', ...
    'h2UnservedKg','h2InventoryKg'});
writetable(seasonalTable,fullfile(outputDir,'4_5_seasonal_8760h.csv'));

summary=table( ...
    sum(operational.h2ProductionKg), ...
    gfmStep.frequencyNadirHz, ...
    gfmBlack.blackStart.energizedTimeS, ...
    seasonal.maxInventoryKg, ...
    seasonal.longestContinuousReleaseH, ...
    sum(smallTank.h2UnservedKg), ...
    rollingDifferenceKg, ...
    'VariableNames',{'OperationalH2ProductionKg','GFMFrequencyNadirHz', ...
    'BlackStartEnergizedTimeS','SeasonalPeakInventoryKg', ...
    'SeasonalContinuousReleaseH','SmallTankUnservedKg', ...
    'RollingStateMaxDifferenceKg'});
writetable(summary,fullfile(outputDir,'4_5_multiscale_summary.csv'));

figurePath=fullfile(outputDir,'4_5_multiscale_validation.png');
make_validation_figure(operational,gfmStep,seasonal,figurePath);
operationalFigurePath=fullfile(outputDir,'4_5_operational_72h.png');
gfmFigurePath=fullfile(outputDir,'4_5_gfm_step_seconds.png');
blackStartFigurePath=fullfile(outputDir,'4_5_black_start_seconds.png');
seasonalFigurePath=fullfile(outputDir,'4_5_seasonal_8760h.png');
make_operational_figure(operational,operationalFigurePath);
make_gfm_figure(gfmStep,gfmFigurePath);
make_black_start_figure(gfmBlack,blackStartFigurePath);
make_seasonal_figure(seasonal,seasonalFigurePath);
docAssetDir=fullfile(here,'docs','assets');
if ~isfolder(docAssetDir), mkdir(docAssetDir); end
copyfile(figurePath,fullfile(docAssetDir,'fig07_multiscale_validation.png'));
copyfile(operationalFigurePath,fullfile(docAssetDir,'fig08_operational_72h.png'));
copyfile(gfmFigurePath,fullfile(docAssetDir,'fig09_gfm_step_seconds.png'));
copyfile(blackStartFigurePath,fullfile(docAssetDir,'fig10_black_start_seconds.png'));
copyfile(seasonalFigurePath,fullfile(docAssetDir,'fig11_seasonal_8760h.png'));

out=struct( ...
    'cfg',cfg, ...
    'operational72h',operational, ...
    'moduleMinimumCheck',moduleCheck, ...
    'badTerminalCase',badTerminal, ...
    'boundaryPacket',boundaryPacket, ...
    'boundary',boundary, ...
    'gfmStep',gfmStep, ...
    'gfmMinuteSupport',gfmMinute, ...
    'gfmBlackStart',gfmBlack, ...
    'gfmOverload',gfmOverload, ...
    'seasonal8760h',seasonal, ...
    'smallTank8760h',smallTank, ...
    'rollingStateMaxDifferenceKg',rollingDifferenceKg, ...
    'report',report, ...
    'outputDir',outputDir, ...
    'assumptionNotice','[assumption values, pending enterprise/vendor calibration]');
save(fullfile(outputDir,'4_5_multiscale_result.mat'),'out');

disp(report);
assert(all(passed),'4.5 standalone multiscale validation failed.');
fprintf('BLUE HUB 4.5 STANDALONE MULTISCALE: ALL TESTS PASSED\n');
end

function make_validation_figure(operational,gfm,seasonal,figurePath)
f=figure('Visible','off','Color','white','Position',[100 100 1200 900]);
tiledlayout(f,3,1,'TileSpacing','compact','Padding','compact');
nexttile;
yyaxis left
stairs(operational.timeH,operational.pElectrolyzerMW, ...
    'LineWidth',1.5,'Color',[0.85 0.33 0.10]);
ylabel('Electrolyzer (MW)');
yyaxis right
plot(operational.timeH,operational.h2InventoryKg/1000, ...
    'LineWidth',1.5,'Color',[0.00 0.45 0.74]);
ylabel('H_2 inventory (t)');
xlabel('Operational horizon (h)');
title('72 h nonzero hydrogen production');
grid on;

nexttile;
yyaxis left
plot(gfm.timeS,gfm.frequencyHz,'LineWidth',1.4);
ylabel('Frequency (Hz)');
yyaxis right
    plot(gfm.timeS,gfm.terminalVoltagePU,'LineWidth',1.4);
ylabel('Voltage (pu)');
xlabel('Dynamic time (s)');
title('WECC REGFM\_B1 reduced-order load-step proxy');
grid on;

nexttile;
yyaxis left
plot(seasonal.response.timeH/24, ...
    seasonal.response.h2InventoryKg/1000,'LineWidth',1.5);
ylabel('H_2 inventory (t)');
yyaxis right
plot(seasonal.response.timeH/24, ...
    seasonal.response.pElectrolyzerMW,'LineWidth',1.0);
ylabel('Electrolyzer (MW)');
xlabel('Continuous horizon (day)');
title('8760 h seasonal inventory mechanism');
grid on;

ax=findall(f,'Type','axes');
for k=1:numel(ax)
    ax(k).Color='white';
    ax(k).XColor=[0.15 0.15 0.15];
    ax(k).GridColor=[0.70 0.70 0.70];
    ax(k).Title.Color=[0.10 0.10 0.10];
    ax(k).XLabel.Color=[0.10 0.10 0.10];
end
exportgraphics(f,figurePath,'Resolution',220,'BackgroundColor','white');
close(f);
end

function make_operational_figure(operational,figurePath)
f=figure('Visible','off','Color','white','Position',[100 100 1200 680]);
tiledlayout(f,2,1,'TileSpacing','compact','Padding','compact');
nexttile;
stairs(operational.timeH,operational.pElectrolyzerMW, ...
    'LineWidth',1.6,'DisplayName','Electrolyzer');
hold on;
stairs(operational.timeH,operational.pChargeMW, ...
    'LineWidth',1.3,'DisplayName','BESS charge');
stairs(operational.timeH,-operational.pDischargeMW, ...
    'LineWidth',1.3,'DisplayName','BESS discharge (-)');
ylabel('Power (MW)');
title('72 h operational power');
legend('Location','best','Box','off');
grid on;
nexttile;
yyaxis left
plot(operational.timeH,100*operational.bessSOC,'LineWidth',1.6);
ylabel('BESS SOC (%)');
yyaxis right
plot(operational.timeH,operational.h2InventoryKg/1000,'LineWidth',1.6);
ylabel('H_2 inventory (t)');
xlabel('Operational horizon (h)');
title('72 h storage states');
grid on;
format_figure(f);
exportgraphics(f,figurePath,'Resolution',220,'BackgroundColor','white');
close(f);
end

function make_gfm_figure(gfm,figurePath)
f=figure('Visible','off','Color','white','Position',[100 100 1200 760]);
tiledlayout(f,3,1,'TileSpacing','compact','Padding','compact');
nexttile;
plot(gfm.timeS,gfm.frequencyHz,'LineWidth',1.6);
ylabel('Frequency (Hz)');
title('REGFM\_B1 load-step frequency');
grid on;
nexttile;
plot(gfm.timeS,gfm.terminalVoltagePU,'LineWidth',1.6);
ylabel('Voltage (pu)');
title('Terminal voltage');
grid on;
nexttile;
yyaxis left
plot(gfm.timeS,gfm.pActualMW,'LineWidth',1.5);
ylabel('P (MW)');
yyaxis right
plot(gfm.timeS,gfm.currentPU,'LineWidth',1.5);
ylabel('Current (pu)');
xlabel('Dynamic time (s)');
title('Active power and positive-sequence current');
grid on;
format_figure(f);
exportgraphics(f,figurePath,'Resolution',220,'BackgroundColor','white');
close(f);
end

function make_black_start_figure(gfm,figurePath)
f=figure('Visible','off','Color','white','Position',[100 100 1200 700]);
tiledlayout(f,2,1,'TileSpacing','compact','Padding','compact');
nexttile;
yyaxis left
plot(gfm.timeS,gfm.frequencyHz,'LineWidth',1.5);
ylabel('Frequency (Hz)');
yyaxis right
plot(gfm.timeS,gfm.terminalVoltagePU,'LineWidth',1.5);
ylabel('Voltage (pu)');
xline(gfm.blackStart.energizedTimeS,'--','Energized');
xline(gfm.blackStart.firstLoadPickupTimeS,'--','First load');
title('Black-start energization sequence');
grid on;
nexttile;
yyaxis left
plot(gfm.timeS,gfm.pActualMW,'LineWidth',1.5);
ylabel('P (MW)');
yyaxis right
plot(gfm.timeS,gfm.currentPU,'LineWidth',1.5);
ylabel('Current (pu)');
xlabel('Dynamic time (s)');
title('Staged load pickup');
grid on;
format_figure(f);
exportgraphics(f,figurePath,'Resolution',220,'BackgroundColor','white');
close(f);
end

function make_seasonal_figure(seasonal,figurePath)
f=figure('Visible','off','Color','white','Position',[100 100 1200 680]);
tiledlayout(f,2,1,'TileSpacing','compact','Padding','compact');
nexttile;
plot(seasonal.response.timeH/24, ...
    seasonal.response.pElectrolyzerMW,'LineWidth',1.2);
hold on;
plot(seasonal.response.timeH/24, ...
    seasonal.h2DeliveredKg*24/1000,'LineWidth',1.2);
ylabel('Power (MW) / delivery (t d^{-1})');
title('8760 h production and delivery mechanism');
legend({'Electrolyzer','H_2 delivery'},'Location','best','Box','off');
grid on;
nexttile;
plot(seasonal.response.timeH/24, ...
    seasonal.response.h2InventoryKg/1000,'LineWidth',1.7);
ylabel('H_2 inventory (t)');
xlabel('Continuous horizon (day)');
title('8760 h seasonal inventory');
grid on;
format_figure(f);
exportgraphics(f,figurePath,'Resolution',220,'BackgroundColor','white');
close(f);
end

function format_figure(f)
ax=findall(f,'Type','axes');
for k=1:numel(ax)
    ax(k).Color='white';
    ax(k).XColor=[0.15 0.15 0.15];
    ax(k).YColor=[0.15 0.15 0.15];
    ax(k).GridColor=[0.70 0.70 0.70];
    ax(k).Title.Color=[0.10 0.10 0.10];
    ax(k).XLabel.Color=[0.10 0.10 0.10];
    ax(k).YLabel.Color=[0.10 0.10 0.10];
end
end
