import sys, os  
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))  
from model import *  
SEP = chr(124)  
def T(a,b,c): return f'{SEP} {a} {SEP} {b} {SEP} {c} {SEP}'  
  
def gen_full_report():  
    params = CommonCaseV1()  
    cb, _ = create_common_case(params)  
    r_base = run_balance(cb, params, 'base')  
    cb2, _ = create_common_case(params)  
    r_peak = run_balance(cb2, params, 'peak') 
    L = []  
    def A(s): L.append(s)  
    A('# 4.4 Energy Island Power Balance Model Report')  
    A('')  
    A('## 1. Measurement Points (MP)')  
    A('')  
    A(T('ID', 'Description', 'Module'))  
    A(T('---', '---', '---'))  
    A(T('MP-DEVICE', 'Device gross power', 'Single source'))  
    A(T('MP-03-SOURCE-POI', 'Source after collection loss', '4.3'))  
    A(T('MP-04-COMMON-BUS', 'Common balance point', '4.4'))  
    A(T('MP-CABLE-SEND/RECV', 'Cable send/receive', '4.7'))  
    A(T('MP-DC-FACILITY', 'Data center power', '4.6'))  
    A(T('MP-ELECTROLYZER', 'Electrolyzer power', '4.5'))  
    A(T('MP-H2-DELIVERY', 'Hydrogen delivery', '4.7')) 
    A('')  
    A('## 2. Core Power Conservation Equation')  
    A('')  
    A('At MP-04-COMMON-BUS:')  
    A('')  
    A('pSource_net + pGridImport + pBessDischarge =')  
    A('pBessCharge + pElectrolyzer + pDCFacility + pExportSend')  
    A('+ pMarine + pSpill + pPostPOILoss + pCommonAux')  
    A('')  
    A('## 3. Simulation Results')  
    A('')  
    A(f'### 3.1 Common Case V1 Parameters')  
    A(f'- Wind: {params.s.wind_mw} MW, PV: {params.s.pv_mw} MW, Tidal: {params.s.tidal_mw} MW')  
    A(f'- BESS: {params.bess.power_mw} MW / {params.bess.energy_mwh} MWh')  
    A(f'- Electrolyzer: {params.h2.elec_mw} MW, SEC: {params.h2.sec_kwh_kg} kWh/kg')  
    A(f'- DC Facility: {params.comp.dc_facility_mw} MW, PUE: {params.comp.pue}')  
    A(f'- Export Cable: {params.exp.cable_mw} MW, {params.exp.cable_km} km')  
    A(f'- Marine Load: {params.marine.load_mw} MW') 
    A('')  
    A('### 3.2 Base Scenario Results')  
    A(f'- Source gross: {params.s.total_mw():.1f} MW at CF 0.7')  
    A(f'- Source actual at POI: {r_base.p_source_actual:.2f} MW')  
    A(f'- Source aux: {r_base.p_source_aux:.2f} MW')  
    A(f'- Electrolyzer: {r_base.p_electrolyzer:.2f} MW')  
    A(f'- DC Facility: {r_base.p_dc_facility:.2f} MW')  
    A(f'- Export send: {r_base.p_export_send:.2f} MW')  
    A(f'- Residual: {r_base.p_residual:.4f} MW')  
    A('')  
    A('### 3.3 Peak Scenario Results')  
    A(f'- Source gross: {params.s.total_mw():.1f} MW at CF 0.3/0.2/0.4')  
    A(f'- Source actual at POI: {r_peak.p_source_actual:.2f} MW')  
    A(f'- Source aux: {r_peak.p_source_aux:.2f} MW')  
    A(f'- Electrolyzer: {r_peak.p_electrolyzer:.2f} MW')  
    A(f'- DC Facility: {r_peak.p_dc_facility:.2f} MW')  
    A(f'- Export send: {r_peak.p_export_send:.2f} MW')  
    A(f'- Residual: {r_peak.p_residual:.4f} MW (deficit)') 
    A('')  
    A('---')  
    sline = f'*Case: common_case_v1 {chr(124)} Generated: 2026-07-20*'  
    A(sline)  
    A('*Model: Energy Island Power Balance, Section 4.4*')  
    rp = os.path.join(OUT_DIR, 'balance_report.md')  
    with open(rp, 'w', encoding='utf-8') as f:  
        f.write('\n'.join(L))  
    print(f'Report saved: {rp}')  
  
if __name__ == '__main__':  
    gen_full_report() 
