function strategies=c5_four_strategy_specs()
%C5_FOUR_STRATEGY_SPECS Three asset baselines and one causal strategy.
%
% This is the only C5 comparison set. No fixed annual or hourly E/H/C
% proportion grid is retained. Numerical controller settings are
% [假设值，待企业调研校准].

strategies={ ...
    struct('id','baseline_E_asset_only', ...
        'strategyClass','ASSET_BASELINE_ELECTRICITY_ONLY', ...
        'productMixEnabled',false, ...
        'electricityEnabled',true, ...
        'hydrogenEnabled',false, ...
        'computeEnabled',false, ...
        'eventReserveRule',false, ...
        'forecastMode','CURRENT_OBSERVATION', ...
        'maxENSMWh',0), ...
    struct('id','baseline_H_asset_only', ...
        'strategyClass','ASSET_BASELINE_HYDROGEN_ONLY', ...
        'productMixEnabled',false, ...
        'electricityEnabled',false, ...
        'hydrogenEnabled',true, ...
        'computeEnabled',false, ...
        'eventReserveRule',false, ...
        'forecastMode','CURRENT_OBSERVATION', ...
        'maxENSMWh',0), ...
    struct('id','baseline_C_asset_only', ...
        'strategyClass','ASSET_BASELINE_COMPUTE_ONLY', ...
        'productMixEnabled',false, ...
        'electricityEnabled',false, ...
        'hydrogenEnabled',false, ...
        'computeEnabled',true, ...
        'eventReserveRule',false, ...
        'forecastMode','CURRENT_OBSERVATION', ...
        'maxENSMWh',0), ...
    struct('id','model_online_prior_posterior_event_aware', ...
        'strategyClass','MODEL_CAUSAL_ONLINE_PRIOR_POSTERIOR', ...
        'productMixEnabled',false, ...
        'electricityEnabled',true, ...
        'hydrogenEnabled',true, ...
        'computeEnabled',true, ...
        'eventReserveRule',true, ...
        'robustEventReserveRule',true, ...
        'maxENSMWh',0, ...
        'allowReliabilityRelaxation',true, ...
        'strictReliabilityMaxTimeS',0.5, ...
        'forecastMode','KALMAN_PRIOR_POSTERIOR', ...
        'plannedShareTolerance',0.15, ...
        'planMaxTimeS',10, ...
        'kalmanDynamicCIWeight',0.65, ...
        'kalmanProcessNoiseFraction',0.20, ...
        'kalmanMeasurementNoiseFraction',0.10, ...
        'kalmanNormalQuantile',0.50, ...
        'kalmanWarningQuantile',0.10, ...
        'kalmanPassageQuantile',0.05, ...
        'kalmanRecoveryQuantile',0.20, ...
        'planShareFilterAlpha',0.35, ...
        'planShareMaxDeltaPerHour',0.10, ...
        'planShareDeadband',0.02, ...
        'recoveryShareFilterAlpha',0.20, ...
        'recoveryShareMaxDeltaPerHour',0.05, ...
        'normalBessReserveTargetSOC',0.50, ...
        'warningBessReserveTargetSOC',0.80, ...
        'recoveryBessReserveTargetSOC',0.60, ...
        'normalLowReserveOptionalLimitFactor',0, ...
        'recoveryOptionalLimitFactor',0.25)};
end
