% Chapter 4.3 standalone demo: wind + floating PV + tidal aggregation.
% Every numerical value is [ASSUMPTION - CALIBRATE WITH OEM/PROJECT DATA].
% This demo intentionally contains no storage, load allocation or bus balance.
clear; clc; rng(43);

thisDir=fileparts(mfilename('fullpath'));
addpath(thisDir);

dt=300;
t=(0:dt:24*3600)';
h=t/3600;
N=numel(t);
capacity=[85 10 5]*1e6;
sourceType={'wind','pv','tidal'};

% Synthetic resource-to-power signals for interface testing only.
wind=max(0,min(1,0.55+0.22*sin(2*pi*h/17)+0.05*randn(N,1)))*capacity(1);
pv=max(0,sin(pi*mod(h-6,24)/12))*capacity(2);
tidal=abs(sin(2*pi*h/12.42)).^3*capacity(3);
pGross=[wind,pv,tidal];

K=10;
commonError=0.02*randn(N,K);
sourceCell=cell(1,3);
for j=1:3
    gross=pGross(:,j);
    collectionLoss=0.01*gross;
    available=max(0,gross-collectionLoss);
    requested=1.03*available;       % Deliberately infeasible EMS request.
    accepted=available;             % Device clips request to availability.
    actual=0.995*accepted;          % Synthetic tracking difference.
    actualCollectionLoss=(actual/(1-0.01))*0.01;
    qCapability=sqrt(max(0,(1.05*capacity(j)).^2-actual.^2));
    scenario=max(0,available.*(1+commonError+0.03*randn(N,K)));

    sourceCell{j}=struct( ...
        'time',t, ...
        'sourceId',sprintf('S%d',j), ...
        'sourceType',sourceType{j}, ...
        'meterPoint','source_collection_bus', ...
        'pAvailableGross',gross, ...
        'pAvailableAtPOI',available, ...
        'pRequested',requested, ...
        'pAccepted',accepted, ...
        'pActualAtPOI',actual, ...
        'pAuxLoad',0.003*capacity(j)*ones(N,1), ...
        'pCollectionLoss',collectionLoss, ...
        'pActualCollectionLoss',actualCollectionLoss, ...
        'pForecastAvailable',0.99*available, ...
        'qMinAtPOI',-qCapability, ...
        'qMaxAtPOI',qCapability, ...
        'qualityFlag',true(N,1), ...
        'operatingState',repmat("normal",N,1), ...
        'constraintCode',repmat("resource",N,1), ...
        'scenarioAvailable',scenario);
end
sources=[sourceCell{:}];

cfg=struct( ...
    'scenarioProbability',ones(1,K)/K, ...
    'parameterSetId','DEMO_ASSUMPTION_4_3_V3', ...
    'units','P=W; Q=var; time=s');

out=source_aggregation_4_3_v3(sources,cfg);
out.metrics=source_complementarity_metrics_v3( ...
    out.time,out.perSource.actual,out.perSource.qualityFlag, ...
    capacity,[dt 3600 6*3600],0.2);

% Contract and conservation checks for Chapter 4.3.
assert(max(abs(out.aggregate.actual-sum(out.perSource.actual,2)))<1e-6);
assert(max(abs(out.aggregate.available-sum(out.perSource.available,2)))<1e-6);
assert(all(out.perSource.accepted<=out.perSource.available+1e-6,'all'));
assert(all(out.perSource.actual<=out.perSource.available+1e-6,'all'));
assert(max(abs(out.perSource.available- ...
    max(0,out.perSource.availableGross-out.perSource.collectionLoss)),[],'all')<1e-6);
assert(abs(sum(out.scenario.probability)-1)<1e-12);
assert(isequal(out.meta.meterPoint,"source_collection_bus"));
assert(~isfield(out,'ports') && ~isfield(out,'balance'), ...
    'Chapter 4.3 output must not contain bus-balance or load-port decisions.');

fprintf('Chapter 4.3 standalone aggregation demo completed.\n');
fprintf('Numerical assumptions require OEM/project calibration.\n');
