function [packet,boundary]=v4_storage_hydrogen_boundary_4_5(cfg,timeH,state0,options)
%V4_STORAGE_HYDROGEN_BOUNDARY_4_5 Publish 4.5 state and feasible limits.
%
% The boundary exposes initial committed state plus physical limits. 4.9
% remains the only owner of cross-module allocation decisions.

if nargin<4 || isempty(options), options=struct; end
cfg=v4_apply_4_5_parameter_overlay(cfg);
timeH=double(timeH(:)); N=numel(timeH); dt=cfg.time.dispatchStepH;
if nargin<3 || isempty(state0)
    state0=struct( ...
        'bessEnergyMWh',cfg.bess.socInitial*cfg.bess.energyMWh, ...
        'h2InventoryKg',cfg.hydrogen.storageInitialKg, ...
        'electrolyzerOn',false, ...
        'electrolyzerPowerMW',0, ...
        'electrolyzerFLEH',0);
end
assert(isfield(state0,'bessEnergyMWh') && isfield(state0,'h2InventoryKg'));
state0=fill_state(state0,'electrolyzerOn',false);
state0=fill_state(state0,'electrolyzerPowerMW',0);
state0=fill_state(state0,'electrolyzerFLEH',0);
e0=double(state0.bessEnergyMWh); h0=double(state0.h2InventoryKg);
reservePower=option_value(options,'gfmReservePowerMW', ...
    cfg.bess.gfmReservePowerMW);
reserveEnergy=option_value(options,'gfmReserveEnergyMWh', ...
    cfg.bess.gfmReserveEnergyMWh);
blackStartSOCMin=option_value(options,'blackStartSOCMin', ...
    cfg.bess.blackStartSOCMin);

eMin=cfg.bess.socMin*cfg.bess.energyMWh+reserveEnergy;
eMax=cfg.bess.socMax*cfg.bess.energyMWh;
assert(e0>=eMin-1e-9 && e0<=eMax+1e-9, ...
    '4.5 initial BESS energy cannot support the configured reserve boundary.');
assert(h0>=-1e-9 && h0<=cfg.hydrogen.storageMaxKg+1e-9);
chargeMax=min(cfg.bess.chargeMaxMW, ...
    max(0,eMax-e0)/(cfg.bess.etaCharge*dt));
dischargeMax=min(max(0,cfg.bess.dischargeMaxMW-reservePower), ...
    max(0,e0-eMin)*cfg.bess.etaDischarge/dt);
tankLimitedElectrolyzerMax=min(cfg.hydrogen.electrolyzerRatedMW, ...
    max(0,cfg.hydrogen.storageMaxKg-h0)* ...
    cfg.hydrogen.secKWhPerKg/(1000*dt));
blackStartAvailable=e0/cfg.bess.energyMWh>=blackStartSOCMin && ...
    reservePower>0 && reserveEnergy>0;

packet=common_packet_4_2('4.5',timeH,cfg,'BOUNDARY');
packet.ports.bessCharge=v4_fill_port(timeH,cfg.meter.commonBus, ...
    0,0,0,0,chargeMax,"4.5_INITIAL_STATE_LIMIT","AVAILABLE");
packet.ports.bessDischarge=v4_fill_port(timeH,cfg.meter.commonBus, ...
    0,0,0,0,dischargeMax,"4.5_INITIAL_STATE_AND_GFM_RESERVE","AVAILABLE");
packet.ports.electrolyzer=v4_fill_port(timeH,cfg.meter.electrolyzer, ...
    0,0,0,0,tankLimitedElectrolyzerMax, ...
    "4.5_INITIAL_TANK_LIMIT","AVAILABLE");
packet.state.bessSOC=repmat(e0/cfg.bess.energyMWh,N,1);
packet.state.bessEnergyMWh=repmat(e0,N,1);
packet.state.h2InventoryKg=repmat(h0,N,1);
packet.state.electrolyzerOn=repmat(logical(state0.electrolyzerOn),N,1);
packet.state.electrolyzerPowerMW= ...
    repmat(double(state0.electrolyzerPowerMW),N,1);
packet.state.electrolyzerFLEH= ...
    repmat(double(state0.electrolyzerFLEH),N,1);
packet.state.gfmReservePowerMW=repmat(reservePower,N,1);
packet.state.gfmReserveEnergyMWh=repmat(reserveEnergy,N,1);
packet.state.blackStartAvailable=repmat(blackStartAvailable,N,1);
packet.product.h2ProductionKg=zeros(N,1);
packet.product.h2AvailableForDeliveryKg=repmat(h0,N,1);
packet.service.electrolyzerRatedMW= ...
    repmat(cfg.hydrogen.electrolyzerRatedMW,N,1);
packet.service.electrolyzerAggregateMinimumMW= ...
    repmat(cfg.hydrogen.electrolyzerMinMW,N,1);
packet.service.electrolyzerModuleCount= ...
    repmat(cfg.hydrogen.electrolyzerModuleCount,N,1);
packet.service.electrolyzerModuleRatedMW= ...
    repmat(cfg.hydrogen.electrolyzerModuleRatedMW,N,1);
packet.service.electrolyzerModuleMinimumMW= ...
    repmat(cfg.hydrogen.electrolyzerModuleMinMW,N,1);
packet.service.electrolyzerIndependentCommitment= ...
    repmat(logical(cfg.hydrogen.moduleIndependentCommitment),N,1);
packet.service.bessStandingLossFractionPerH= ...
    repmat(cfg.bess.standingLossFractionPerH,N,1);
packet.service.bessTerminalRule= ...
    repmat(string(cfg.bess.terminalRule),N,1);
packet.service.bessTerminalTargetMWh= ...
    repmat(terminal_target(cfg.bess.terminalRule,e0, ...
    cfg.bess.terminalTargetSOC*cfg.bess.energyMWh),N,1);
packet.service.h2TerminalRule= ...
    repmat(string(cfg.hydrogen.terminalRule),N,1);
packet.service.h2TerminalTargetKg= ...
    repmat(terminal_target(cfg.hydrogen.terminalRule,h0, ...
    cfg.hydrogen.terminalTargetKg),N,1);
packet.quality.dataSourceType="CONFIG_PLUS_COMMITTED_STATE";
packet.quality.calibrationVersion="UNCALIBRATED";
packet.audit.boundaryOwner='4.5';
packet.audit.stateInheritance='EXPLICIT_STATE0_NO_IMPLICIT_RESET';
packet.audit.bessTerminalRule=cfg.bess.terminalRule;
packet.audit.h2TerminalRule=cfg.hydrogen.terminalRule;
packet.audit.gfmReserveStatus= ...
    '[assumption value, pending PCS vendor calibration]';
packet.audit.blackStartStatus= ...
    'REDUCED_ORDER_PROXY_ONLY; EMT/HIL/PROTECTION VALIDATION REQUIRED';
validate_module_packet_4_2(packet,'4.5',cfg,true);

boundary=struct( ...
    'state0',state0, ...
    'bessChargeMaxInitialMW',chargeMax, ...
    'bessDischargeMaxInitialMW',dischargeMax, ...
    'electrolyzerMaxInitialMW',tankLimitedElectrolyzerMax, ...
    'gfmReservePowerMW',reservePower, ...
    'gfmReserveEnergyMWh',reserveEnergy, ...
    'blackStartSOCMin',blackStartSOCMin, ...
    'blackStartAvailable',blackStartAvailable, ...
    'bessTerminalRule',cfg.bess.terminalRule, ...
    'bessTerminalTargetMWh',packet.service.bessTerminalTargetMWh(1), ...
    'bessStandingLossFractionPerH',cfg.bess.standingLossFractionPerH, ...
    'h2TerminalRule',cfg.hydrogen.terminalRule, ...
    'h2TerminalTargetKg',packet.service.h2TerminalTargetKg(1), ...
    'electrolyzerModuleCount',cfg.hydrogen.electrolyzerModuleCount, ...
    'electrolyzerModuleRatedMW',cfg.hydrogen.electrolyzerModuleRatedMW, ...
    'electrolyzerModuleMinimumMW',cfg.hydrogen.electrolyzerModuleMinMW, ...
    'electrolyzerIndependentCommitment', ...
    cfg.hydrogen.moduleIndependentCommitment);
end

function value=option_value(s,name,defaultValue)
if isfield(s,name), value=s.(name); else, value=defaultValue; end
end

function s=fill_state(s,name,value)
if ~isfield(s,name) || isempty(s.(name)), s.(name)=value; end
end

function target=terminal_target(rule,initialValue,configuredTarget)
if strcmpi(rule,'cyclic'), target=initialValue;
else, target=configuredTarget;
end
end
