function designTable = c5_product_mix_specs()
%C5_PRODUCT_MIX_SPECS Chapter-5 horizon-energy allocation strategies.
%
% E/H/C are target shares of actually dispatched common-bus input energy:
%
%   E = cable sending energy (MWh)
%   H = electrolyzer input energy (MWh)
%   C = flexible-compute input energy (MWh)
%
% The legacy 22 share cases are not nameplate-capacity shares, delivered-
% product shares, equal-CAPEX shares or investment decisions. Firm/base
% compute remains a common critical load outside their optional-product
% denominator.
%
% Four additional Chapter-5 asset strategies provide true power-only,
% hydrogen-only, compute-only and mixed-output operating comparisons.
% Those four cases remove common base compute, switch product assets on or
% off explicitly, and use a 120 MW full-flexible compute task pool where
% compute is installed. Capacities and the unlimited flexible-task pool are
% [假设值，待企业调研校准]. They compare operating value only, not equal
% CAPEX or lifecycle investment return.

rows={ ...
    "mix_E100","Power only",1.00,0.00,0.00; ...
    "mix_H100","Hydrogen only",0.00,1.00,0.00; ...
    "mix_C100","Compute only",0.00,0.00,1.00; ...
    "mix_E80_H20","Power + hydrogen, power-led",0.80,0.20,0.00; ...
    "mix_E60_H40","Power + hydrogen",0.60,0.40,0.00; ...
    "mix_E40_H60","Power + hydrogen, H2-led",0.40,0.60,0.00; ...
    "mix_E20_H80","Power + hydrogen, high-H2",0.20,0.80,0.00; ...
    "mix_E80_C20","Power + compute, power-led",0.80,0.00,0.20; ...
    "mix_E60_C40","Power + compute, moderate compute",0.60,0.00,0.40; ...
    "mix_E40_C60","Power + compute, compute-led",0.40,0.00,0.60; ...
    "mix_E20_C80","Power + compute, high-compute",0.20,0.00,0.80; ...
    "mix_H80_C20","Hydrogen + compute, H2-led",0.00,0.80,0.20; ...
    "mix_H60_C40","Hydrogen + compute, moderate compute",0.00,0.60,0.40; ...
    "mix_H40_C60","Hydrogen + compute, compute-led",0.00,0.40,0.60; ...
    "mix_H20_C80","Hydrogen + compute, high-compute",0.00,0.20,0.80; ...
    "mix_E60_H20_C20","Triplex power-biased",0.60,0.20,0.20; ...
    "mix_E50_H30_C20","Triplex power-led",0.50,0.30,0.20; ...
    "mix_E40_H30_C30","Triplex balanced",0.40,0.30,0.30; ...
    "mix_E30_H30_C40","Triplex compute-led",0.30,0.30,0.40; ...
    "mix_E20_H40_C40","Triplex H2/compute-led",0.20,0.40,0.40; ...
    "mix_E20_H60_C20","Triplex H2-biased",0.20,0.60,0.20; ...
    "mix_E20_H20_C60","Triplex high-compute",0.20,0.20,0.60};

scenarioId=string(rows(:,1));
scenarioLabel=string(rows(:,2));
targetElectricityInputShare=cell2mat(rows(:,3));
targetHydrogenInputShare=cell2mat(rows(:,4));
targetComputeInputShare=cell2mat(rows(:,5));
shareSum=targetElectricityInputShare+targetHydrogenInputShare+ ...
    targetComputeInputShare;
assert(all(abs(shareSum-1)<=1e-12), ...
    'Product-input energy shares must sum to one.');

allocationBoundary=repmat( ...
    "OPTIONAL_INPUT_ENERGY_OVER_FULL_HORIZON; BASE_COMPUTE_EXCLUDED", ...
    numel(scenarioId),1);
capacityRule=repmat( ...
    "COMMON_V5_PHYSICAL_CAPACITY; STRATEGY_CHANGES_DISPATCH_ONLY", ...
    numel(scenarioId),1);
parameterStatus=repmat( ...
    "[假设值，待企业调研校准]",numel(scenarioId),1);

designTable=table(scenarioId,scenarioLabel, ...
    targetElectricityInputShare,targetHydrogenInputShare, ...
    targetComputeInputShare,allocationBoundary,capacityRule, ...
    parameterStatus);

n=height(designTable);
designTable.strategyClass=repmat("DISPATCH_SHARE_POLICY",n,1);
designTable.productMixEnabled=true(n,1);
designTable.assetElectricityEnabled=true(n,1);
designTable.assetHydrogenEnabled=true(n,1);
designTable.assetComputeEnabled=true(n,1);
designTable.computeScenarioMode=repmat("SUPPLIED_ANNUAL_TASK",n,1);
designTable.computeFacilityCapacityMW=nan(n,1);
designTable.computeModuleCount=nan(n,1);
designTable.comparisonGroup=repmat("LEGACY_22_OPERATION_SHARE",n,1);

assetScenarioId=[ ...
    "baseline_E_asset_only"; ...
    "baseline_H_asset_only"; ...
    "baseline_C_asset_only"; ...
    "compare_EHC_mixed_optimized"];
assetScenarioLabel=[ ...
    "Asset baseline: power only"; ...
    "Asset baseline: hydrogen only"; ...
    "Asset baseline: compute only"; ...
    "Asset comparison: E/H/C optimized"];
assetTarget=[ ...
    1,0,0; ...
    0,1,0; ...
    0,0,1; ...
    NaN,NaN,NaN];
assetAllocationBoundary=repmat( ...
    "ASSET_LEVEL_OUTPUT_BOUNDARY; NO_COMMON_BASE_COMPUTE",4,1);
assetCapacityRule=repmat( ...
    "E200MW_H100MW_C120MW_WHEN_ENABLED; OPERATING_VALUE_ONLY",4,1);
assetParameterStatus=repmat( ...
    "[假设值，待企业调研校准]",4,1);
assetStrategyClass=repmat("ASSET_BASELINE_OR_COMPARISON",4,1);
assetProductMixEnabled=false(4,1);
assetElectricityEnabled=[true;false;false;true];
assetHydrogenEnabled=[false;true;false;true];
assetComputeEnabled=[false;false;true;true];
assetComputeScenarioMode=repmat("FULL_FLEXIBLE_TASK_POOL",4,1);
assetComputeFacilityCapacityMW=120*ones(4,1);
assetComputeModuleCount=16*ones(4,1);
assetComparisonGroup=repmat("CH5_ASSET_STRATEGY_V1",4,1);

assetTable=table(assetScenarioId,assetScenarioLabel, ...
    assetTarget(:,1),assetTarget(:,2),assetTarget(:,3), ...
    assetAllocationBoundary,assetCapacityRule,assetParameterStatus, ...
    assetStrategyClass,assetProductMixEnabled, ...
    assetElectricityEnabled,assetHydrogenEnabled, ...
    assetComputeEnabled,assetComputeScenarioMode, ...
    assetComputeFacilityCapacityMW,assetComputeModuleCount, ...
    assetComparisonGroup,'VariableNames',designTable.Properties.VariableNames);
designTable=[designTable;assetTable];
end
