function combined = assemble_c5_23_strategy_table( ...
    legacySummaryFile,optimalSummaryFile,outputFile)
%ASSEMBLE_C5_23_STRATEGY_TABLE Merge 22 fixed-share cases and free optimum.
error('C5:Retired23StrategyRanking', ...
    ['The model-derived causal strategy must not be ranked as a 23rd ', ...
     'fixed policy. Use the two separate outputs produced by ', ...
     'run_c5_typical48_causal_comparison.']);
legacy=readtable(legacySummaryFile,'TextType','string');
optimal=readtable(optimalSummaryFile,'TextType','string');
n=height(legacy);
combined=table(legacy.scenarioId,repmat("FIXED_SHARE",n,1), ...
    legacy.realizedElectricityInputShare, ...
    legacy.realizedHydrogenInputShare,legacy.realizedComputeInputShare, ...
    legacy.renewableUtilization,legacy.eCurtailmentMWh,legacy.ensMWh, ...
    legacy.economicNetCostCNY,-legacy.economicNetCostCNY, ...
    false(n,1),legacy.status, ...
    'VariableNames',{'scenarioId','strategyType', ...
    'realizedElectricityInputShare','realizedHydrogenInputShare', ...
    'realizedComputeInputShare','renewableUtilization', ...
    'eCurtailmentMWh','ensMWh','economicNetCostCNY', ...
    'operatingNetBenefitCNY','modelSelectedEconomicOptimum','status'});
freeRow=table(optimal.scenarioId,optimal.strategyType, ...
    optimal.realizedElectricityInputShare, ...
    optimal.realizedHydrogenInputShare,optimal.realizedComputeInputShare, ...
    optimal.renewableUtilization,optimal.eCurtailmentMWh,optimal.ensMWh, ...
    optimal.economicNetCostCNY,optimal.operatingNetBenefitCNY,true,"PASS", ...
    'VariableNames',combined.Properties.VariableNames);
combined=[combined;freeRow];
[~,economicOrder]=sort(combined.economicNetCostCNY);
[~,utilizationOrder]=sort(combined.renewableUtilization,'descend');
combined.economicRank=nan(height(combined),1);
combined.utilizationRank=nan(height(combined),1);
combined.economicRank(economicOrder)=(1:height(combined))';
combined.utilizationRank(utilizationOrder)=(1:height(combined))';
writetable(combined,outputFile);
end
