function phaseSummary = c5_summarize_product_mix_48h_phases( ...
    results,designTable,scenario)
%C5_SUMMARIZE_PRODUCT_MIX_48H_PHASES Build reproducible phase ledgers.

phases=unique(scenario.hourly.phase,'stable');
records=cell(0,1);
row=0;
for i=1:numel(results)
    if ~isstruct(results{i}) || ~isfield(results{i},'dispatch')
        continue
    end
    r=results{i};
    d=r.dispatch;
    in=r.input;
    cfg=r.config;
    for p=1:numel(phases)
        idx=scenario.hourly.phase==phases(p);
        row=row+1;
        records{row,1}=table( ...
            designTable.scenarioId(i),phases(p), ...
            min(d.timeH(idx)), ...
            max(d.timeH(idx))+cfg.time.dispatchStepH, ...
            sum(in.pSourceAvailableMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pCableSendMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pElectrolyzerMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pComputeFlexibleMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pComputeBaseServedMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pCurtailmentMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pBessChargeMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pBessDischargeMW(idx))*cfg.time.dispatchStepH, ...
            sum(d.pInternalUnservedMW(idx)+d.pMarineUnservedMW(idx)+ ...
                d.pComputeBaseUnservedMW(idx))*cfg.time.dispatchStepH, ...
            'VariableNames',{ ...
                'strategyId','phase','startH','endH', ...
                'eAvailableMWh','eCableSendMWh', ...
                'eElectrolyzerInputMWh','eFlexibleComputeInputMWh', ...
                'eBaseComputeServedMWh','eCurtailmentMWh', ...
                'eBessChargeMWh','eBessDischargeMWh','ensMWh'});
    end
end
if isempty(records)
    phaseSummary=table;
else
    phaseSummary=vertcat(records{:});
end
end
