function [fixedSummary,modelSummary,fixedHourly,modelHourly] = ...
    run_c5_typical48_causal_comparison(outputDir,parallelWorkers)
%RUN_C5_TYPICAL48_CAUSAL_COMPARISON Baselines + 22 fixed, model separate.
%
% The synthetic all-channel 48 h case is not used for ranking. This runner
% selects one normal 48 h sample from the annual multi-source case. The
% three asset baselines and 22 given E/H/C policies form the fixed-policy
% comparison set. The causal model decision is reported separately and is
% not inserted as a 23rd ranked fixed policy.

thisDir=fileparts(mfilename('fullpath'));
c5Root=fileparts(fileparts(thisDir));
annualCode=fullfile(c5Root, ...
    '5.7混合最优策略短测试与年度运营分析','code');
addpath(fullfile(c5Root,'5.1场景设计','code'),annualCode,thisDir);
c5_add_v5_model_paths();
if nargin<1 || strlength(string(outputDir))==0
    outputDir=fullfile(c5Root,'5.3对比方案与模型最优策略', ...
        'results','typical_normal_48h_causal_v2');
end
if nargin<2 || isempty(parallelWorkers), parallelWorkers=1; end
assert(isscalar(parallelWorkers) && parallelWorkers==round(parallelWorkers) && ...
    parallelWorkers>=1,'parallelWorkers must be a positive integer.');

annualScenario=c5_build_annual_2025_multisource_scenario();
sample=c5_select_typical_normal_48h(annualScenario);
cfg=sample.config;
base=sample.input;
eventCode=sample.hourly.eventCode;

design=c5_product_mix_specs();
fixedDesign=design(design.strategyClass=="DISPATCH_SHARE_POLICY",:);
baselineDesign=design(ismember(design.scenarioId,[ ...
    "baseline_E_asset_only","baseline_H_asset_only", ...
    "baseline_C_asset_only"]),:);

nFixed=height(fixedDesign)+height(baselineDesign);
fixedRows=cell(nFixed,1);
fixedLedgers=cell(nFixed,1);
strategies=cell(nFixed,1);
r=0;
for i=1:height(baselineDesign)
    r=r+1;
    spec=baselineDesign(i,:);
    strategies{r}=struct('id',spec.scenarioId, ...
        'strategyClass','ASSET_BASELINE', ...
        'productMixEnabled',false, ...
        'electricityEnabled',spec.assetElectricityEnabled, ...
        'hydrogenEnabled',spec.assetHydrogenEnabled, ...
        'computeEnabled',spec.assetComputeEnabled, ...
        'eventReserveRule',false);
end
for i=1:height(fixedDesign)
    r=r+1;
    spec=fixedDesign(i,:);
    strategies{r}=struct('id',spec.scenarioId, ...
        'strategyClass','FIXED_HOURLY_EHC_POLICY', ...
        'productMixEnabled',true, ...
        'eShare',spec.targetElectricityInputShare, ...
        'hShare',spec.targetHydrogenInputShare, ...
        'cShare',spec.targetComputeInputShare, ...
        'shareTolerance',0.02, ...
        'eventReserveRule',false);
end
if parallelWorkers>1
    pool=gcp('nocreate');
    if isempty(pool) || pool.NumWorkers~=parallelWorkers
        if ~isempty(pool), delete(pool); end
        parpool('Processes',parallelWorkers);
    end
    parfor i=1:nFixed
        [fixedRows{i},fixedLedgers{i}]=c5_run_sequential_hourly( ...
            base,cfg,strategies{i},eventCode,false);
    end
else
    for i=1:nFixed
        [fixedRows{i},fixedLedgers{i}]=c5_run_sequential_hourly( ...
            base,cfg,strategies{i},eventCode,false);
    end
end
fixedSummary=vertcat(fixedRows{:});
fixedHourly=vertcat(fixedLedgers{:});
fixedSummary.comparisonSet=repmat( ...
    "BASELINES_PLUS_22_FIXED_HOURLY_POLICIES",height(fixedSummary),1);

modelStrategy=struct('id','model_causal_myopic_1h', ...
    'strategyClass','MODEL_CAUSAL_MYOPIC_SEPARATE_EVALUATION', ...
    'productMixEnabled',false,'eventReserveRule',true);
[modelSummary,modelHourly]=c5_run_sequential_hourly( ...
    base,cfg,modelStrategy,eventCode,false);
modelSummary.comparisonSet= ...
    "SEPARATE_MODEL_EVALUATION_NOT_FIXED_POLICY_RANKING";

if ~isfolder(outputDir), mkdir(outputDir); end
writetable(fixedSummary,fullfile(outputDir, ...
    'c5_typical48_baselines_plus_22_fixed_summary.csv'));
writetable(fixedHourly,fullfile(outputDir, ...
    'c5_typical48_baselines_plus_22_fixed_hourly.csv'));
writetable(modelSummary,fullfile(outputDir, ...
    'c5_typical48_model_causal_summary_separate.csv'));
writetable(modelHourly,fullfile(outputDir, ...
    'c5_typical48_model_causal_hourly_separate.csv'));
writetable(sample.hourly,fullfile(outputDir, ...
    'c5_typical48_selected_scenario_input.csv'));
sourceOutput=table(sample.hourly.timeUTC, ...
    sample.sourceDetail.availableBySourceMW(:,1), ...
    sample.sourceDetail.availableBySourceMW(:,2), ...
    sample.sourceDetail.availableBySourceMW(:,3), ...
    sample.sourceDetail.aggregateAvailableMW, ...
    'VariableNames',{'timeUTC','pWindAvailableMW','pPVAvailableMW', ...
    'pTidalAvailableMW','pTotalSourceAvailableMW'});
writetable(sourceOutput,fullfile(outputDir, ...
    'c5_typical48_multisource_available_output.csv'));
writetable(sample.selectionAudit,fullfile(outputDir, ...
    'c5_typical48_selection_audit.csv'));
save(fullfile(outputDir,'c5_typical48_causal_comparison.mat'), ...
    'fixedSummary','modelSummary','fixedHourly','modelHourly', ...
    'fixedDesign','baselineDesign','sample','sourceOutput','-v7.3');
end
